### ISSUE TITLE
Add more diversity to the lineup of NPC portraits

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1006]
I've been thinking lately about how, erm, white Naev's NPC lineup is. I can't work on this of course (I'm no good at drawing), but it occurs to me that the collection of NPC portraits should be diversified.

Adding more NPCs with different ethnic backgrounds would not only be a nice gesture to people of color, it would also make Naev's lineup of NPCs more varied.

Obviously no-name NPCs should get this treatment, but I would say that unique portraits should get this treatment too. Currently we just have a single black unique NPC; I think more unique NPCs should be people of color (and with a greater variety of apparent ethnic backgrounds).

I would also note that in resolving this issue, we should take care not to let our unconscious biases seep in, such as by portraying black people as criminals or some such thing (which actually seems to have seeped into the lineup of pirate NPC portraits, so working on that might be worthwhile).

**Comment by agb32** [comment]
Perhaps not just known colours, but a whole range of different colours - who knows what evolution will do to us in the next few 000 years...?

**Comment by onpon4** [comment]
Well the Soromid would be a good place to do unusual colors (and blue people - agyria - from silver poisoning is a real thing), but for everyone else I imagine we probably want to be more grounded.

Chances are what'll happen in our continuing evolution is we'll get darker on average. There wouldn't be any evolutionary pressure to color the skin in a weird way, the only pressure that causes more or less pigment in skin is more or less sunlight. If we want fanciful colors (outside of the Soromid) it would make more sense to put those in hair and eyes.

This talk reminds me of another aspect that could use diversifying: the size of NPCs. Different weights, different face proportions, etc.

**Comment by bobbens** [comment]
https://opengameart.org/content/portraits-for-naev should be incorporated! (found by @onpon4 on discord)

**Comment by amylaar** [comment]
> Well the Soromid would be a good place to do unusual colors (and blue people - agyria - from silver poisoning is a real thing), but for everyone else I imagine we probably want to be more grounded.
> 
> Chances are what'll happen in our continuing evolution is we'll get darker on average. There wouldn't be any evolutionary pressure to color the skin in a weird way, the only pressure that causes more or less pigment in skin is more or less sunlight. If we want fanciful colors (outside of the Soromid) it would make more sense to put those in hair and eyes.

If we only think about existing pigment, a logical optimum is dark skin for radiation resistance, with vitamin D supplements
taken as a matter of course.  But not too dark, lest you can't find melanoma in time.  OTOH, if the rich don't breed and the
poor can't afford supplements, then 'white' people will be dominant planet-side in areas where vitamin D deficit is common and selective pressure from radiation is low.  Likewise, if you can't afford cancer screening/treatment, the cap on healthy melatonin would not be in effect.

The Soromid, however, would fix the metabolic pathways to synthesize vitamin D (and C, of course).  And do something about cancer.
Also fix the problem of overeating, and reduce the risk of starvation with photosynthesis.  That can give green or cyan pigments.  When it comes to radiation hardening, both literal black and white have their merits.  Black could absorb harmful radiation, and help dissipate excess heat.  White can reflect radiation, and avoid taking in too much heat from the outside.  White subcutaneous pigment can be well combined with green or cyan epidermal pigment to combine photosynthesis with radiation resistance and also boost the photosynthesis a bit.
But the physiological effects would likely be drowned out by mate choice.  What if you could consciously affect the pigment
patterns on your skin?  Maybe a true practitioner of the art could produce something as intricate as tattoos, or as swiftly
changing as animation.  Body language would get a whole new meaning.

Most Za'lek would wear accessories that help them with information access, unless they have an implant for that purpose.
Many will also prefer functional clothing.  Although pure functional clothing can't be effectively washed or mended, that
doesn't matter, since it can't get dirty or damaged in the first place (by definition - that would be internal state).
 
> This talk reminds me of another aspect that could use diversifying: the size of NPCs. Different weights, different face proportions, etc.

High gravity worlds and high acceleration ships would favour stocky midgets.  People living in zero-G space stations would be fine with weak, spindly limbs that can reach farther to find a hand-hold.

**Comment by onpon4** [comment]
Hi @amylaar, just wanted to let you know that I've edited your post's wording slightly. Please contact me via email (diligentcircle@riseup.net) or via Discord (diligentcircle 丸#5156) in case of any questions or issues pertaining to this edit.

🕵️

**Comment by bobbens** [comment]
Since we're moving to needed artwork in the Wiki, I have create https://github.com/naev/naev/wiki/Needed-Artwork:-Characters and explicitly mention diversity is important. If you think anything else should also be mentioned please feel free to edit. Closing issue.
