### ISSUE TITLE
[Proposal] Trade Interface

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1007]
Now that we have a basic economy thing working with #1002 we can start thinking of actually letting the player plan trade routes with some sort of visualization.

**Comment by agb32** [comment]
(as an aside - did I dream it, or did we used to have a map view of each solar system with the planets etc shown, and clicking on them gave information?  Could have been another game, but I can't think what unless Frontier:Elite)

**Comment by BTAxis** [comment]
The only thing that matches that description is the map editor.

**Comment by Mutos** [comment]
I remember discussions years ago, about adding a map to the "Commodity" tab. That would be an inset map like on the "Missions" tab, but showing known price delta for the currently selected commodity being displayed on systems. The issue would be which "known" price to show...

**Comment by agb32** [comment]
The known price could be the suggested rolling average at each place previously visited... and selecting a commodity (e.g. Food) would show price deltas for that commodity.
There would be a slight complication here, because a system has multiple assets/planets all of which can have slightly different prices.  Perhaps an overlay in the main map window might also help.

**Comment by Mutos** [comment]
> There would be a slight complication here, because a system has multiple assets/planets all of which can have slightly different prices

"slightly" in what respect? Maybe displaying an average or an interval would do if multiple planets are present in the same system, or maybe the differences are too important and it makes no sense.

**Comment by agb32** [comment]
An average, or maybe the best trade perhaps... either would give the player an idea... (which is all they need, since the prices vary with time anyway, so will be different by the time they arrive!)

**Comment by PhoenixRiver** [comment]
Maybe display the best and worst prices that the player has seen in
that system? Though if there are wildly different planets in one
system (quite often the case in physical terms, don't know if that is
the case with the new trade stuff yet) that might not work so well,
ditto the averaging...

What about a small spot of colour on the scale from deep blue to deep
yellow stacked one next to the other for each trade point in the
system (using their system map co-ordinates to place them in a minimum
sized square). Deep blue would indicate a serious "surplus" (i.e. low
price) of the commodity and deep yellow a serious "lack" (i.e. high
price) of the commodity in comparison to the trade place they are
currently in - this means that you wouldn't have to worry about slight
fluctuations and also that you could more easily show prices for nine
or even sixteen trading depots per system relatively compactly and
make the map less cluttered (I'm presuming here that the map is only
showing prices for one commodity at a time...)
One issue would be the need to have a(n approximate) maximum and
minimum price for each commodity but it needn't be exactly accurate,
just a close approximation.
Alternatively the scale for the colouring could depend on a percentage
profit with very good and very bad profit possibilities just round off
to the end of the scale e.g. a 10% profit/loss per unit of commidity,
it depends on what sort of profits are generally available I guess...
due to the lack of trading I've not really thought about it for Naev
but anything between 1% and 10% seems to be a good profit depending on
which game you are playing, one or two even seem to cap your profit
from a single run adjusting prices at your destination to stop you
making too much profit...

Anyway, just a thought,

River *<:@)

**Comment by agb32** [comment]
I like the idea of dots etc.  Rather than a max/min, we could use a mean and standard deviation - that would only require 3 bits of data for each planet/commodity in the save file.  And this would probably be even better than the moving average - particularly while the economy remains sinusoidal - and we could always look at something different when things change.

**Comment by agb32** [comment]
Have made a start on this with pull request #1011.  This adds numeric data in the commodity tab when landed, and saves necessary economy information in the save file - basically amounting to 4 values per commodity per planet visited, so not huge.

The price at which the player last bought the commodity are also shown/saved.

Once this is merged, I'll move on to creating lua hooks, and a person at the bar who can randomly give out recent prices on a planet in a nearby system - which will get included in the information saved, thus helping the player to build up their economy information - and also giving them a good reason to keep visiting the bar.

As an aside, is it worth adding a medium and large cargo pod, now that there is a reason to trade?

After that some pictoral information on the map...

**Comment by agb32** [comment]
Can anyone advise:  How does this lua look - I'm not a lua expert!  To go in npc.lua
(sorry, code insert doesn't seem to work with lua - at least, not that I can get it to!)

-- Returns an economy message, and updates known economy information accordingly.
function getEconMessage(fac)
   -- Select a planet in a nearby system which has commodities for sale.
   sysList = getsysatdistance( max=3, hidden=true )
   if #sysList == 0 then
      return getLoreMessage(fac), nil
   end
   -- get a message string.
   local retmsg = msg_econ[rnd.rnd(1, #msg_econ)]
   -- Select a system - try up to 10 times.
   for i=1,10,1
   do
      local sys = sysList[rnd.rnd(1, #sysList)]
      jumpdist = sys:jumpDist()
      t = time.get() - time.create( 0, 2 * jumpdist, 0 )
      for key, planet in ipairs( sys:planets() ) do
         commodities=planet:commoditiesSold()
         if #commodities > 0 then
	    coststr="\n"
	    for cname, commod in ipairs ( commodities )
	    do
               price=commod:priceAtTime(planet,t)
	       coststr = coststr..stringformat("%s -> %d\n", cname, price)
            done
	    local myfunc = function()
	                      planet:recordCommodityPriceAtTime(t)
			   end
            return retmsg:format(planet:name(),system:get(planet),coststr), myfunc
         end
      done
   done   
   return getLoreMessage(fac), nil
end

**Comment by agb32** [comment]
![image](https://user-images.githubusercontent.com/9550289/84444535-ef87f700-ac39-11ea-98da-732461a16961.png)

**Comment by BTAxis** [comment]
Off the top of my head, it seems you're doing something similar to getsysatdistance() in dat/scripts/jumpdist.lua. You may be able to offload some lines by using that. Or better yet, standardize your economy-related logic into a helper script, sounds like it could come in handy one day.

**Comment by agb32** [comment]
It uses getsysatdistnace() on line 4...
The idea then is that it randomly chooses one of the systems, and iterates through the planets.  Then if number of commodities > 0 , it prepares the message.  Actually, that's just made me realise, I should choose a planet randomly, otherwise, it will always be the same one in a system.
Is there a better way of testing it, than just fire it up and see what happens?

**Comment by BTAxis** [comment]
You could write some debug output, load the script in the console, and run it from there.

**Comment by agb32** [comment]
Having problems here - can anyone help please... (lua pasted below)
It is basically working, and for any NPC that has this type of message, "Making func for [planet]" always gets printed.  However, when you speak to that person, it seems random as to whether the message "Func called for [planet]" gets printed, i.e the function doesn't always get evaluated.
For cases where it works, then the message gets printed as many times as you approach that person.  For cases where it doesn't work, it never gets printed (and the c function doesn't get called), even if you approach the person many times.  Could be something to do with local/global variables, but I can't see what.  
I've not worked out a pattern for when it works and doesn't.  In cases where there are >1 ncp with this type of information, again, for some it works, for others it might not...


![image](https://user-images.githubusercontent.com/9550289/84580051-60124d80-adcb-11ea-842e-3080c9f48a58.png)

**Comment by bobbens** [comment]
You should use three backticks around code to put it on github instead of using images. Quickly glancing over it, it looks fine (you could make syslist local though). However, where is it getting called?

On a side note issue #1028 on making commodities searchable would be related to this.

**Comment by agb32** [comment]
That will do it - I was trying 1 back tick (which is what I get if I click the "insert code" button.
Its getting called in the spawnNPC function in npc.lua.
There is something odd going on which I don't understand:  just before the return, if I ```print(myfunc)``` it returns an address as expected.  However, if I then do the same in the spawnNPC function just after it was called, sometimes it prints the function, and sometimes nil.  I have a couple of other things to try, but its a bit wierd!
I'll take a look at #1028.

**Comment by agb32** [comment]
Problem solved - within getJumpMsg, I had changed it to return getEconMsg instead of getLoreMsg, but hadn't removed the ```, nil``` at the end of the line which was breaking it... all sorted now, and pull request made.

**Comment by agb32** [comment]
Pull request now also made #1080 which displays economy information on the map.

**Comment by agb32** [comment]
I notice that the work discussed above about talking to npcs has been reverted and replaced with a news item.  I think it should be reverted back because:
1. Having economy information in the bar gives good reason to always visit the bar, since if you get econ info from it, it will build up your economy statistics.
2. Having it in news will mean that the player will always benefit whether they read it or not, and for all neighbouring systems.   Economy info will be built up too rapidly.

I think onpon4 did this, probably without realising that it adds to the players savefile information.  Commit was ab7f8bd, and a few after that.  Followed by ce51bcf and 021f22d

**Comment by bobbens** [comment]
I think this is mainly covered in latest master.
