### ISSUE TITLE
Bad strings

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1021]
During translations, I noticed some mistakes in the original strings.

Here's a list of what I found so far (and I explain why it's wrong):

* Factor used to divide the above resolution with
    * Wrong word. The word “factor” is for the operands in multiplication. For division, the first operand is called “dividend”, the second one is “divisor”, and the result is called “quotient”: https://en.wikipedia.org/wiki/Division_(mathematics)#Notation
* Size of the OpenAL music buffer (in kilobytes).
    * “kilobyte” is ambigious. 1000 or 1024? Could use “kibibyte”? https://en.wikipedia.org/wiki/Binary_prefix
* Font sizes (in pixels) for NAEV
    * “NAEV“ → “Naev”
* tonne
    * Game is sometimes saying “tonne“, sometimes saying “ton”. Pick one.
* Jump for system '%s' not found in system '%s' for removal.
    * The grammar sounds kind of weird. Not sure
* Joystick of index number %d does not existing, switching to default 0
    * “does not existing” = grammar failure
* article is invalid.
    * Not capitalized
* Planet '%s' does not belong to a system..
    * Double “.“
* To use a modifier key hit that key twice in a row, otherwise it will register as a modifier. To set with any modifier click the checkbox.
    * Missing comma after first “key”
* \apAutonav continuing until destination (%d jump%s left).
    * What does `%s` resolve to? The English plural “s”? If yes, very very bad idea, it should be obvious that it will not work for other languages. Just use Gettext's plural system here
* Player starts out in non-existent or invalid planet '%s',trying to find a suitable one instead.
    * missing space after comma
* Uknown
    * typo

I will extend the list when I find more strings.

**Comment by Wuzzy2** [comment]
Mor strings:

* The given link exists in the Vorbis data stream, but is not decipherable due to garbacge or corruption.
    * “garbacge” → “garbage”
asteroid field in %d has less than 3 corners.
    * “asteroid” → “Asteroid”

**Comment by Wuzzy2** [comment]
More strings:

* The given link exists in the Vorbis data stream, but is not decipherable due to garbacge or corruption.
    * “garbacge” → “garbage”
* asteroid field in %d has less than 3 corners.
    * “asteroid” → “Asteroid”

**Comment by onpon4** [comment]
I've fixed most of these in #1055 (only excluded a couple I think are ambiguous). Couple comments:

* Naev is definitely guilty of not using ngettext where it should (and yes, that %s appended an s to that string, though I've fixed it in my PR). That might warrant its own issue. Actually Lua code doesn't even have access to ngettext; not sure what needs to be done to fix that.
* "Tonne" is the correct term for cargo weight since what we're referring to is indeed a tonne (or metric ton). Of course colloquial usages have to be distinguished (like "I've got tons of credits"; that should use "ton" rather than "tonne"). I've changed as many uses of "Ton" to "Tonne" as I could find; of course "ton" is not something that's easily greppable since it's a fairly common 3 letter combination (found in "button" for example).
* The entry whose grammar you were confused by ("Jump for system '%s' not found in system '%s' for removal") is a warning that prints when the game tries to remove a jump from a system, but the system doesn't have the jump to begin with.
* I didn't find "Uknown" in either the C source or the dat folder with grep -r. I think this may be a leftover entry.
* The thing about asteroid fields and corners isn't in the code anymore; in fact it refers to a way of defining asteroid fields that doesn't exist anymore.

**Comment by Wuzzy2** [comment]
More typos:

* We value our autonomy. We don't want to be ruled by those megalomanic Dvaered Warlords! Can't they just shoot at each other instead of threatening us? If it wasn't for the Liberation Front...
    * megalomanic → megalomaniac
* Did you know that if a planet doesn't like you, you can often bribe the spaceport operators and land anyway? Just hail the planet with 
    * Is this string missing something?
* If you're having trouble with overheating weapons or outfits, you can press 
    * Is this string missing something?
* Hey, you ever wonder why we're here?", you say, "It's one of life's great mysteries isn't it?", the citizen replies, "Why are we here? Are we the product of some cosmic coincidence or is there some great cosmic plan for us? I dunno, but it keeps me up at night" ... "What?? No, I mean why are we in here, in this bar?
    * Missing quoation marks at end and finish?
* I  haven't got all day.
    * double space
* "Greetings, %s," the pilot of the Vendetta says to you as soon as you answer his hail. [...]
    * First, this string mentions system by `%s`, but at the end, same system is mentioned by hardcoded name „Pas“
* Use %s to respond to the hail 
    * trailing space
* You walk up to a scrappy little man leaning against the bar. You sit next to him, and he eyes you up and down. You return the stare cooly. Lackadaisically, he strikes up a converrsation.
    * converrsation → conversation
* "Look, I really can't tell you the exact contents of the box. Let's just say it's "small" weaponry. My... employer... isn't fond of the government of %s. As such, he needs... "
    * "small" → 'small' (inner quotation marks should be different)



Factually incorrect strings:
* Good. If you look at the bar at the bottom of the screen, you'll see that it has changed to show that you have selected a hyperspace target (next to "Nav"). [...]
    * Not true for all GUIs. In some GUIs like `brushed` its at the top, in others, its at bottom
* But watch out! That jump just now has drained your fuel reserves, as the bottom bar will tell you
    * same
* Once landed, you will be presented with the landing screen. This is the default screen for all planets or stations you land on. The landing screen gives you information about the planet or station in general and lets you refuel.
    * but refueling is automatic since a very long time now
* The trade system is currently in an early stage of development. Once the system is more developed, it will be explained in a separate tutorial.
    * Still true?


Player character gender:
* You look like a man in need of a couple spare credits.
    * the gender of the player character is not often explicitly mentioned in the game except in a few missions like this. It's always male. Intentional?
* You feel a very large hand slap you on the back. "Thats a lad!" he cries exuberantly. "I'll have my boys load up the cargo, as quickly as you please. 
    * same
* "You say you want this job, but you don't have enough cargo room for this assignment, little man!" Ragnarok turns away, displeased at wasting a whole 5 STU on you.
    * same
* "Well, thats your choice boy. Be on your way now. I'm busy."
    * same

**Comment by onpon4** [comment]
Most of these are invalid. I've fixed the valid ones.

> megalomanic → megalomaniac

I've opted to just remove this word entirely because it has a sanist vibe to it anyway. The fix is in #1057.

> Is this string missing something?

They're not, those are old outdated strings which were split into parts rather than using %s formatting properly. I just checked, they were removed some time ago.

> Missing quoation marks at end and finish?

No, that's intentional. The code actually inserts quotation marks at the start and end. Probably not the best idea, so I've changed that in #1057.

> I haven't got all day.

I couldn't find this with a grep -r search, so I think it's been removed. (It might have been a portion of a mission whose text has changed; there have been a lot with bad writing that I've fixed up.)

> First, this string mentions system by %s, but at the end, same system is mentioned by hardcoded name „Pas“

I actually just fixed that incidentally in a separate commit. :slightly_smiling_face:

> Use %s to respond to the hail 

Doesn't seem to exist anymore. Probably a part of the old tutorial.

> converrsation → conversation

That was fixed some time ago along with the rest of the issues with the text in the Heretic campaign. That entire string has been changed since the gettext file was updated.

> "small" → 'small' (inner quotation marks should be different)

Same deal here. That was old text from the Heretic campaign.

> Factually incorrect strings:

Those are all from the old tutorial, which no longer exists.

> Player character gender:

I fixed those all quite some time ago. Most of those are again from the Heretic campaign, whose text was almost entirely rewritten.

**Comment by Wuzzy2** [comment]
New bad strings:

* "Hello there," he begins to speak, "I'm sure you have quite a few questions. My name is Shaman and I am a proud  commander in what is known as the Nasin. We are currently terrorize the Sirius overlords that control %s
    * double space (after “proud”, grammar
* Your not sure exactly what to expect, but you think that they've been expecting you.
    * grammar
* Your payment of %s was credited  to your account.
    * double space (after “credited”)
* [...] My sincerest apologies for being absent. [...]
    * Has opening quotation mark at start, but no closing quotation mark at the end
* [...] I hope its good enough"
    * Missing period at end
* At this, he runs off to helps a group of elderly citizens who are struggling against the tide of people.
    * helps → help

> Those are all from the old tutorial, which no longer exists.

OMG nooo! This means I have translated a large chunk of text for nothing! :-( Whatever …

**Comment by Wuzzy2** [comment]
* Input must be at least %d character%s long!
    * Another plural thing?

**Comment by onpon4** [comment]
> New bad strings:

Those all are no longer used. (Just did a grep -r in the dat directory.)

> OMG nooo! This means I have translated a large chunk of text for nothing! :-( Whatever …

So far as I understand the organization of translation files is a mess at the moment, so there are probably a lot of old strings which no longer exist.

> Another plural thing?

Yes. I've just pushed a fix to #1059.
