### ISSUE TITLE
Green text is hard to read

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1022]
I find it hard to read the green text on the gray windows. The contrast is very bad.
Can you please try to tweak the text color to make it more readable?

c6bf63993f3ca8d11bce627217b173ed6e18bb4b

**Comment by onpon4** [comment]
I actually tried to fix this but couldn't figure out what actual color was being used for certain green text.

Honestly I think removing colored text entirely should happen because of #868 if nothing else.

**Comment by Wuzzy2** [comment]
I am in favor of the colored text as its good to direct player's attention to something. However, highlighted text MUST be still be perfectly readable for obvious reasons.

I think/hope this is just a matter of finding the right color.

**Comment by onpon4** [comment]
It's only good at directing attention for color-sighted players. There are better ways to attract attention that don't require color-sight, like bold, underlined, or italic text, or other visual indicators.

**Comment by Wuzzy2** [comment]
Good point.

**Comment by bobbens** [comment]
Colours are defined in src/colour.c. In particular, I think cDConsole is being used and is hard to read. Honestly, this needs quite a rehaul. Bold and other fonts might be a bit trickier to do. In that sense, maybe moving to some sort of markdown might be better, but that will require quite a lot of modifications.

**Comment by onpon4** [comment]
Markdown support does come to mind as a good option.

**Comment by bobbens** [comment]
The thing is how far down the rabbit hole do we go? One option I have always thought of is using some sort of full-blown renderer (html / markdown), rendering to a framebuffer, and just displaying that. The framebuffers would be cached and freed by a garbage collector. This would be fairly hard to implement properly, but if done well, would allow infinite flexibility. Another downside would be most likely another dependency.

**Comment by onpon4** [comment]
I'm not too worried about another dependency personally as long as it's adding something good (text markup, which could have lots of applications).

That said, I don't think we need *full* HTML / Markdown, just some key parts (inline parts basically). So it would probably be sufficient to make an in-house solution. It could even be less than Markdown, e.g. foregoing options for how to mark up text in favor of something more simplistic. Like just supporting `*italic*`, `**bold**`, `_underline_`. If you made it simplistic like that it shouldn't be any more complicated than the `\a` weirdness we currently do for colors.

**Comment by bobbens** [comment]
Italic and bold should be fairly easy to do, underline also if we do it on a per-character basis. However, I would argue that either way, using framebuffers and caching would be much more scalable than the current solution of rerendering everything all over every frame (which does lead to fps drops with lots of text). This solution would also allow more complex markdown libraries and such to be used for "free", so it wouldn't just be overengineering. That said, it is a fairly major overwork. For 0.8.0, it might be best to just do some minor colour tweaks only.

**Comment by BTAxis** [comment]
Surely all of this doesn't make the original point moot, though? Obviously having something that's readable by color blind people is a good thing, but that's not to say we can't also have color coded text. Which means we need a hue of green that's readable against the background..

**Comment by bobbens** [comment]
Looking over it a bit, I think the problem is we define colours, but they behave the same over any background. This makes it so the console colours, although easy to read on some backgrounds, become harder to read on other backgrounds. Obvious examples would be darkened "disabled" buttons are much harder to read than other ones.

Possible solutions:
1. Define different colours for different situations and add conditionals for that.
2. Use shaders to try to take this into account.
3. Reduce the use of background colour changes.
4. Not use colours and use bold/italic instead

However, I agree with @BTAxis in that colours and markdown stuff are complementary, so we should either try to solve it by 1 or 2. The 3rd option does also seem a bit tricky.

**Comment by Wuzzy2** [comment]
You are overthinking this way too much... XD Just pick a readable color.

Try `#007200`.

See test text here (made in GIMP):
https://satoshiupload.com/images/QKpTSHzu9p.png

It needs to be that dark because it needs to be readable against all shades of gray in the background (the background is a gradient).

Oh, I also see that the greeting message in the Lua console uses a different green, which is even brighter (and less readable). I suggest to change the color of that as well.

**Comment by onpon4** [comment]
@Wuzzy2 Naev uses colors all over the place and they're defined in a messy way. It took me quite a while to fix even problems with shades of gray, and with full color it's even harder. Yes, *for now* we need to just pick a color that works better (since a full solution would be a big undertaking), but that shouldn't be the be-all-end-all.

@bobbens I don't know how shaders would be used for coloring, but the main thing I'm in favor of is making the use of color consistent in a node, so to speak, and reducing the number of colors substantially. Something like your typical CSS design; on this page for example almost all text is black or white, and the only colored text is a couple of links (which display one additional color). By keeping the number of colors down and giving priority to black for light backgrounds and white for dark backgrounds, you keep the color profile simple to adjust and check. In that sense, color-coded text (as opposed to some segments, like buttons, having different colors defined) is a maintenance burden with no real benefit.

FWIW I can't actually think of any game that over-uses colors as much as Naev does. Most just don't support any kind of markup at all. Naev might be a special case, but even so, color markup isn't a very good solution even when you're talking about shades of gray.

The main thing Naev uses color for is the starmap, where it tells you if any given planet is unoccupied, neutral, restricted, friendly, or hostile. Rather than using colors (which are arbitrary anyway), we should instead use symbols of some kind here. Emojis come to mind as one possible option (albeit probably pre-rendered so we don't have to worry about what font we're using). You could, for example, use ❤️ for friendly planets, 👍 for neutral planets, 👎 for restricted planets, and ☠️ for hostile planets (and no symbol for uninhabited planets). Then you could get rid of this text coloring nonsense we currently have altogether. (This would suffice for other uses of color as well, where we use green and red to mean "increased" and "decreased"; we could replace the use of green with 👍 and the use of red with 👎. Or we could use arrows instead.)

**Comment by BTAxis** [comment]
> FWIW I can't actually think of any game that over-uses colors as much as Naev does. Most just don't support any kind of markup at all.

That's not true at all. A lot of games use color coded text all over the place, especially in places like tooltips and in-game help texts. It's common practice, and I wouldn't say Naev "over-uses" it by any stretch of the imagination.

**Comment by bobbens** [comment]
> > FWIW I can't actually think of any game that over-uses colors as much as Naev does. Most just don't support any kind of markup at all.
> 
> That's not true at all. A lot of games use color coded text all over the place, especially in places like tooltips and in-game help texts. It's common practice, and I wouldn't say Naev "over-uses" it by any stretch of the imagination.

I would actually argue that Naev *underuses* colours with respect to most games. 

Thinking of fairly easily solutions. Naev uses lots of gradients in the toolkit, however, modern toolkits like the newer android ones have gone back to flat stuff. By switching to flat (should be fairly easy in the code) colours we should not only be able to gain font readability, but it should be much easier to control the color combinations.

Thinking of markdown, another thing I would like to wish for is something like hover-over tooltips which could be helpful with lore (like hover over faction names or NPC names to get brief descriptions, etc.). Probably should open another issue for markdown stuff ;)

**Comment by onpon4** [comment]
Well maybe my exposure to games is too limited to notice.

In any case, most of this is unnecessary and it's not colorblind-accessible (and on that note, most games aren't colorblind-accessible, so I wouldn't look to them for insight on how to use color). Headings don't need to be a different color at all, so we could change that to black right away with no ill effect. Planet status could be indicated with emojis or emoji-like graphics like I suggested above, and same for indication that some stat is good or bad, or that some stat has increased or decreased. Key indications in the tutorial and by NPCs could switch to bolded text, non-broadcast status messages could switch to italic text, and the current objective could be indicated with some kind of marking (like again an emoji or emoji-like image).

**Comment by onpon4** [comment]
On the suggestion I had earlier, we could use this font: https://www.google.com/get/noto/help/emoji/

If the engine can support rendering emojis directly then that could be used as a font; if not we could take the corresponding SVG images and either use them directly or convert them to PNG for use in-game. It would be a fairly easy thing to do.

**Comment by BTAxis** [comment]
> In any case, most of this is unnecessary and it's not colorblind-accessible (and on that note, most games aren't colorblind-accessible, so I wouldn't look to them for insight on how to use color). 

I agree that we can make allowances for color-blind people, and indeed should in situations where ambiguity would otherwise result. But it makes no sense whatsoever to remove colors just because a small demographic can't benefit from them.

Some text coloring is clearly unnecessary, though, particularly the headings. I'd as soon make them black, or maybe a dark blue for slight aesthetic effect. On the other hand, things like the highlighted hotkey on buttons are useful and shouldn't be removed. Similarly, the red/green coloring for positive/negative effects is something that ain't broke, and needs no fixing.

**Comment by onpon4** [comment]
Difficulty telling the difference between red and green is the most common form of colorblindness, and it's probably more common than you think.

> As many as 8 percent of men and 0.5 percent of women with Northern European ancestry have the common form of red-green color blindness."
- https://web.archive.org/web/20160728003639/https://nei.nih.gov/health/color_blindness/facts_about

The main reason to remove colors altogether is to unify the experience and prevent issues related to color accessibility from being overlooked as they usually are in the mainstream video game industry and have been in Naev for years. And, importantly, to ease testing for colorblind accessbility - but also to ease testing for color contrast in general, since it's usually quite obvious if you should prefer white or black, while other colors aren't so simple. We can see that taking effect with this very issue, where some shades of green worked great for a slightly darker gray but not the current shade. And it's not the first case; the first case was a shade of silver text that was rendered nearly invisible by the background color change.

I'm not opposed to the use of any color *at all*, but the only usage of color should be what you mentioned for headers - stylistic. Very very slight variations used sparingly to make things look nicer, not unlike what you find in CSS styling. But for text that needs to be legible, we should be highly favoring black or white text, with colorblind-friendly indicators like symbols, bolding, or italics for any visual indication of information.

Regarding button hotkeys, I'm not so sure we should have those at all, but if we should, the usual way to indicate that is just by underlining the corresponding letter. That would probably look better anyway.

**Comment by BTAxis** [comment]
> The main reason to remove colors altogether is to unify the experience 

There is *no* reason why the experience needs to be unified. Color enriches the experience for those who can see color normally, and that's okay. There is no need to feel that this is somehow unfair to those who can't see the colors.

**Comment by onpon4** [comment]
That's not the point.

The point is that you and I can see color and naturally will have an inclination to do things that disadvantage colorblind people; this is how Naev got into this mess of not having colorblind support in the first place.

Besides, whether this use of color is aesthetically pleasing is subjective, and there are ways to do the same thing that work for colorblind people, too. Honestly I hate the look of colored text anyway; it reeks of 1990s Web design. A small, carefully selected selection of colors for aesthetic purposes looks much nicer.

Are you opposed to the idea of using ❤️👍👎☠️👉 icons to indicate most of the things colors currently do, as well as support for bold / italic / underlined text for the few cases where inline color variation is used?

**Comment by onpon4** [comment]
By the way, here's one other thought that comes to mind regarding contrast issues, particularly where text can be over both light and dark parts:

Use white text, but put 4 black copies behind that white text shifted in each cardinal direction. This is something Project: Starfighter does and it helps enable the text to be more visible in more places. More or less a simple black outline. Just a thought. (It would be especially helpful for the floating text in the GUI, but could be used everywhere white or light-colored text is used to improve contrast.)

**Comment by BTAxis** [comment]
> The point is that you and I can see color and naturally will have an inclination to do things that disadvantage colorblind people; this is how Naev got into this mess of not having colorblind support in the first place.

This is blowing things out of proportions quite a bit. Accommodating colorblind people is fine, but there is no *obligation* to do so, to the point where the game experience is being watered down for regular people. Which, yes, I say is what would happen if we removed text color coding. The practice is such a staple in game UI design and makes perfect sense for the player base at large.

If someone is actually feeling hindered in their ability to play the game as a result, *and I have not seen any evidence that this is the case*, then we address it. Otherwise, this whole discussion is about finding a solution to a non-existent problem.

> Are you opposed to the idea of using ❤️👍👎☠️👉 icons to indicate most of the things colors currently do, as well as support for bold / italic / underlined text for the few cases where inline color variation is used?

Not at all. Having pictographs for various things is a great idea, and we shoud definitely do it. We're already doing it in some places. I just don't think that means we should also remove the color coding for text.

> I think if we did that, then removed text coloration, the result would be much easier on the eyes (better contrast), nicer looking overall, and we would take a positive step for colorblind accessibility.

You can have your cake and eat it too by adding in a check box in the menu that does exactly this. You can have your color-blind legibility without cutting down the design to the lowest common denominator.

**Comment by onpon4** [comment]
> This is blowing things out of proportions quite a bit. Accommodating colorblind people is fine, but there is no *obligation* to do so

I disagree. Ignoring the needs of colorblind users when they can be accommodated (i.e. Naev is not inherently a type of game that needs to require color sight) would be a subtle form of ableist discrimination.

By the way, that's my position as regards audio, too: just like color, any audio should be completely optional, both for the benefit of deaf users and for anyone who doesn't have working audio on their system. I've also thought of the possibility of removing the requirement for literacy to play the game by using text-to-speech or supporting screen readers somehow. We can and should solve problems like these as much as is feasible.

The only accessibility we can't provide is any ability which is fundamental to the game, such as sight itself (since it's a graphically-based game), or the ability to use a mouse and keyboard or compatible interface. Anything else, I would say that we do, indeed, have a moral obligation to include support for them as much as we feasibly can.

> to the point where the game experience is being watered down for regular people. Which, yes, I say is what would happen if we removed text color coding. The practice is such a staple in game UI design and makes perfect sense for the player base at large.

I've played and worked on several games that don't have a need for colored text displaying essential information. I don't see why Naev can't become one of them.

> If someone is actually feeling hindered in their ability to play the game as a result, *and I have not seen any evidence that this is the case*, then we address it. Otherwise, this whole discussion is about finding a solution to a non-existent problem.

Colorblind people exist and are quite common, so of course their ability to play is being hindered. You can even partially experience it if you turn a redshifter on with a very low color temperature. (And for the record, I have *personally* experienced this before, I actually have to turn off Redshift to play Naev for this very reason. Naev is unplayable without full color sight.)

> Not at all. Having pictographs for various things is a great idea, and we shoud definitely do it. We're already doing it in some places.

Great, I'm glad we agree on this at the very least.

> I just don't think that means we should also remove the color coding for text.

Removing color coding entirely is really a separate issue concerning contrast, which is very bad with some colors and hard to adjust because of just how many colors Naev uses. I would also say subjectively that it doesn't look aesthetically pleasing, and that removing these unnecessary uses of color will enhance the ability of all of us to properly develop the game with colorblind accessibility in mind.

> You can have your cake and eat it too by adding in a check box in the menu that does exactly this. You can have your color-blind legibility without cutting down the design to the lowest common denominator.

Yes, that would be a valid option, though it shouldn't be necessary if we do things right.

What that doesn't solve, though, is code and design complexity which makes changing these things as difficult as it is. If we only had to manage a small number of colors then contrast issues and the like would be easier to prevent.

Just to give some perspective, Project: Starfighter defines 17 colors total, and four of them (white, cyan, yellow, red) are used for text. Naev defines *59* colors, nine of which are explicitly used for text, but some other colors are actually used for text as well. Naev is a more complex game than Starfighter for sure, but doesn't 59 colors, and managing all of those to prevent contrast issues, seem excessive?

I'm not even advocating the removal of these colors. I'm just advocating the removal of *most* coloring of *text*.

I can even suggest exactly what colors we should have for text:

* Keep the purple text for system notifications, white text for pilot broadcasts and mission messages with the broadcaster in a gray color.
* Black text for TK text, keep just the blue highlighting of controls for tutorial and NPCs.
* White text everywhere else.
* Replace other color-coding with icons.

That would be a total of five colors: three for dark backgrounds, and two for light backgrounds. Much easier to manage, and colorblind-accessible. And this is subjective, but I think it would look nicer.

Adding black shadows behind non-black text could be very helpful too, as I mentioned before. It would essentially prevent contrast problems from ever occurring and give a lot more leeway as far as design of the backgrounds.

**Comment by BTAxis** [comment]
Oh, for- I'm not going to argue your politics, that's clearly a lost cause. To me, it all comes down to this:

> I'm not even advocating the removal of these colors. I'm just advocating the removal of most coloring of text.

My problem with this is that there is no *need* to remove coloring from text. It really isn't that hard to come up with a color scheme that makes everything easy to read. Make it all black for all I care. People who have trouble with the text can then use that scheme. What you're saying is that *everyone* should use the same scheme, and you've not given a good reason. The colored text has a function, and those who aren't visually impaired benefit from it. Why remove it? Because then everyone has the same experience? That's not good enough.

The best way forward that I can see is to put the text coloring scheme, or other markup scheme based on what Bobbens proposed, into a configuration of some sort. You'd define a markup per text class (such as "positive modifier", "negative modifier" etc), and markup all text with these classes as appropriate. We can just use some color coding scheme we like and assume that an average player will be okay with it. That is a fair assumption. In the event that someone has a problem with the color scheme, or even just doesn't like it, well then, it's easy to change.

Who loses in this scenario? Nobody. It's not even that hard to code.

**Comment by Wuzzy2** [comment]
This issue has gone WAAAAY to off-topic … It's really just about bad contrast of a particular type of text. This issue was NOT and was NEVER meant to become a full rework of everything, lol.

At least open a new issue for colorblindness … And be specific. Then we can talk.

**Comment by onpon4** [comment]
@Wuzzy2 #868 is the issue. It's not new. We're discussing what to do about colored text. Colorblind accessibility is intertwined with that.

**Comment by onpon4** [comment]
> The best way forward that I can see is to put the text coloring scheme, or other markup scheme based on what Bobbens proposed, into a configuration of some sort. You'd define a markup per text class (such as "positive modifier", "negative modifier" etc), and markup all text with these classes as appropriate.... Who loses in this scenario? Nobody. It's not even that hard to code.

Great! Sounds like a perfectly fine system. Would you like to code it?

**Comment by onpon4** [comment]
I finally found what color it is and changed it in #1030. This is the result of the change:

![Screenshot at 2020-06-14 19-45-10](https://user-images.githubusercontent.com/2217995/84606949-09af1880-ae78-11ea-888e-78499b15bc92.png)

You'll notice that the text is more legible, but it changed the color used for showing what's selected on the left, too. *This* is why I've been arguing all this time that we need to get rid of this color usage. It's a mess. Now we either need to accept the puke-green selection color, create a new color variable for just the selection color, or leave text with such poor contrast that it causes eye strain. Probably I'll be fixing this particular color issue, but before I do that I just want to demonstrate how bad our color system is because this isn't the first time I've dealt with it. This needs to change.

If BTAxis wants to code this custom colorization thing he's talking about, that could solve it as long as every kind of element has its own color definition. I think it would be *much* easier, though, especially for testing and ensuring colorblind accessibility, to just strip out these text colorations and replace them with icons and bolded text (depending on the situation). I'll be working on the icons part of that on my "emoji" branch.

**Comment by bobbens** [comment]
Honestly, I find colours easier to understand at a glance than emojis. I agree on @BTAxis that we don't need to cater to the lowest common denominator, but I also agree with @onpon4 in that the current colour stuff is a bit of a mess. That said, we don't have to make it unnecessarily hard for the colourblind either. What I would suggest would be:
1. Improve the toolkit using material design guidelines ( #1031 )
2. Reduce number of colours used over all with focus on contrast. Colours should be named by functionality and not real colour to be easier to adjust. Probably should also have two (plus one for colourblind maybe) versions depending on whether background is "dark" or "light"
3. Add alternative that uses bold/italic typeface + emoji instead (optional in configuration file, proposed above by @onpon4 )
4. Add markdown support to be able to incorporate tooltips ( #1029 ) which could solve some ambiguous cases

With that said, I'll leave this issue up a bit more, but since it is a) solved by #1030 and b) derailed into another discussion, I will close it in a few days most likely.

**Comment by onpon4** [comment]
That sounds good to me.

**Comment by Wuzzy2** [comment]
The green text is now readable!

Issue is fixed.

You should post a new issue for the other talk … :P

**Comment by PhoenixRiver** [comment]
Apparently I was late to this but underline isnot usable with certain
"alphabets", neither is italic and bold is only slightly more general
but again not usable in some languages...

I put this here as there is no indication I could find about where
this discussion went...

River
