### ISSUE TITLE
[Proposal] Material Design Toolkit (UI)

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1031]
Give that the Naev toolkit was designed like 15 years ago using gradients because I thought they were "cool" and seeing the noise about the color interface and usability. I would like to propose changing the interface design to a [material design](https://material.io/design). I am not a graphics designer, but I think it would improve usability quite a bit. First steps would be getting rid of gradients and making it all much smoother.

**Comment by ids1024** [comment]
I wonder if it would be hard to embed something like Qt (which seems to be the currently favored cross-platform toolkit), and overlay that on top of our OpenGL rendered space scenes.

**Comment by bobbens** [comment]
I always thought about that. Back in the day it wasn't really possible, but things have probably changed. One issue is that Qt is C++, so unless we make a library or find one to bind it to C, it is a no-go. GTK is C, so that would be possibly the more rational choice. The question is if we can embed GTK, as in render the GTK on a texture or whatever and just render that, or if we have to spin it around and have Naev render to some sort of window buffer that GTK uses. This will probably be heavily tied to how the input is handled.

That said, given the amount of custom widgets and stuff we use, I'm not sure to what point it would be beneficial and less work than just improving the current framework. My cursory research on the topic indicates that we might be better off just trying to improve the current toolkit.

**Comment by ids1024** [comment]
> GTK is C, so that would be possibly the more rational choice.

I think GTK is worse at being cross-platform, while QT is basically the standard for cross-platform GUI development (well, that or Electron).

Currently, a major problem with the toolkit in Naev (and perhaps more difficult than updating the style) is that it's pretty hard to make changes. If someone wants to experiment with a different layout for a screen, that's a pretty significant programming task.

I think it would be better if UI design was done in Lua instead of C. Perhaps if we used Qt, we could have some C++ code that wraps a Lua API around Qt, providing the abstractions we want? That is, if that would be simpler than updating or rewriting the current toolkit code. The same idea applies with other options.

(Everywhere we're compiling should have a C++ compiler as easily available as the C one, and we already have a bit of [Objective C glue code for Mac](https://github.com/naev/naev/blob/master/src/glue_macos.m).)

But yeah, that's probably not a particularly minor undertaking.

**Comment by bobbens** [comment]
One of the reasons I'm not sure to what extend it can be useful, is that while some windows are fairly straight forward to "port" (e.g., only text / images / buttons), the entire shop interface widgets (which are one of the major issues) will still require lots of custom code, likely ending up reimplementing the entire thing again, just in QT, making it even more complicated.

Moving the interface stuff to Lua is also possible, but I'm worried we'll end up with a mess of callbacks back and forth having all the code in two places thus being even harder to understand. 

I have used GTK back in the day a bit (and QT I think), and my impression of both (and pretty much any toolkit) is that as long as you do really simple stuff, they are great and easy to use. However, the moment you start trying to do fancier custom things they just break down really really fast. In that sense, I think something like using html/css might actually be easier to use as a toolkit (probably biased by all the web development I do). Easiest solution would be to just incorporate webkit or whatever, have it render to a texture and bind the input stuff to it. Probably easier said than done.

Some references for using webkit in games are found [here](https://www.reddit.com/r/gamedev/comments/50j40h/htmlcss_gui_system_for_c_game_engine_openglvulkan/)

**Comment by agb32** [comment]
I'd avoid gtk/qt for this - if you'd have started with them 15 years ago, you'd have had to have done at least one redesign since (e.g. porting gtk2 -> gtk3), which of course takes effort... 
A redesign of the shading, and few tweaks might be sufficient?

**Comment by bobbens** [comment]
Partially solved in #1193 . Not sure if it still needs significant improvement.

**Comment by onpon4** [comment]
I'm happy with it myself.

🕵️

**Comment by bobbens** [comment]
Closing as it doesn't really seem necessary at the moment.
