### ISSUE TITLE
Minor graphical issue with slider

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1038]
If you click on a slider (widget), a thin rectangle appears to mark it. This is OK.

But if you move the slider all the way to the left or right, the slider does not really neatly fit into the rectangle. This looks slightly odd.

090051c25a68fe7f0153f0e74f25558981030261

**Comment by Houkime** [comment]
The issue looks like this
![image](https://user-images.githubusercontent.com/32805122/96364777-cfa69980-112b-11eb-8d2a-ec44e1fa214f.png)
![image](https://user-images.githubusercontent.com/32805122/96364795-e6e58700-112b-11eb-8b71-3561f4d28d7f.png)

Note that it is not symmetrical. It looks like the "pivot point" of slider knob is offset to the left.

So probably the fix should be two-part.

Center the knob so that it can hit the edges symmetrically.
enlarge focus indicator (a thin rectangle) x-wise a bit or shrink the sliding area.
Good measure might be to have the same rectangle-knob spacing from knob's edge at maximum-left position as it is now from slider track on the right to the rectangle (x1) 

![image](https://user-images.githubusercontent.com/32805122/96365121-e1893c00-112d-11eb-8485-0ad4541e25b8.png)

Note that on this picture y-wise frame vs slider is also not symmetrical and text is colliding with the focus frame.

**Comment by Houkime** [comment]
In src/toolkit.c in window_render() (https://github.com/naev/naev/blob/master/src/toolkit.c#L1315)  
One can  see that focus rendering is hardcoded to widget's w and h.

```
if (w->focus != -1) {
      wgt = toolkit_getFocus( w );
      if ((wgt == NULL) || wgt_isFlag(wgt, WGT_FLAG_KILL))
         return;
      x  += wgt->x;
      y  += wgt->y;
      wid = wgt->w;
      hei = wgt->h;
      toolkit_drawOutline( x, y, wid, hei, 3, &cBlack, NULL );
```
So, since there are no per-widget settings, all changes should concentrate inside widget code.
The fader widget code is in src/tk/widget/fader.c
The rendering code is fad_render() (https://github.com/naev/naev/blob/master/src/tk/widget/fader.c#L87)

```
static void fad_render( Widget* fad, double bx, double by )
{
   double pos;
   double w,h;
   double tx,ty, tw,th;
   double kx,ky, kw,kh;

   /* Some values. */
   pos = (fad->dat.fad.value-fad->dat.fad.min) / (fad->dat.fad.max-fad->dat.fad.min);
   w = fad->w;
   h = fad->h;

   /* Track. */
   tx = bx + fad->x + (h > w ? (w - 5.) / 2 : 0);
   ty = by + fad->y + (h < w ? (h - 5.) / 2 : 0);
   tw = (h < w ? w : 5.);
   th = (h > w ? h : 5.);
   toolkit_drawRect(tx, ty, tw , th, toolkit_colLight, NULL);

   /* Knob. */
   kx = bx + fad->x + (h < w ? w * pos - 5. : 0);
   ky = by + fad->y + (h > w ? h * pos - 5. : 0);
   kw = (h < w ? 15. : w);
   kh = (h > w ? 15. : h);

   /* Draw. */
   toolkit_drawRect(kx, ky, kw, kh, toolkit_colLight, NULL);
   toolkit_drawOutline(kx + 1, ky, kw - 1, kh - 1, 1., toolkit_colDark, NULL);
}

One needs to change it with respect to w and h so that the knob never crosses the focus outline (which is at the borders of w and h).
Also one probably needs to change mouse handling etc accordingly since knob won't be at the same place anymore.

**Comment by onpon4** [comment]
I actually attempted to fix this some time ago but found that the way the widget uses magic numbers was too convoluted for me to figure out what to do with it. Everything I tried to do just ended up making it worse. It's something that really needs cleanup.

🕵️

**Comment by Houkime** [comment]
I think i have managed to make it somewhat better, at least from behavior point of view (codestyle still needs work).
