### ISSUE TITLE
Lore: Inconsistent use of time

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1039]
In some of the lore (news text, civilian text), there is talk of “weeks“, “months”, “years” and “decades” in a non-planetary context. I think this does not fit into the Naev universe, which has its own timing system (SCU, “cycles“, etc.). I suggest to rewrite the texts.

Offending strings:

* Technicians at the Omega Station recently returned from a new effort to understand the Sol Incident. They expect the first data to arrive in two months' time.
* In an interview with Bleeding Edge anchor McKenzie Kruft, a researcher at Eureka labs says he has produced a tabletop atomic reaction. He hopes to publish his results in a science journal later this year.
* The Empire agreed terms with shipbuilder Nexus for a new generation of military craft. The deal extends the partnership with the government for another decade.
* For decades used only as menial labourers, now SuperChimps are being widely adopted as domestic companions. Enhanced primates make an affectionate, intelligent pet, or low-cost servant.
* You have attached your docking clamp to the derelict's airlock, but the door refuses to open. A few diagnostics reveal that the other side isn't pressurized. The derelict must have suffered hull breaches over the years. It doesn't seem like there's much you can do here.
* Only two years after the mysterious disappearance of its owner, the galaxy's only deep space bar shut down the generators and cycled the airlock one last time.

Note that there are also other strings which already refer to type via “cycles”.

**Comment by onpon4** [comment]
I've fixed these in #1057 (and actually a lot of cases you didn't notice as well).

I didn't change the "over the years" bit since that's an expression and not a reference to actual years. (Note: years still exist in the Naev universe, they're just planet-specific and therefore not typically used as an intergalactic time unit. In fact there are some cases, notably a couple references to First Growth times, where "years" makes more sense than "cycles", and some cases where the real-world time units are the only acceptable choice, like a discussion of a calendar for a particular planet.)

**Comment by Wuzzy2** [comment]
Yeah, I agree the concept of years needs not to be banned entirely. Context matters obviously.
