### ISSUE TITLE
Turbo fire in main menu screen

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1042]
Sometimes, ships spawn in the main menu screen and sometimes they shoot each other. When they due, you can hear them blast very loudly. The fire frequency seems to be very very fast, much faster than usual. I once saw a Dvaered Goddard that fired rockets at a VERY high speed (ca. hundreds per second). This is ridiculous and can also get VERY loud when this happens.

090051c25a68fe7f0153f0e74f25558981030261

**Comment by onpon4** [comment]
I've never witnessed this personally and the firing rate seems normal on my end. Did you see an indicator in the top-left that says 2.0x or something similar? (That's controlled by the tilde/grave key by default.)

Alternatively it's possible you just found a ship with a rapid firing rate. You mentioned a goddard; Dvaered Goddards have a lot of ship slots. In the most extreme case it could be equipped with 7 Mace launchers, which would fire at a total rate of 19.6 shots per second (this would likely seem quite fast and loud since Mace rockets are some of the loudest weapons in the game).

**Comment by bobbens** [comment]
There is a limit on the number of voices that can be played simultaneously. It should be rare enough if it does happen that it shouldn't be a major issue. Closing this issue.
