### ISSUE TITLE
[Proposal] Ship's Log

### ISSUE THREAD

**Issue by ids1024** [naev/naev#1053]
It seems to be relatively common in RPG and adventure games to have some kind of "journal" recording important events and information. It could make sense to have something like this in Naev. Calling it a "Ship's Log" seems like it would fit well.

I'm not sure what the best interface would be. But while a chronological log of information could be part of it, it would be nice if there's a quick way to be reminded that the player knows of an odd baron in the remote Ingot system. And things like that, which the player might forget.

**Comment by bobbens** [comment]
Could be something as simple as just active/cleared quests by time with some small comments. Might be a way to try to generate the automatically from OSD, but I guess manual would be better.

**Comment by onpon4** [comment]
Probably the most difficult thing to do would be to prevent useful info from getting lost in clutter about random cargo missions or some such thing, so maybe it would be best, if we're going to do something like this, to have missions define when something should be logged? That way you'll only get something logged when it's important (assuming mission authors use the feature correctly).

**Comment by bobbens** [comment]
I would argue for adding a new API for this. Copying other games (Baldur's gate et al. comes to mind), would mean that the following would probably be decent:

1. Allow missions to create a log
2. Allow missions to add information to the log (it is time stamped, maybe location stamped)
3. Allow missions to finalize the log (either complete or aborted)

One thing that has to be taken into account is that missions can be failed and restarted. Therefore I would propose having the log be tied to the ID of the mission name, so that if you create a log and one already exists with the same ID, it gets recreated and the old one is erased.

I would also argue that it is not probably necessary to be able to edit the log entries. Just have it be additive.

Finally, they should be saved in the save game.

**Comment by ids1024** [comment]
> I would argue for adding a new API for this.

Definitely. That's the only way it will really provide the most useful kind of information.

> I would also argue that it is not probably necessary to be able to edit the log entries. Just have it be additive.

Ideally, we would be able to have typo fixes and such apply to earlier log entries, and switching language would switch the language of the entries. That may be more effort than its worth.

**Comment by agb32** [comment]
So, something like (in C, with lua hooks):
int shiplog_create(char *logname,int overwrite); /* returns a log ID, for log with specified title.  If overwrite set, and title already exists, the log will be cleared and previous log ID returned, otherwise a new log ID will be created. */
shiplog_append(int logid,char *msg);/* Add a message to the log */
shiplog_close(int logid); /* Actually, this probably isn't necessary.*/
The shiplog functions would capture current time and system/planet (if landed) and record these.
Log data to be saved in config file.

Some sort of log viewer, which can either display all log information in chronological order (including all log IDs), or display information from a specified log ID if selected from a list.

Might be fun to log (with log ID == 0) whenever a player enters a system or lands at an asset, so that they can track where they've been over time - we could play this out on the map perhaps.  But maybe not, as that would grow the save file significantly...

Should all missions automatically create a log?  I guess not, as its not interesting for shipping etc.  Perhaps only those missions met in the bar?

**Comment by ids1024** [comment]
> Might be fun to log (with log ID == 0) whenever a player enters a system or lands at an asset, so that they can track where they've been over time - we could play this out on the map perhaps. But maybe not, as that would grow the save file significantly...

I'm not sure exactly how much that will grow the save files, but it would probably be fairly substantial, for something users would probably mostly want to filter out. So although I kind of like the idea of that being available... probably not.

> Should all missions automatically create a log? I guess not, as its not interesting for shipping etc. Perhaps only those missions met in the bar?

I think it's mainly unique missions we would want this for. Otherwise it's kind of the same problem: a lot of information users would typically want to filter out.

**Comment by PhoenixRiver** [comment]
There could be two logs, one a journey log and one an event log;

> I'm not sure exactly how much that will grow the save files, but it would
> probably be fairly substantial, for something users would probably mostly
> want to filter out. So although I kind of like the idea of that being
> available... probably not.

If this is shown on the map you would only need a list of systems
visited (down to the asset is probably not so helpful) and the ability
to chose how many visits to show (there is probably little benefit to
doing this by date and so that infromation wouldn't need to be saved
either). This would reduce the saved information to something pretty
minimal and also keep it seperate from the events/missions the playe
had done (though it would show the locations the playe had to visit to
do these - possibly a link to the event log could be placed if an
event was logged in a system? That would mean storing a tuple though
and most of the time the second would be empty).

>> Should all missions automatically create a log? I guess not, as its not
>> interesting for shipping etc. Perhaps only those missions met in the bar?
>
> I think it's mainly unique missions we would want this for. Otherwise it's
> kind of the same problem: a lot of information users would typically want to
> filter out.

Both could be stored but with a filter for types of mission, faction
missions vs cargo missions vs citizen missions vs combat missions - it
requires missions to include a type but makes sorting them much
easier.
Also if the mission log text is only ever stored in the mission.xml
then the text/translation can be changed without messing with the log.
That would also mean the only things needing stored are the date of
the log entry, asset/system at log entry and the mission ID (maybe
also the mission type for quicker sorting/ filtering?)

These might become quite a lot over the years of a single pilot but
the benefits of the log could potentially offset this to a high
degree... NPCs could use the log information to refer to past events
the player knows about as well as knowing which parts of the galaxy
the player has explored (for proposing missions in only areas the
player was familiar with / making the player have a chance to explore
new areas with some guarentee of profit :)

Just a couple of thoughts,

River

**Comment by agb32** [comment]
Implemented in #1153.

**Comment by agb32** [comment]
I've added a tab to the info screen, which displays current logs. 
e.g.

![image](https://user-images.githubusercontent.com/9550289/87431514-a92e0b00-c5de-11ea-8827-dba7b6d606be.png)

![image](https://user-images.githubusercontent.com/9550289/87431661-e09cb780-c5de-11ea-9db9-a2f5e00d8dbf.png)

I've implemented the hooks in the cargo, cargo_rush and pirate mission scripts as an example to be followed - so please feel free to add hooks in other missions as appropriate.

Ship log data is saved in the savefile.

**Comment by onpon4** [comment]
Does that log system support long logs (e.g. lines of dialog)? If it doesn't then it's probably not a complete implementation of this proposal albeit a step in the right direction (with some caveats I mentioned on the PR itself).

**Comment by agb32** [comment]
I guess we could either add a horizontal scroll to the widget (might cause problems elsewhere in the game?), or alternatively allow a click on the log line to pop up a new dialogue window, or something like that containing the full text.  But at the moment, long logs will disappear off the side... so if we need them, something will need to be done.

**Comment by onpon4** [comment]
> I guess we could either add a horizontal scroll to the widget (might cause problems elsewhere in the game?), or alternatively allow a click on the log line to pop up a new dialogue window, or something like that containing the full text.

Yeah, a pop-up dialog would work.

**Comment by agb32** [comment]
pop-up dialog implemented...

**Comment by onpon4** [comment]
Cool!

**Comment by onpon4** [comment]
Implemented by #1153 and #1180.
