### ISSUE TITLE
Broken news reel in translated game

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1077]
If you play in a translated version of the game, the news reel goes bonkers.

In the News reel, the News caption text is duplicated in English and German. Also, several news entries themselves appear in English AND German. Some only in one language. It's very chaotic and this doesn't happen if you disable translation.

I haven't found a logic behind this oddidy, but something about the newsreel translation system is definitely very broken. This needs testing.

It's hard to explain, see for yourselves. I tested in Sirius space on planet Pauldur in Nixon system.

0.8.0-beta1

**Comment by onpon4** [comment]
That's because the news event looks for previously published articles and unpublishes them if they match the name of an article that's being published. The code unfortunately doesn't have any way of dealing with that, but it'll only show up if you played under one language and then switched to another language.

(This applies to the news caption too because under the hood that's actually an "article".)

I'm not sure if there's a viable fix for this since the news feed is something that's built on, not just generated. Previously submitted articles stay up until a certain expiration time. And the script only has access to the current language, not other languages that may have been used in other sessions.

**Comment by Wuzzy2** [comment]
Does this mean the savegames save the literal text of the news, and not just a list of something like “news ID” or something like that?

If yes, this is bad design even if we ignore language. If you ever want to change the text of an existing news, it won't apply to old savegames.

**Comment by onpon4** [comment]
> Does this mean the savegames save the literal text of the news, and not just a list of something like “news ID” or something like that?

Yes, that's how it works. There's no ID system for news articles (if there were the text would have to be contained in an XML file somewhere and there would be little flexibility for posting news articles; the economy news articles would be impossible for instance).

> If you ever want to change the text of an existing news, it won't apply to old savegames.

That's not quite true actually, the event only compares titles. Any article with an identical title will be removed and replaced with the new one. The duplication problem only happens when two articles are a version of the same article but have different titles (as would happen if you were to switch languages in the middle of a save, for instance).

**Comment by bobbens** [comment]
This is non-trivial to handle in a super nice way. What could be done is to save the language and remove (or hide) if the game is set in another language.

**Comment by onpon4** [comment]
I just made some changes to t he news event in #1178. It doesn't do everything, but it uses tags instead of article titles to prevent duplicate articles. This means that articles in other languages will remain, but you won't have, say, both the German version and the English version of the same article. So the worst of what you experienced is solved.

The idea of making it re-translate or ignore previously posted news articles is a lot harder and probably not worth it. That said, one other change to the news event is it makes proper use of article expiration, so old articles are removed after around 10 periods.

**Comment by bobbens** [comment]
Should be solved in #1178 (for new games), although changing language in the middle will be a bit weird.
