### ISSUE TITLE
Game is very very fast with big ships

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1078]
For some reason, when I have a big ship like the Kestrel the game becomes very fast but no speedup multilpier is displayed. It's so fast that it's pretty hard to react to enemy actions, to battle, and so on. Weird.

0.8.0-beta1

**Comment by onpon4** [comment]
That's intentional. It's the time dilation effect of ships, which you can see in the shipyard. Big ships have time pass faster, small ships have it pass slower. (In fact the Hyena actually makes time run at 75% speed.)

The reason for this is because big ships' slow speed can be very tedious at normal time passage rate, and it's justified in-universe as the big ships being harder to control than smaller ships. (So the being more difficult to react effect is also intentional; it's an added benefit of flying smaller ships.)

The Kestrel actually doesn't have the highest time dilation, carriers like the Peacemaker do. Kestrels have a time compression rate of 250%. (You can look at and compare time dilation rates in the shipyard, as mentioned.

Anyway, I would recommend the Hyena if you need more reaction time, or possibly a Corvette class ship if you want something bigger (which only has 150% time dilation).

**Comment by onpon4** [comment]
I've adjusted the Kestrel's time dilation a bit in #1069. Made it just 225% (instead of 250% like other Cruisers) since the Kestrel is generally designed to be faster than other Cruisers. I think this helps make it feel more natural.

**Comment by Wuzzy2** [comment]
Ugh. Then this is just a horrible mechanic IMO.

I mean, speeding up THE ENTIRE GAME by 250% or even more, at all times, even if you're not moving, just because your ship is big, is absurd.
This makes direct combat basically impossible. You could maybe still fight 1-2 enemies, but taking out large numbers of enemies will be very hard, even if you had more than enough firepower to defeat them all, simply because your reaction time is not fast enough. In other words, the benefit of having a large warship is nullified. Not good.
Also note that 250% is a very extreme number. Heck, even 110% would probably be noticable.
That it also goes the other way is … weird.
If you have like 5 enemies, how are you supposed to concentrate even on a single target at this game speed? And then you told me that 250% was not even the end of the line … Oh boy.

Seriously, where is the fun in that? Combat is already hectic enough at 100% speed, thank you very much. I mean, the whole concept of speeding up LITERALLY THE ENTIRE GAME depending on the size of your ship ... it just doesn't make any sense to me.

OK, so the rationale is that flying mega ships is tedious. OK, this is a valid complaint, and I agree. But I think the solution is very very misguided.

I think the central problem with this concept is that it's forced. It's not possible to get rid of the speedup except flying a smaller ship. This sucks.

How about making it activatable with a keypress?

Currently, there's a keybind to toggle 2× speedup. Maybe a similar key can be added for “ship speedup”?

As for tediousness, it might also make sense to explore other, less extreme solutions on how to deal with large warships.

Finally, “time dilation” should not be used as term. Because it applies at all times, even if you don't move. The term would maybe make more sense in hyperspace but it has nothing to do with that. Better pick a different “sciency” term.

**Comment by onpon4** [comment]
> This makes direct combat basically impossible.

I somehow manage to do it without issue. I've been piloting a Pacifier most of this game, having a blast with the Kestrel, and rarely resort to my smaller ships anymore.

> Also note that 250% is a very extreme number. Heck, even 110% would probably be noticable.

250% means 250% of the original speed, i.e. an increase of 150%. 110% would just be a 10% increase and not make much of a difference at all.

> That it also goes the other way is … weird.

Well, I thought it was a cool mechanic to be able to control a tiny ship with high precision, rather than struggling with the weak thing trying to compensate with fast reflexes. With the Hyena you're zipping in and out of situations incredibly fast without having to be a superhero.

> If you have like 5 enemies, how are you supposed to concentrate even on a single target at this game speed? And then you told me that 250% was not even the end of the line … Oh boy.

You're not. Typical combat with large ships involves bombarding them with auto-aiming turrets, *or* bombarding them from afar with missiles (or sometimes both). You don't need to concentrate on 5 enemies at a time, in fact you shouldn't. Focus on one enemy at a time (preferably the small one dealing the most damage) and then move on to the next one. A large ship can take the heat; that's the point of it.

In fact in Naev combat you should never center your attention on more than one or two ships at a time with any ship. But it's only with small ships that you have to worry about dodging enemy fire, and so for them you need time to move slower.

> Seriously, where is the fun in that? Combat is already hectic enough at 100% speed, thank you very much. I mean, the whole concept of speeding up LITERALLY THE ENTIRE GAME depending on the size of your ship ... it just doesn't make any sense to me.

I don't think of Naev as an action game. The fun is in figuring out how to manipulate the AI into doing what you need to do to win, and also to figure out the best kind of ship for a particular situatiton.

If a particular ship isn't working for you in a particular situation, you probably need to change your ship.

> I think the central problem with this concept is that it's forced. It's not possible to get rid of the speedup except flying a smaller ship. This sucks.

Well, like I said, this is one of the points.

Think of an elephant and a mosquito. Time passes a lot faster from the elephant's perspective than from the mosquitoe's perspective. But the elephant is much much stronger than the mosquito and not likely to be substantially harmed by what the mosquito does. Meanwhile, any sudden movement can squish the mosquito in an instant.

You have a choice here: you can be the elephant (carrier class), or you can be the mosquito (Hyena), or you can be somewhere in between.

All choices are valid. And the fast passage of time doesn't have to be a hindrance if you pilot a large ship that you designed properly.

If you designed a large ship to dodge and react to bolts, you're using the large ship wrong. You need a smaller ship for that, a Corvette at the largest. If you want the larger ships, you need to change your perspective to one where you aren't concerned with the minor consequences of a Hyena zapping you with a peashooter.

But this won't work in all circumstances. If you're a pirate, for example, the Empire is far far too heavily armed for you to take them on directly. You need a small ship so you can slip away from their grasp.

All the time speed change is doing here is portraying this dynamic in another dimension. It's not wrecking your game. It's just highlighting the problems with your strategy.

> How about making it activatable with a keypress?

That would kind of defeat the purpose of the feature. Speed-up for the impatient is already achieved with the grave/tilde key by default. This feature is a gameplay mechanic.

> As for tediousness, it might also make sense to explore other, less extreme solutions on how to deal with large warships.

I don't think speeding up time so that they can be slow and brutish without being tedious to control is "extreme", at least not for Naev. Naev messes around with the passage of time all the time; it's a major aspect of its identity.

> Finally, “time dilation” should not be used as term. Because it applies at all times, even if you don't move. The term would maybe make more sense in hyperspace but it has nothing to do with that. Better pick a different “sciency” term.

We juggled around a few different possible terms. "Time Dilation" is what we decided on as a balance of sounding nice and being descriptive. Another idea that comes to mind for me is "Time Compression". I believe that was my favored term and others preferred "Time Dilation", but I'm not entirely sure; this was months or maybe even years ago (I forget when it was).

**Comment by ids1024** [comment]
> Speed-up for the impatient is already achieved with the grave/tilde key by default. 

That provides a fixed 2x speedup. What if we changed that to depend on the ship? Perhaps compute based on the maximum speed of the current ship, adjusted so any ship will move at the same (relatively fast) speed.

**Comment by onpon4** [comment]
We could, but that probably shouldn't be necessary. Honestly what I've always thought would be cool is to enable that key to speed up the game more than 2x for when you really want to make things go faster (maybe a 4x and 8x option). But auto-calculating an amount to speed up would be redundant already since slower ships usually have time going faster anyway.

**Comment by onpon4** [comment]
Could I get your thoughts on this as pertains to the current state of the game, @Wuzzy2? We were talking to one other person who had problems with the system about it and decided to implement a tutorial of sorts in #1104. This should prevent any confusion, and the reduction in time dilation for the Kestrel should make the Kestrel specifically (which is the ship you had problems with) easier to control.

Please let us know.

🕵️

**Comment by Wuzzy2** [comment]
The help text is a clear improvement. Although I still more or less disapprove of the mechanic as a whole. :P

**Comment by onpon4** [comment]
Alright. Well there aren't any plans to remove the mechanic as a whole, so I'm closing this for now. If you have any other specific thoughts for how to improve the system, or other specific complaints about the system, please let us know.

🕵️

**Comment by PhoenixRiver** [comment]
Okay, I hate to necropost but I really have to because I played with a large freighter for the first time - working my way up from nothing - and though it has four turrets (it's a Rhino... I was considering the Mule but decided I need the extra arour... I needn't have bothered) ... I get attacked by one pirate and it's fifty fifty if I can target them and kill them before I'm dead... it's a hundred percent I'm dead if it is more than one pirate... so armoued traders are not usable for anything normal traders are usable for??

I don't care if it takes an hour to get somewhere I want an option to turn off the time dilation... the game is hard enough going outside the Empire before having serious armourment (I can just about manage with a full sped up Gawain though I've died to a random pirate so many times in Devraed space it's stupid - it does not deserve to be the area next to the new person's Empire space... Sirius and Frontier space are both waaaay safer, if you've the speed).

I have to say I see the arguments but the degree of speed dilation is insane, traders are death traps and in which case my entire style of gameplay has been removed from the game... shame.

**Comment by PhoenixRiver** [comment]
Sorry:

Windows 10, Steam version 0.9.2, everything default with a resolution of 1920x1080 on fullscreen

(I mention the resolution because clicking the enemies at that resolution is not easy or fast even with the best reaction times and I'm not adjusting my mouse twitch speed for every application jsut for this game.)

**Comment by onpon4** [comment]
> I have to say I see the arguments but the degree of speed dilation is insane, traders are death traps and in which case my entire style of gameplay has been removed from the game... shame.

I have to say, myself being the one who implemented the Time Constant mechanic years ago and actually being neurodivergent, I find your crass description of the mechanic as "insane" to be very hurtful. It feels like a personal attack on me for being neurodivergent because my neurodivergence absolutely influenced me when I implemented that. It feels like you're saying that I did something horribly wrong because of my neurotype. *This* is why I tell people not to casually throw out ableist shit like this.

What's more is, since this issue was opened, the Time Constant values were actually lowered across the board. It's +25% now. That means that every 10 seconds, another 2.5 seconds are added. This isn't an amount of time that is going to cause pirates to kill you before you can even aim at them, unless the default speed of the game would also have that problem, in which case the complaint should be that the entire game is too fast and/or that Naev's slow speed option isn't accessible enough. Though given that you say you're having trouble clicking on things because of your resolution, it seems to me you should give the "R" key a try and consider adjusting zoom and/or scale factor as well.

Whatever the case, this accessibility issue you're facing has very little to do with the thing you're blaming it on, and maybe consider not resorting to ableist insults when you're frustrated with something, thanks.

🕵️

**Comment by PhoenixRiver** [comment]
You are indeed correct to point out that this attack on time dilation only was unfair, especially given that there are, I'm sure, other solutions that in combination could help me with the problems I'm experiencing and therefore I would like to retract my statements above and apologise for the form and wording I chose as this issue was simply the straw the broke the camels back for me. I intend to submit a more thoughtout and thorough ticket to explain my experiences with starting this game afresh after a number of years of enforced abscence.

I am sorry if I insulted or hurt you personally, I had no intention to do this. I was not aware that this entire system was created by one person (this is a cooperative endevour after all, is it not?) nor who that person was or what impairments they might have... whether similar or different to my own.
