### ISSUE TITLE
NPC chat in bar

### ISSUE THREAD

**Issue by agb32** [naev/naev#1081]
Might be good to have an option not to show a certain conversation again?
e.g. the recommendation to buy a map or two, the one about Captain T Practice, Soromid Organic ships, the Emperor's ship, etc.

**Comment by onpon4** [comment]
It could be possible to modify the NPC script to only show each message once. It would be a bit finnicky though since var.push doesn't support tables.

**Comment by agb32** [comment]
No - I think it would need to be more than once - otherwise new players would miss lots of tips at the start.

**Comment by Wuzzy2** [comment]
Yes, displaying hints once for the entire game and then it's gone forever is a bad idea.

I also think it's perfectly fine if the NPC repeats having given you a jump point. Maybe you want to reread what they have said …

The jump point dialog should only be avoided if you have already have bought the local map before talking to the person for the first time.

Otherwise, I think NPC dialogs are OK as-is. Don't touch them. Also, it's pretty standard practice in adventure games to repeat a dialog word by word if you talk to a simple NPC again. This is by design so you can reread the text. This should not be changed. Some adventure games paraphrase or summarize if you talk to same NPC a 2nd time (especially when it was a long text), but it's not really important for Naev.

**Comment by onpon4** [comment]
I'm actually not in favor of the idea either, but that would be the most elegant way to prevent previous messages from being shown. Personally I don't see a problem with reading a message multiple times, it's perfectly normal for NPCs.

**Comment by agb32** [comment]
Personally, I read messages each time I land - so it does get a bit of a click-fest - though its only Arrow Return Return, so not too bad.  Some of them annoy me though, having read them so many times with unimportant info...
Having an incentive to read them would be good (I do it on the off chance that a jump point will be provided! - or something else useful)

**Comment by onpon4** [comment]
Well you don't have to talk to every NPC you ever see. At some point you stop because you're no longer interested in what they have to say. At least, that's what you're supposed to do.

**Comment by 2ndBillingCycle** [comment]
What if the NPCs were sorted, with new messages to the top right of the bar?

That way, when the player receives a message they recognize, they know all messages right and downward are also repeats.

I'm not sure how this would be implemented, though.

**Comment by onpon4** [comment]
It's a thought, but Naev doesn't have a mechanism to track what NPC dialogs have been picked. It just picks them at random (and the event is restarted each time you land so it's not possible to have persistent tables; tables can't be used in `var.push()`).

If we did have some way to store tables it would theoretically be possible to store a table of previously shown strings, check against that table, and then pre-generate a list of NPC dialogs, sorting them into a table, and then assigning those to the NPCs. It would complicate the NPC event code a bit though and it would start to bloat up the save file (there are hundreds of NPC strings I think and unlike say news articles this table would be permanent).

On a side note, just want to mention that the reason I say strings instead of something like indexes is because indexes are unreliable (removing a string would cause all indexes after that to be wrong) and there's a fairly large number of tables containing the randomly selected strings so having to store data about each of them separately would complicate things.

In truth I don't think this would be particularly worthwhile. I wouldn't particularly object if someone wanted to do it though, other than a slight and possibly unfounded worry that adding support for writing tables with var.push could be "opening Pandora's box" so to speak.

**Comment by agb32** [comment]
A string search for the current session might be a good option - so as not to clutter up the save file.
Could also turn the outline of the npc a different colour once it has been seen...

**Comment by onpon4** [comment]
If it's only lasting for the current session it would hardly seem a worthwhile addition to me.

Also I'm going to give my resounding disapproval to "turn the outline a different color", both because colorblind accessibility and because we shouldn't be telling the player ahead of time what NPCs to talk to, it breaks immersion (the very thing NPCs are there for).

**Comment by bobbens** [comment]
NPCs have been reworked completely. They will try to not repeat messages in the same playing session, however, that will not be saved and is reset when you restart naev (not when you load a game though!). Thanks for the report!
