### ISSUE TITLE
Incomplete translation

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1084]
Although I managed to translate German to 100%, there are a lot of things that remains untranslatable:

- Some buttons and windows
- Outfit names and descriptions
- Ship names and descriptions
- Various NPC texts
- Some stats
- Credits
- Other texts

My guess is that the POT file was not updated, but I also guess that some strings might not have been marked for translation in the first place.

**Comment by onpon4** [comment]
> My guess is that the POT file was not updated

Yes, that's the only reason some strings aren't translatable. I don't think I've seen an actually untranslatable string in quite some time.

Incidentally, like I've said before, the POT also has a lot of old entries that are no longer relevant.

**Comment by bobbens** [comment]
Updated POT files. This can be done manually with `make -C po update-po`, and if files have been added/changed make sure to run `./extras/update-po.sh` first.

**Comment by Wuzzy2** [comment]
But what about:

> * Outfit names and descriptions
> * Ship names and descriptions

**Comment by bobbens** [comment]
That's a good point. We have to set up gettext for xml, which is a bit tricky as per https://www.gnu.org/software/gettext/manual/html_node/Preparing-ITS-Rules.html

**Comment by onpon4** [comment]
Outfit and ship names can't be translated as it stands because outfit names are identifiers. Change the outfit name and the game won't be able to find it anymore. The same goes for faction names, system names, etc. Pretty much any name is an identifier.

Descriptions would be possible to translate, though. The difficulty would be getting the string from the XML into the POT file without manual effort.

**Comment by bobbens** [comment]
I don't see why they can't be translated? If we make the `outfit.get(...)` API and all the other game functions use the translated version, it should be fine. Only issues I can think of is:
1. We need to check to make sure IDs are unique within the translation (should happen automatically if done when loading)
2. We need to watch out for cases of `outfit:name() == "Foo"` in the Lua code, as it will be comparing untranslated vs translated.

**Comment by onpon4** [comment]
Well that's the thing, we aren't set up for that right now. Doesn't mean it's impossible but we'll need some major refactoring first.

**Comment by bobbens** [comment]
I really don't see the problem? Just slap `_(...)` around all uses of outfit names in the code (including the loading xml part, and the `nlua_outfit.c` outfit.get(...)). It should just naturally use the translated version as the ID. Not sure if we might run into unicode problems (in which we just have to change function names), but it should be straight forward. The only really problematic issue I can think of is what I mentioned above, i.e., using `outfit:name() == "Foo"` in the Lua code, since it doesn't use the translated version. Those will have to be identified and changed to `outfit:name() == _("Foo")` and it should work. Same can be done with ships and whatever.

**Comment by onpon4** [comment]
Yes, I'm just saying that's pretty much all the code that has to change in some way. And it's not just those cases, any case of any part of the code referencing a faction, outtfit, planet, what have you would have to be edited, so pretty much every unique mission and prettty much every event that refers to a specific system. (Unless you have the C code automatically apply gettext to things like `faction.get()` and `outfit.get()`, which could work, though that could create code breakages that are difficult to work around if someone expects e.g. `faction.get(faction.get("Collective"):name())` to work (since you can't reverse a gettext translation, only apply it).

Of course if you take a literal approach to this and say that *only* outfits and ships are important for name translation then it's not very much, but I would think that we would also want to translate faction names, planet names, system names, for transliteration support if nothing else. When you combine all of these together there's probably hundreds of lines of Lua code that need to be adjusted.

It's also important to note that with translated names it would be very possible to get issues not unlike what we currently have with news articles, except breaking missions that are in progress when switching languages, or worse, removing all of your outfits and ships because it doesn't recognize any of the outfit names in the save file. This I think is probably something that should be handled with care (duplicate news articles are a nuisance but missions or the entire game breaking for no apparent reason could be bad). It probably would even be a good idea to have separate references to both the English names and the translated names within the Lua API with instructions to use the one that always return English (i.e. the identifier) when you're trying to save data or something.

**Comment by bobbens** [comment]
Actually savegames is probably the most important point. In order to not break everything, we would have to save in English. So I guess there is no way out other than to store the strings in English. So the following should work:
1. Keep most everything as is
2. Only translate when displaying
3. When using outfitter and stuff compare against translated name

This should be much easier to handle without breaking savegames. However, the Lua stuff still will have to be changed when displaying names to use `_(...)` which does involve a lot of editing.

**Comment by onpon4** [comment]
Yes, that sounds about right to me.

**Comment by Wuzzy2** [comment]
> Those will have to be identified and changed to outfit:name() == _("Foo") and it should work. Same can be done with ships and whatever.

Nooo! You do NOT want to use the translated string as identifier. This can lead to all sorts of unexpected weirdness.

> Only translate when displaying

Yes, and only translate for this. Never ever use the translated string internally (except in search/sorting).

**Comment by bobbens** [comment]
Should be solved in 8cb41b6637b503a289f9b2e3a95872df12981861 . There should be quite a few places that it doesn't properly show in the game yet. We'll fix them as we find them ;)
