### ISSUE TITLE
Dark Shadow mission repeats after failing or cancelling

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1093]
If the Dark Shadow mission starts, and you either fail it (by jumping out of the Suna system without picking up the person) or cancel it, it does not take long for you to get hailed again and the mission repeats again.

f502b70c4c20f517f0bec79de222c1897696ba92

**Comment by onpon4** [comment]
This is intended behavior. Naev normally allows you to keep trying missions over and over again without consequence until you win. Same goes for aborting, there is no penalty for doing so.

**Comment by bobbens** [comment]
This is gameplay design. Naev does not give penalties to fail missions, given that the game autosaves all the time and this just  makes it a hassle forcing the player to restart the game from previous save when doing screwing up. However, it could be tweaked so that it doesn't happen during a while, although I don't think it should be necessary.
