### ISSUE TITLE
Rename the default branch from "master" to something else

### ISSUE THREAD

**Issue by onpon4** [naev/naev#1168]
We discussed this on the Discord channel a bit, but I wanted to open an issue to collect discussion and help with organization. 🙂

So, as it turns out, the usual convention of naming Git primary branches "master" has its origins in master/slave terminology, as has come to light recently. Details on that origin can be found here:

https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

And as it happens, for this same reason GitHub has stated that they are now working to change the default primary branch name from "master" to a neutral term:

https://www.bbc.com/news/technology-53050955

So the proposal is simple: work toward transitioning Naev's use of the "master" branch as a primary branch to some other, neutral branch name (preferably whatever branch name becomes the new convention, most likely "main" from the looks of it right now). Renaming the primary branch can cause problems, so I propose a four-step transititon process:

1. Identify cases that need to be accounted for (where stuff needs to be updated to use the new branch).
2. Create a new branch with the desired name (a copy of the master branch) and update all cases to use said new branch rather than the master branch.
3. Make the new branch the primary branch.
4. Leave the master branch up for some time to make sure nothing continues to require it. When sure that it is no longer needed, simply delete the master branch.

So! First is step one: we need to identify what is going to be affected by a change in the default branch and prepare to update those things in step 2. Most obvious is pull requests; any outstanding pull requests at the time this is done will have to be edited so that they're merged into the new branch (or alternatively, they can be merged or closed beforehand). Anything else to consider?

🕷️

**Comment by bobbens** [comment]
I would wait until whatever github/git creates to be the new master is decided and adopt that. Would be probably the easiest and avoid complications down the line.

**Comment by onpon4** [comment]
Yeah, that would make sense. Probably it'll be "main", maybe it'll be something like "mainline"... whatever we change it to we should probably follow what GH defaults to.

We actually have to wait anyway because it's currently impossible for a GitHub Pages repo to use anything other than "master". That's probably one reason they haven't changed the default default branch yet.

🕵️

**Comment by Wuzzy2** [comment]
No, it doesn't make sense.

* The whole movement is 100% based on ideology. It's done not because it is technically needed, but mainly because of outside political pressure.
* Many repos scramble to find an “alternative name”, but there is no agreement yet. The result is predictable: An unholy mess of “alternative” names for the default branch. This is not dev-friendly and just creates a ton of confusion. I do NOT want to learn a new default branch name for every new repo. Also, there's not general agreement on how exactly repos should transition. It's complete chaos.
* The transition period will be quite annoying. Many devs will be confused to learn that the `master` branch suddenly stopped working.
* A lot of documentation (official and unofficial) about Git must be updated. A TON of documentation assumes that `master` is default. This little change will screw over a ton of documentation and tutorials. That's painful as hell!
* This is virtue-signalling of the highest order, and completely pointless. In most of the world, being against slavery is the default position. If the goal is to make a political statement against slavery, you're just preaching to the converted anyway. Do you really think FOSS advocates have slavery advocates in their rows? It doesn't make sense.
* The explanation that the `master` branch name comes from “master/slave”, in my opinion, pretty brittle. All it says that there is a slave repo in BitKeeper. That's basically it. There is no further “evidence” than that, and no attempt to further explain things is made. And even the e-mail only says that there MIGHT be a connection. Doing such a decision on so many “maybes” is not smart. The only way to find out for sure is to ask Linus himself …
* There's no meaning of the word “slave” in Git to my knowledge. Making the whole decision even more absurd to me.
* Even if the Git “master” was really as in “master/slave”, that still is no good reason to make this change. It's just a metaphor. It's almost as if the advocates for change believe that merely by saying the word “master”, you are kinda pro-slavery, or “normalize” is. Well, it doesn't work like this, it's just magical thinking.
* There are other “evil-sounding” words in the FOSS sphere that nobody cares about, like “SIGKILL” or “git” (British English for “idiot”) ...
* If we take this ideology to its logical conclusion, you'd have to ban “master/slave” terminology from BDSM as well. I'm pretty sure the BDSMers won't be happy about this.
* The whole FOSS movement turns themselves into a laughing stock for doing such bad decisions. To outsiders, this looks completely silly. I am a little worried the FOSS movement might even lose acceptance in the general public because of nonsense like this
* Just because GitHub, *which isn't even FOSS*, wants to abandon `master` doesn't mean it's a good idea to do so. Also, why should we take decisions from GitHub, which is owned by Microsoft (!), serious at all? Microsoft ain't your friend. Especially if Git itself doesn't also abandon `master`, this is VERY bad optics, it looks like that Microsoft can just rule by decree how FOSS operates (kinda). Yes, I'm a bit exaggerating here, but I'm just making a point here that we probably should not listen to MS. :P
* If you really would care about inclusivity, you wouldn't exclude FOSS zealots from conversations by using Discord, a *proprietary* chat software … :P

Overall, I think you and every other FOSS project that does this is shooting themselves in the foot.

If the name change would be “cheap”, i.e. create no migration pains, I probably wouldn't mind that much. I'd still be annoyed, but not enough to rant about it. But it does generate pains to change the name, as you admit yourself, that's why I'm telling you: Please stop.

**Comment by onpon4** [comment]
> No, it doesn't make sense.

The convention of naming the default branch "master" comes from "master/slave" terminology, as mentioned. If this turns away even *one* person of color, it is doing us *and society* a disservice.

By all means, don't focus on this issue if it's not important to you. But spending a small amount of time to remove the possibility of this causing harm to someone isn't "shooting ourselves in the foot". There is *no reason* to oppose renaming the default branch to something neutral that avoids any potentially negative connotations, unless your goal is to produce negative connotations. As Layla already mentioned, we're not going to do it in a way that's disruptive.

> This is not dev-friendly and just creates a ton of confusion.

This is untrue. Git is specifically designed to allow any branch to be the default. If you're depending on branches being named any particular thing, you're doing it wrong.

> If we take this ideology to its logical conclusion, you'd have to ban “master/slave” terminology from BDSM as well.

This isn't an "ideology" and no one's banning anything.

> There are other “evil-sounding” words in the FOSS sphere that nobody cares about, like “SIGKILL” or “git” (British English for “idiot”) ...

If you want to advocate changing those, go for it. We don't control POSIX standards or the name of Git, however, so this is the wrong place for that.

We *do* control what we call the primary Naev Git branch, though, and we want to change it to something else that doesn't have the "master/slave" connection.

> But it does generate pains to change the name, as you admit yourself, that's why I'm telling you: Please stop.

It doesn't "generate pains" if done right. I and Layla have already changed multiple repositories we are in charge of, no problem.

🕵️

**Comment by onpon4** [comment]
Just wanted to link to this here:

https://gitlab.com/gitlab-org/gitlab/-/issues/221164

It's GitLab's issue on picking a new name. Might be a useful reference going forward since apparently GH and GL are cooperating on this.

🕷️

**Comment by ids1024** [comment]
The default branch name for new GitHub repositories is now "main". They are still working on a recommended way to transition existing repos: https://github.com/github/renaming#later-this-year

**Comment by ids1024** [comment]
Github recently released the branch renaming support they've been planning for this (which is also useful for other cases where branches need to be renamed): https://github.com/github/renaming#renaming-existing-branches

**Comment by amylaar** [comment]
An alternative would be to re-contextualize the word to give it a different connotation.  If the documentation describes how to
make an apprentice branch, the master becomes one that gives instruction and guidance.
That also makes it more natural when a new branch becomes the primary branch.  A master can eventually be overtaken by the
former apprentice.  'main' implies that it stays paramount forever, and nothing else is of much importance.

**Comment by UncombedCoconut** [comment]
Nice try, @amylaar.
Obviously, "main" refers to the "Sea" in "Sea of Darkness".

**Comment by onpon4** [comment]
This is all set now! bobbens just renamed the primary branch to "main".

🕵️
