### ISSUE TITLE
Medium and large cargo pods

### ISSUE THREAD

**Issue by agb32** [naev/naev#1197]
There are xml files for medium and large cargo pods - but these aren't in the tech.xml, so can't be purchased anywhere.

Is this by intention, or a bug?  If a bug, I'll happily add.  Might be worth increasing the capacity of them too, in line with the cargo hulls, so e.g. 60T for medium and 150T for large (4x and 10x small - same as for the s&k cargo hull.

**Comment by onpon4** [comment]
It looks like they were added all the way back in 2015 (#534) and were never added to the XML. I don't think capacity should be increased beyond what they're currently set to if we use them; note that these are *additions*, so if you had 150T cargo capacity for large that would lead to a cargo capacity as high as 1000 tonnes even on a combat ship.

Anyway, since bobbens merged #534 without any objections I think it's fair to say that he thought it was a good idea, so yeah, we should make these cargo pods obtainable.

**Comment by onpon4** [comment]
There we go, done in 1ea891c.

🕷️
