### ISSUE TITLE
Unable to Install on Mac OS 10.15.6

### ISSUE THREAD

**Issue by michaelkramer** [naev/naev#1206]
After downloading the "naev-0.6.1-macosx.zip" attempted to add:

- "naev-0.7.0-ndata.zip" - did not load kept asking for missing `ndata`
- "ndata-0.8.0-beta1.zip" - opened but then crashed before the loading screen finished.

**Comment by onpon4** [comment]
You need to use the same ndata version as the version of Naev you've downloaded:

https://sourceforge.net/projects/naev/files/naev-0.6.1/ndata-0.6.1.zip/download

The MacOS build is older than the others because we don't have any Mac users working on Naev. If you'd like to help with that, do let us know.

See here for where to put the ndata:

https://github.com/naev/naev/wiki/FAQ#i-just-installed-the-game-and-tried-running-it-and-it-exits-right-away-or-says-insert-ndata

Let me know if the 0.6.1 ndata file works for you.

🕷️

**Comment by michaelkramer** [comment]
Thank you.  Please contact me about helping out.  I have ideas but have not worked with C or C++ before.  I mainly do stuff in Javascript or C#.

**Comment by onpon4** [comment]
Do you have a Discord account? We usually talk about the game here:

https://discord.gg/nd2M5BR

There's also #naev on irc.freenode.net if you use IRC, though not many people hang out there these days.

@bobbens is the one you'll want to talk to if you want to help with MacOS builds specifically, he heads the project and handles builds / releases AIUI. For everything else usually the way to contribute is fork the Git repo and then submit a pull request with your changes. Feel free to ask any questions you have on Discord or IRC.

Anyway, closing this issue since it seems the build's working fine (other than being outdated).

🕷️
