### ISSUE TITLE
Replace libintl with more flexible solution

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1216]
Currently libintl has two major flaws for us:
1. Can only load from laid out files; can't handle zips
2. Can only handle a single translation file and thus won't work with for example separate translation files for data and binary

Since the API is not too complex, I think it should be possible and easy to just read the `po` files, use a simple hash map to store the data, and reimplement libintl. In particular, the following libraries can be used:

* [libgettextpo](https://www.gnu.org/software/gettext/manual/gettext.html#libgettextpo): library for reading po files
* [uthash](https://github.com/troydhanson/uthash): hash table library
* [libintl-lite](https://github.com/j-jorge/libintl-lite): reference implementation in C++

**Comment by onpon4** [comment]
I still think we should fix #1 just by getting rid of the whole ndata thing. 😉

As for the second one I'm not sure what the problem is. We generate this stuff automatically on build-time now, right? So why should it matter if it's one file or two files? Seems like not the best reason to reinvent the wheel.

🕵️

**Comment by bobbens** [comment]
Dropping ndata and just using gettext seems like the way we are going so closing.
