### ISSUE TITLE
More info in Landing screen

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1285]
I suggest to add more info on the Landing screen of planets:

- Planet class (and maybe in brachets what this class means, e.g. “Class O (Oceanic)”)
- Population
- Maybe other little facts of interest?

**Comment by onpon4** [comment]
Do you have a use-case in mind for this info? Currently population and why planets are given the classes they are have no effect on the game (class has an effect on economy numbers but not in a way that a player could take advantage of knowing what the classes mean, since full economy info is shown by the system map anyway).

🕵️

**Comment by Wuzzy2** [comment]
Just for flavor, basically. Not really important.

**Comment by bobbens** [comment]
Could be done. I think population does affect the economy thing too.

**Comment by bobbens** [comment]
I have put the planet class, population, and faction on the main window, which I think are the main things the player could be interested in. Thanks!
