### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by bnk159hair** [naev/naev#1348]
Hello, we are Korean university students. This project is an area we are interested in, so we would like to contribute.
We want to contribute through the Korean translation of the project. Is it okay to contribute?

**Comment by onpon4** [comment]
Of course! We don't have good Unicode support at the moment so I think it won't display properly until we fix that, but yes, you can contribute a translation.

Just in case you're not sure how to start, what you'll want to do is fork the Naev repo, then clone your fork in one of a couple ways (GitHub has guides to try to help with this if you don't know how to). Then, on your machine: compile Naev, and if you used Meson commands in the compilation process, run `meson compile naev-pot` as well. This will generate the file "naev.pot" which will show up in the po directory (so e.g. if you have the Naev repo clone in "~/naev", you will have "~/naev/po/naev.pot"). You'll use naev.pot to create a file called I believe ko.po, either by using the `msginit` command if you have it (it's one of the gettext tools), or by copying naev.pot and manually editing it; translations go in `msgstr` fields, and they translate the corresponding English text in the `msgid` fields. You can see de.po and ja.po for examples (de.po is the better example since ja.po is very very incomplete). Then you'll need to commit ko.po to your fork (again, there's guides on GitHub if you don't know how), and you'll submit a pull request so we can review your changes and add them to ours.

You don't have to do the whole translation at once; blank `msgstr` fields will simply fall back to English, so there's no danger of breakage. So feel free to start with only a partial translation. (The German translation for example was translated in many separate steps because translating the entire game takes some time, and the Japanese translation has barely even been started. Both of these scenarios are perfectly acceptable, since one text string translation is better than zero. 😉)

Hope that helps!

🕵️

**Comment by bnk159hair** [comment]
Thank you for your answer. My team will participate in the translation.

**Comment by bnk159hair** [comment]
Can you email naev.pot file? I proceeded as you described, but both Ubuntu and Windows environments are not working properly.
My email address (bnk159hair@naver.com)

**Comment by bobbens** [comment]
I have attached the v0.8.0-beta.4 naev.pot here.
[naev.pot.zip](https://github.com/naev/naev/files/5621250/naev.pot.zip)

**Comment by bobbens** [comment]
I have merged and added Korean as a language as of PR #1495 . One important open issue is we need a Korean open source font that is similar to our current font (Cabin SemiBold). If anybody knows of any I would be grateful. It should be possible to add it to `dat/fonts/` and then translate he following to point to the new font:
```
msgid "fonts/Cabin-SemiBold.otf"
msgstr "
```
We probably would also need an open source Korean monospace font like SourceCodePro-Semibold too.

**Comment by bnk159hair** [comment]
We have found the font. 
How to give it to you. Through pull request?

**Comment by onpon4** [comment]
Yes, it goes under the dat/fonts directory. You should also note the license of the font via FONT_LICENSE.yaml (which is also in the dat/fonts directory).

🕵️

**Comment by onpon4** [comment]
#1499 resolved the font issue, so I'm going to close this as resolved now. Thanks for the contributions!

🕵️

**Comment by UncombedCoconut** [comment]
Quick note for anyone interested in Korean language support: it's now possible to contribute translations online using [Weblate](https://hosted.weblate.org/projects/naev/naev/).
Thanks again for your contributions.
