### ISSUE TITLE
Finish luajit submodule port to meson

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#1525]
Currently this submodule wraps make to build things.. and as the comments say, we should probably finish writing enough so meson can build luajit natively..

**Comment by UncombedCoconut** [comment]
I've tried to do just that and shared the code here: https://github.com/UncombedCoconut/naev/tree/luajit-out-of-tree
Unfortunately, it doesn't work. (The Windows cross-build, which is the first case I checked, will go through the loading screen and immediately crash.) I'm not expecting this to be easily debuggable.

Note that playing with it means reminding Meson to reprocess subproject definitions.
Since I'm role-playing the Dvaered engineer lately, I'll say: `rm -rf subprojects/luajit` so it regenerates per the updated `subprojects/packagefiles/luajit` recipes.

**Comment by UncombedCoconut** [comment]
My branch works now. Do we still use Autotools for ALL official builds?
If yes, I'm comfortable making this a PR.
If no, I want to wait until after 0.8, because it's scary to touch a JITted language runtime's CFLAGS, and that's what will happen if we do this (because Meson will honor the overall project's build settings).

**Comment by UncombedCoconut** [comment]
Actually, this branch works *for me* (gcc, clang, x86_64-w64-mingw32-gcc tested with Wine).
In the CI run ("Meson_Compile_Naev (ubuntu-20.04, bash, linux.ini)" which compiles with clang and links with lld) it won't build.
I couldn't reproduce the issue on my machine even with the same "meson setup" command. Can I get away with making this @ProjectSynchro's problem? ;)

**Comment by ProjectSynchro** [comment]
> My branch works now. Do we still use Autotools for ALL official builds?
> If yes, I'm comfortable making this a PR.
> If no, I want to wait until after 0.8, because it's scary to touch a JITted language runtime's CFLAGS, and that's what will happen if we do this (because Meson will honor the overall project's build settings).

All releases still use Autotools, which should be unaffected by any changes we make to meson (right now at least).

> Actually, this branch works _for me_ (gcc, clang, x86_64-w64-mingw32-gcc tested with Wine).
> In the CI run ("Meson_Compile_Naev (ubuntu-20.04, bash, linux.ini)" which compiles with clang and links with lld) it won't build.
> I couldn't reproduce the issue on my machine even with the same "meson setup" command. Can I get away with making this @ProjectSynchro's problem? ;)


I'll try to reproduce the build errors you saw in your branch.

**Comment by UncombedCoconut** [comment]
Feedback from @nloewen:

- At first glance, it doesn't feel very "Mesonic" but without digging into it more, I can't really say that it's actually bad.
- I think cc.get_define() should do the same job [as the lj_arch_test step], without having to compile/run/parse, but I don't know for sure. Maybe something worth looking in to, but if everything works as it is now probably not a big deal.
- Does it do that [passing extra arguments to Clang's assembler] if you use add_project_arguments() and add_project_link_arguments() instead of the c_args param?
- Should `if host_machine.system() == 'windows'` test for things like cygwin as well?
(also thoughts on shared/static, but there's a rational explanation for that, I swear.)

Some of these seem like interesting ideas for the repo I borrowed from.
