### ISSUE TITLE
Game crashes if you switch from a ship carrying cargo to a ship with stowed cargo.

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1532]
Repro: load this little fellow, go to the equipment screen, and double-click the pirate Kestrel.

[True pirate.ns.gz](https://github.com/naev/naev/files/5650772/True.pirate.ns.gz)

The save data says
```
<ship name="P-KISTAL" model="Pirate Kestrel>
   ...
   <commodities>
      <commodity quantity="35">Food</commodity>
      <commodity quantity="23">Diamond</commodity>
   </commodities>
   ...
</ship>
```

If that's a legitimate situation, the pilot_cargoMove code needs to handle it correctly.
(If it's not, that code still needs to change.)
It tries to make space for new entries in the dest->commodities array, but clobbers the originals rather than appending.
But also, can the source and destination ships have overlaps in the commodity types? Do we have to dedup? Should we simply call a helper method to add each cargo to the destination?

**Comment by bobbens** [comment]
It shouldn't crash, but the way the game is, you should not have cargo in any ship other than the active ship. This prevents "abuse" like basically storing a shitload of resources on stored ships, going to a planet in a fighting ship, and selling it all. To answer your questions:

0. I would print a warning, and try to merge (or just clobber). This could also be sanitized at load.
1. Source and destination ship can't overlap, since destination can't have cargo.
2. No need to dedup since it should be illegal.

**Comment by UncombedCoconut** [comment]
Wild. I pirated this save file from @asyasb (who reported some separate
issue once and posted a save file which added useful diversity to what I
had). I'd goofed around since then, but the original probably had the same
loaded Kestrel and we can ask about it.
Either way, if the save format says it can happen, it can happen. :)

**Comment by UncombedCoconut** [comment]
Just capturing what came up on Discord: the block on leaving cargo on a ship is on this path:
GUI -> equipment_changeShip -> land_errDialogue( shipname, "swapEquipment" ) -> can_swapEquipment
There's a similar block on the shipyard trade-in path. (The "swapEquipment" and "swap" checks are near duplicates and should maybe be merged?)

There's a gap: Lua scripts can call player.swapShip directly. Example: missions/pirate/pir_ship_stealing.lua. That script's logic could be revisited; the author was already questioning it.
But we basically need to decide
(1) Is untransferred cargo allowed then, or does it have to get jettisoned (with mission-cargo handling as needed)?
(2) Should a call to player.swapShip() be allowed to fail?

My gut says: the "abuse" isn't an issue there, and blocking swapShip on cargo would be absurd within this mission's story, but we'd better avoid untransferred mission cargo or risk other absurd consequences.

**Comment by UncombedCoconut** [comment]
I'm increasingly leaning toward a solution where scripts don't have swapShip() available.
Maybe the pirate mission can convert the ship to an escort (piloted by your crew) until landing.

Mischief to prevent one way or another:

- Load up on cargo. Do most of a sightseeing mission. Steal a ship that can't fit your stuff. Land at the sightseeing drop-off point. Maybe the passengers are stuck as spare-ship cargo and orphaned after sightseeing.lua tries to use pilot_rmMissionCargo. Gods know what anyone would want with kidnapped passengers, but this might create some.
- Almost load up on cargo. Start your ship-stealing mission. Start a mission to smuggle contraband (once we have contraband). Steal a ship that can't fit your stuff. Fly the contraband-free ship to some moon next to the drop-off point. Switch back to your old ship.

There are other ways to prevent exploits involving mission cargo and scripted swapShip() calls, but I can't think of any particularly clean ones.

**Comment by bobbens** [comment]
> But we basically need to decide
> (1) Is untransferred cargo allowed then, or does it have to get jettisoned (with mission-cargo handling as needed)?

I would want to not allow it. Not only does it make some stuff become weird. We would need to also update all the GUI to show what cargo is on what ship, etc... Unless we have some other script that checks when the player lands and can change ship to move all the cargo back to their ship ASAP.

> (2) Should a call to player.swapShip() be allowed to fail?

Honestly, I wouldn't be against it. Have swapShip fail if it can't move cargo. This would allow the mission to check for this and try to do something about it (spawn dialogue about jettisoning and then remove the least expensive cargo, or just abort if not possible).

> I'm increasingly leaning toward a solution where scripts don't have swapShip() available.
> Maybe the pirate mission can convert the ship to an escort (piloted by your crew) until landing.

Although it is tricky to use, I think having swapShip() available is good. I can think of many cases where it could be used to force the player to temporarily use a ship, before restoring their original ship ore something like that (which is what we used to do in the old tutorial).

In this case, having it be your escort is also interesting. Basically spawn a pilot that follows you around or something (can't fight because of lack of crew) and you have to protect it until you get to a "safe system". Would probably make the mission infinitely harder though.

My proposal would be to add Lua helper stuff to handle this that:
1) Tries to swap ship and checks if fails.
2) If fails, sees if it can jettison some unneeded cargo and asks the player if they want to. If it works, swaps.
3) If not, it fails and it can just tell the player (in the pirate mission) that they don't have enough cargo to swap (with some proper flavour text).

The first two could be wrapped, so the mission would just check to see if it can do the jettison swap stuff, and if not, say something about trying again to the player.

**Comment by bobbens** [comment]
OK. I have implemented this mainly Lua side with a `dat/scripts/swapship.lua` helper script that can either succeed or fail. It will also tell the player that it will get rid of cargo (cheapest first) if necessary. Shouldn't remove mission cargo. I have tested it in a script, but haven't tested the pirate stealing mission, and it worked without a hitch.

**Comment by bobbens** [comment]
Closing as theoretically fixed :)
