### ISSUE TITLE
[proposal] use physfs for file i/o

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1543]
Propose to move towards using [physfs](https://icculus.org/physfs/) for all our file I/O. This is probably most important for allowing mods and the likes to exist. Would also help unify our IO which is a bit of a mess with ndata+nfile.

**Comment by Mutos** [comment]
Just read the intro page of PhysFS, 500% OK for that proposal ! Single IO model + easy modding an TCing, where can I vote for it ? ^-^

**Comment by UncombedCoconut** [comment]
Hmm, how about gettext? Replace that too? :)

**Comment by bobbens** [comment]
> Hmm, how about gettext? Replace that too? :)

Oh noes! The "g"-word. For gettext, I think that the "easiest" approach atm would be to integrate some functionality to merge po files into Naev, so on start up it could first try to find all the po files for the user's language and then merge them into a single one and gettext that. While I still think it would be nice to somehow get a better alternative, it feels like digging our own grave ;)

**Comment by UncombedCoconut** [comment]
This is coming along nicely.
Some speed bumps:

- `nlua_newEnv` sets `package.path` based on the ndata dir. That needs to go away, but I'm not sure how to override the `package` library behavior so we query physfs.
- `ndata_read` allows for "slurping" a file directly into a buffer. It's convenient! PhysicsFS doesn't have that feature. We can reimplement it easily if `PHYSFS_fileLength` _de facto_ can't fail. (We don't support device/special files, and that may be enough.) Otherwise a gross dynamic-array solution is needed.
    - For Lua, probably implement [this](https://www.lua.org/manual/5.1/manual.html#lua_Reader) instead.
    - For XML, probably implement [this](http://xmlsoft.org/xmlio.html#Input) instead.
- `ndata_listRecursive` lists each file exactly once. PhysicsFS doesn't have that feature on its own (in case one file lives on 2+ mounts). As such, it's reimplemented atop physfs but not removed.
- We need a new gettext implementation, per the above.
- Finally, there's supposed to be a benefit we can reap. ;)

Possibly non-issues, but I'm unsure:

- Do any scripts (soundtrack, balancer) need to be physfs-aware?
- Do we want saving an editor file to go through physfs?

**Comment by UncombedCoconut** [comment]
Done except for side issues, now tracked separately.
