### ISSUE TITLE
High CPU usage on menu screens, general

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1545]
Using naev-0.8.0-beta.4-linux-x86-64.AppImage on Ubuntu 18.4, I experience one full CPU thread used, plus additional from another, for total of 30% of 4 threads possible, when the game is 'idle' on any menu or when paused.  I would expect the game to pause unnecessary processing, rather than wasting CPU time generating wasted heat and wearing out my laptop fans.  FPS limit set to 60.

This is not related to sound (a previously reported issue) ... sound disabled/enabled does not appear to affect this.

**Comment by UncombedCoconut** [comment]
Totally valid criticism.
I've noticed the same while working on Naev.
It also looks very hard to fix. Naev is mostly not designed to pause unnecessary processing; there's a game loop active even when the user interface is up. This has some upsides, like how easily the main menu supports its background animations, but it's bad for energy efficiency. Similarly, Naev calculates a lot of stuff each frame rather than trying to cache/invalidate things like background window contents. This makes it easy to avoid a whole class of bugs, but it's bad for energy efficiency.
So this issue will probably stay open a while, and the best thing to tell everyone who sees it is: be sure to set an FPS limit, like the OP did. That will improve Naev from "furnace" to "breezy battery hog".

**Comment by bobbens** [comment]
My love2d branch handles this partially, in the sense that dialogues now also run the fps control stuff. I'll probably close that when merged, but that's not targeting 0.8.0.

**Comment by bobbens** [comment]
So there is a different fps control when menus are up now in main branch, which means it should be a lot less intensive in many cases. fps control can also lower cpu usage. Closing.
