### ISSUE TITLE
Console log warnings

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1550]
Using naev-0.8.0-beta.4-linux-x86-64.AppImage on Ubuntu 18.04, I get these console warnings (in addition to the Cargo Rush warning already reported):

Warning: [event_runLuaFunc] Event 'Travelling Merchant' -> 'broadcast': [string "events/travelling_merchant.lua"]:68: Pilot is invalid.
Warning: [hook_runEvent] Hook [timer] '227415' -> 'broadcast' failed

Warning: [misn_runFunc] Mission 'Sirius Pilgrimage Transport' -> 'create': [string "cargo_common.lua"]:201: bad argument #1 to 'format' (string expected, got userdata)

**Comment by UncombedCoconut** [comment]
Thanks!
That first one is probably fixed by this commit (from after the beta.4 release): https://github.com/naev/naev/commit/d61d66dc048d1c428186a77d2f87177c05616435
That second one is probably fixed by this commit (from after the beta.4 release): https://github.com/naev/naev/commit/a890f22581e7dac6bb489d34465a13aa3a366f1b
I'm checking, but I think that 2nd one is likely to explain issues with Cargo Rush and the Empire campaign. It also probably means the AppImage version isn't using LuaJIT, which I didn't realize. That has the potential to make beta.4 pretty broken for AppImage users.

**Comment by tzargoth** [comment]
Ah, okay.  I guess I'll have to wait for beta 5 to be able to make progress on the main campaign missions (the other issue I opened).

**Comment by UncombedCoconut** [comment]
If you have time and would like to help confirm that, you can try downloading the latest nightly AppImage from here: https://github.com/naev/naev/releases
My best guess is that it could unbreak several missions for you and would be worth a try. Thanks again for testing and reporting!

**Comment by tzargoth** [comment]
Sure, I'll give that a try.  Also, I got one game crash, "free(): invalid next size (fast) ... core dump" ... is there some place to get more details on this for you?

**Comment by UncombedCoconut** [comment]
When possible, steps to repeat are the best thing to share. (If it requires your save file, that will be in `~/.local/share/naev/saves/`.)
Of course, some bugs are not cooperative enough to happen every time you do something.
I'm not sure how practical it is to trace these release builds, but perhaps you could try running
`ulimit -c unlimited`
and running Naev in the same terminal. If it crashes, it will actually write out a file like `core.12345` which can be shared.

**Comment by tzargoth** [comment]
The crash only happened once, and didn't repeat after reload, so not sure what triggered it.  I'll see if I can get a core dump with that setting the next time.  Thanks.

**Comment by bobbens** [comment]
Closing as seems fixed in master.
