### ISSUE TITLE
FLF prelude mission issues

### ISSUE THREAD

**Issue by tzargoth** [naev/naev#1574]
With the variety of ships a player can use, the 25 second mission timer, and class of ships the FLF use in the Sigur system, can lead to mission failure in these ways:
- stronger player ship leads to all FLF ships destroyed and agent in a coma (he never wakes up)
- stronger player ship can lead to awake agent, and request to follow, but player ship is too slow to keep up with FLF ships (they currently do not escort)
- a faster ship can leave the player too far from the FLF ships when the agent wakes up, losing signal and failing the mission

This mission needs to be robust enough to handle these variables more gracefully.  And, maybe if the player is stupid and doesn't follow the FLF ships (when they could have done so), the Agent really shouldn't be some vegetable waiting to be handed over to the Dvaered ... realistically, he'd want to be let off on the nearest station/planet.

**Comment by onpon4** [comment]
Just want to mention the possible solution mentioned on Discord:

1. Make it so that the FLF pilots you fight go to your position before they start going to their waypoints.
2. Check the player's ship class and add an FLF Pacifier if the player has a medium or large ship. A second Pacifier could also be added in the case of a large ship which comes equipped with a very bad engine (probably Beat Up Small Engine with a lot of weight to the ship).
3. If any ship gets damaged, immediately wake Gregar up (should prevent any possibility of the FLF pilots being destroyed).
4. If you fail to follow the FLF ships, fail the mission with something about how Gregar leaves your ship or something.

🕵️

**Comment by onpon4** [comment]
OK, so I've come up with a different solution which nonetheless seems to work pretty well:

* If piloting a large ship, a Pacifier is added to even things out.
* Before starting their normal waypoints, all FLF ships follow you until they are very close to you. This ensures they don't go out of range before you even have a chance to follow them.
* FLF ships limit their speed to slightly slower than your ship, ensuring that it is always possible to follow them.

🕵️
