### ISSUE TITLE
Translations don't work

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1595]
Is it just me, or did translations stop working once again?
I build Naev from a fresh repo, following the instructions in the readme but I always get English instead of German. Config log says that translations are on.
Tested in 96ab927f7c37680911a5aa1ea8f7a522125f5765.

It worked couple of commits / days ago.

**Comment by UncombedCoconut** [comment]
At the moment, it's a pain in the ass to test translations in a local build.
Here's how I do it:
`[builddir]$ meson compile && DESTDIR="$(pwd)"/dest meson install && ./naev.sh "$(pwd)"/dest/usr/local/share/naev/dat`
I think that solving #1543 will be our key way of making this less painful. Once that's done, the simpler instructions in the project readme should be sufficient.

**Comment by Wuzzy2** [comment]
Well, I tried that, but it didn't work either. I guess I just have to wait until the aforementioned issue is fixed then …

**Comment by UncombedCoconut** [comment]
Fair warning: if that didn't work, your problem is new to me. (I've tested the above command and it gives me German text if my configuration says `language = "de"`.) So the above plans may not fix it for you either.
One quick thing to check: did that "meson install" command create this path underneath your build dir? `dest/usr/local/share/naev/dat/gettext/de/LC_MESSAGES/naev.mo`
If that file is OK, and the log said it was using "de", it sounds like a new (to me) issue with the C code.

**Comment by bobbens** [comment]
This seems like it really should fixed. I think as mentioned, using physfs and having it detect when it's running from source repository to add the translation paths (and others as necessary), does seem like the best approach to handle it. That said, I'm not sure if we can get physfs to play well with gettext since it requires using non-standard reading functions which aren't exposed in the API I believe. If it isn't possible a more ad-hoc solution might be necessary, such as look for multiple paths to see where to set the gettext, but even then, gettext requires a specific file structure that will have to be done with the build system.

**Comment by UncombedCoconut** [comment]
There is some experimental code going into today's nightly build, which should allow you to run
```
meson compile
meson compile naev-gmo
./naev.sh
```
and get the translations.

Because this implementation involves quite a bit of new code (to solve the larger problem of letting Naev mods / data overlays include translations of their own content), and the last bits were rushed in ahead of the cutoff for nightly builds, I won't be surprised if things are merely broken in a different way. But they're no longer supposed to be broken. :)

**Comment by UncombedCoconut** [comment]
At this point, I assume translations are working unless someone re-tests and reports otherwise.
Unfortunately there's no way around the extra "meson compile naev-gmo" step (other than installing), but it's reflected in our Readme.md file.

**Comment by Wuzzy2** [comment]
Huh. I just pulled, followed the instructions and it did not work. But after I set the language EXPLICITLY to “de”, it worked. I had “system” selected before, but my system language is German. So it seems the Naev “system language” option does not work.

Also, please don't forget to update the README file because `meson compile naev-gmo` is not in it yet.

**Comment by UncombedCoconut** [comment]
Thanks for checking!
That's a good point -- the new Naev code is as smart as the old Naev code at detecting the system language, but I think we need to implement more of the libc locale logic ourselves now.
I'll work on that today.

If you'd like to share relevant variables shown by `env`, I'll pay extra attention to your situation. Otherwise I'll just check libc documentation.

"meson compile naev-gmo" is in Readme.md (https://github.com/naev/naev/commit/90f17176440ff78795514f6e8e57a931ae929e5e). README doesn't have instructions to compile at all (and should probably be removed.) Am I missing something?

**Comment by onpon4** [comment]
We removed README from Naikari some time ago. No negative effects from that so far as I can tell.

🕵️

**Comment by Wuzzy2** [comment]
OK, I meant `Readme.md`. I have no idea why Naev has two “readme” files. \*shrug\*

My `LANG`:

```
LANG=de_DE.UTF-8
```
