### ISSUE TITLE
Carefully ensure all "Redistributions in binary form must reproduce the above copyright notice" requirements are honored

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1606]
Post-0.8, we've been adding a fair amount of stuff. Reminder to double-check later that all binary distributions fully credit our library authors. (In some cases, I'm not sure if embedding the library triggers the clause, but we're nice people and we may as well...)

**Comment by bobbens** [comment]
Does it have to be done every run or can it just be thrown into credits? Additionally, a licensing window or something could also be displayed in options or something.

**Comment by UncombedCoconut** [comment]
I think even a stand-alone text file is fine. The main concern is having the message in .c/.h files which don't make it into binary distributions.
(Including them in credits makes sense to me, but maybe a thanks there and the exact notice off to the side.)

**Comment by onpon4** [comment]
If you're referring to the 3-clause BSD license, what it specifically says is:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

That's clearly referring to the license file. So that's not a thing asking for an entry in the credits (unless you're planning to put multiple copies of the 3-clause BSD license in the credits), it's just telling you to include the LICENSE.txt or whatever. This should go hand-in-hand with properly documenting Naev's exact license for the entire repository. I believe I mentioned a couple years ago, we need to have a license documentation file which clearly states licensing intent for everything, rather than just having a copy of the GNU GPL sitting there. I can do the bulk of the work (IANAL but I have enough experience with licensing stuff that it's not hard for me to do) but I really need @bobbens involved in this, namely to give a clear answer on what the licensing policy is going to be stated as, and in particular what our default license is (because while I believe I know the answer to that, I don't have the legal authority to decide the license of his work for him; I really need an explicit direction here or anything I do will be entirely meaningless).

Related: #638

If we get that done and over with, any additional licenses will just be a matter of listing those there similar to what SuiteSparse does.

🕵️

**Comment by bobbens** [comment]
> That's clearly referring to the license file. So that's not a thing asking for an entry in the credits (unless you're planning to put multiple copies of the 3-clause BSD license in the credits), it's just telling you to include the LICENSE.txt or whatever. This should go hand-in-hand with properly documenting Naev's exact license for the entire repository. I believe I mentioned a couple years ago, we need to have a license documentation file which clearly states licensing intent for everything, rather than just having a copy of the GNU GPL sitting there. I can do the bulk of the work (IANAL but I have enough experience with licensing stuff that it's not hard for me to do) but I really need @bobbens involved in this, namely to give a clear answer on what the licensing policy is going to be stated as, and in particular what our default license is (because while I believe I know the answer to that, I don't have the legal authority to decide the license of his work for him; I really need an explicit direction here or anything I do will be entirely meaningless).

Honestly, as long as it's DFSG-compatible, anything should be fine. Probably as default licenses we would want something like GPLv3+ for source code (C/Lua), and CC-by-sa v4+ for other data.
