### ISSUE TITLE
Benito thanks you for destroying Sindbad

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1631]
When you are asked to defend Sindbad and you destroy it instead, Benito still thanks you.  The Empire and Dvaered will avenge
her since you need a powerful, hence slow ship to do the deed, but still, Benito's reaction makes no sense.
Either make her angry at you for betraying her and the FLF, or let her have an epiphany that the FLF, while fighting the
Dvaered warlords, have become just as bad as them with their Bias For violent Action, and maybe it's better this way
if the FLF destroy themselves.

**Comment by onpon4** [comment]
Ah, I didn't even realize that was possible. I suppose I could make doing that cause the FLF to hate you as an easter egg. (Of course, this would also lock up the FLF campaign's reward.)

🕵️

**Comment by onpon4** [comment]
There we go, just did that. I didn't make it scold you or anything, I just made it so that you lose all your rep with the FLF (causing the FLF to attack you). Specifically you lose 10 rep every time you attack Sindbad, and if it's below 0 when Sindbad is destroyed, it gets set to -100 and you don't get any of the event's rewards.

🕵️
