### ISSUE TITLE
[proposal] boarding

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1635]
Boarding is horrible and a relic of the EV clone past. It's time to get over it. This proposal discusses what I believe to be the best direction for improving boarding.

1. It should be implemented in Lua (love2d stuff can be used to render arbitrary stuff, will have to be consistent with the toolkit though)
2. Should have a minigame
  2.1. Needs to have a difficulty setting (based on boarding ship vs boarded ship)
  2.2. Should be fairly fast (10 to 30s)
  2.3. Have a random factor
3. Probably have a limit on what/how much you can take based on how well you did in the minigame

For the minigame, I would recommend something like [paradroid](https://www.youtube.com/watch?v=azKPxC425XA), of which there is an open source clone "freedroid", although it is in C. However, if anyone else has good minigame recommendations, I'm all ears.

**Comment by onpon4** [comment]
Honestly, Paradroid's takeover mechanic is simple enough that we could even implement it in C easily enough if we needed to, though Lua might be easier with that Love2d API you've got. Probably we would make the number of "charges" you get depend on crew size, and we would want to make sure it looks like a regular window (so that it's well-integrated into the game visually). Graphics-wise, we need to make sure that either we use two colors that are very different brightnesses, or use something other than color, to ensure that it's colorblind-accessible.

Thinking of alternative ideas, the only one I can think of so far is to instead have boarding itself be a sort of top-down maze-based shooter minigame where you try to physically loot the ship. That would probably be overly complicated though (and it would probably feel like a completely different game interrupting the game people want to play). I like the Paradroid idea better.

🕵️

**Comment by agb32** [comment]
Or a top-down map of the ship you're boarding, which you have a brief time to wander around and collect stuff from (which perhaps your crew do some fighting or something).  But paradroid idea would keep it simple...

**Comment by V-ktor** [comment]
My idea (for a game I wanted to make but stopped) was to have a turn based game with a top-down map of both ships involved in boarding, consisting of separate sections. Each turn the player can move crew between adjacent sections. After that, the troops in each section will attack each others. If only one side survives the section is captured which will have some effect depending on the type of the section, e.g. when capturing a cargo bay some cargo will be stolen.

**Comment by agb32** [comment]
V-ktor, I think you could do what you want with the Battle for Wesnoth engine...

**Comment by bobbens** [comment]
> My idea (for a game I wanted to make but stopped) was to have a turn based game with a top-down map of both ships involved in boarding, consisting of separate sections. Each turn the player can move crew between adjacent sections. After that, the troops in each section will attack each others. If only one side survives the section is captured which will have some effect depending on the type of the section, e.g. when capturing a cargo bay some cargo will be stolen.

That might be too much for Naev. Ideally it should be 10 to 30 secondish short minigame (maybe longer for capital ships). Don't want this to be that big and complex of a mechanic if possible (although since Naev supports Love2D API now, you can theoretically add other minigames all over).

**Comment by bobbens** [comment]
More thought on the topic: do we actually need a boarding mini-game? Do we actually have to limit what the player can board? The only place I think it "could" be an issue is if the player is strolling around in their starter llama, and they find a disabled pirate kestrel or something, and loot everything, but even then, I think that could be a fun mechanic, and o I don't think it would be game-breaking.

Maybe it would be enough to just make the boarding interface somewhat akin to a treasure chest in an RPG, and allow the player to take everything, or just something they want. While I do like the idea of adding a mini-game to get more loot or something like that, I'm starting to feel that it may not be necessary, given that disabling ships itself is somewhat the minigame.

**Comment by bobbens** [comment]
Changed it so that boarding always succeeds and now boarding androids provide a credit / cargo percent boost. Still think the interface needs an overhaul.
