### ISSUE TITLE
shader framework needs flexibility

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1695]
This is not a major issue atm, but at the current time, all shaders are hardcoded in a python-generated anonymous structure. While this is fast and efficient, it doesn't allow things like specifying shader by name in the xml files and thus wouldn't scale to defining shader effects which could be useful for weapons, activated outfits, damagetypes, etc... Now it's not entirely clear how to do this efficiently, I would propose something like setting up an array with names and pointers to the ids in the current anonymous struct. This would allow adding an API to get/set shaders and uniforms (albeit with some overhead), without losing the speed and easy-to-use interface we currently have. All that would have to be done is:
1. Create an array for all the shaders (and have the program, vertex, and fragment shaders accessible by pointer (or value assuming IDs don't change))
2. For each shader, create an array of uniforms with name so they can also be acquired and set by API

**Comment by UncombedCoconut** [comment]
Thinking about this from a type-safety perspective, I'd expect shaders not to be interchangeable unless they're in some explicit family/class.
So my idea would be to support definitions like this in `shaders_c_gen.py` (throwaway example with 2 "circle" shaders and 2 "trail" shaders):
```python
   Shader(
      name = "circle",
      class_ = "circle",
      vs_path = "circle.vert",
      fs_path = "circle.frag",         
      attributes = ["vertex"],
      uniforms = ["projection", "color", "radius"]
   ),
   Shader(
      name = "circle_filled",
      class_ = "circle",
      vs_path = "circle.vert",
      fs_path = "circle_filled.frag",
      attributes = ["vertex"],
      uniforms = ["projection", "color", "radius"]
   ),
   #...
   Shader(
      name = "trail", 
      class_ = "trail",
      vs_path = "trail.vert",
      fs_path = "trail.frag",
      attributes = ["vertex"],
      uniforms = ["projection", "c1", "c2", "t1", "t2", "length", "dt" ]
   ),
   Shader(
      name = "trail_zalek",
      class_ = "trail",
      vs_path = "trail.vert",
      fs_path = "trail.frag",
      attributes = ["vertex"],
      uniforms = ["projection", "c1", "c2", "t1", "t2", "length", "dt" ]
   ),
```

Then the emitted C code could emit `ShaderAttrs_circle` and `ShaderAttrs_trail` types instead of anonymous structs, and provide accessors like shaders_trail_get(name).

This should solve most problems, unless we want to let physfs mods provide new named shaders. (It may be premature to worry about that.)
If we do want that, then maybe the codegen should shift to generating these kinds of shader classes, and the instances can be defined by files in dat/glsl. This idea is a bit trickier to flesh out in a satisfying way.

**Comment by bobbens** [comment]
I was overthinking this. `GL_ARB_shader_subroutine` does seem to give us a lot of flexibility as we can define arbitrary functions by name and use the from XML. The only downside is that not everyone will necessarily have this (although most should), so it is a bit more messy than just requiring opengl 4.0.

**Comment by bobbens** [comment]
Closing as I'm considering this basically solved with `GL_ARB_shader_subroutine`.
