### ISSUE TITLE
[VN] Transitions don't work well with semi-transparent canvases

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1709]
Code to reproduce:
```
local vn = require 'vn'
local love_shaders = require 'love_shaders'
local graphics = require 'love.graphics'

paperbg = love_shaders.paper()
vn.clear()
vn.scene()
vn.func( function ()
   vn.setBackground( function ()
      vn.setColor( {0.2, 0.2, 0.2, 0.8} )
      paperbg:draw( 0, 0 )
   end )
end )
local voice = vn.newCharacter( _("Unknown Voice") )
vn.transition( "hexagon", 3 )
vn.na("Foo")
vn.done( "hexagon" )
vn.run()
```
The above code should be saved to something like `foo/main.lua` and then it can be run with:
```
love = require 'love'
love.exec( 'foo' )
```

**Comment by UncombedCoconut** [comment]
Aside: is recursive love.exec allowed? If I `love.exec( 'foo' )` twice, `_checkstarted` barfs ("vn: can't modify states when running"), as though no `vn.run` statements after `love.exec( 'scripts/vn' )` ran.

If I wrap this code in `function foo() ... end` (run with `require 'foo'` and `foo()` to repeat), it works as long as I ensure `love_shaders().paper()` is only called once. Per Naev process. That seems like it shouldn't matter, but it seems to matter.

One debugging technique that looks promising is simply hacking `vn.transition` to pass `1` instead of `progress` in the `shader:send( "progress", progress )` line. If there's still a jump at the end (and there is), it's a lot easier to see what the difference is. In this case, it looks like the background Naev scene is missing from what we draw during the transition.
Similarly, drawing as if `progress==0` should have no jump at the start.

All transition shaders should agree on what role `effect()`'s `color` parameter plays. Majority rules => no role. (It really has to be either irrelevant or a constant -- we don't have a "before" and "after" value, after all.)

**Comment by bobbens** [comment]
Recursion is not allowed. Both the love2d stuff and the vn stuff use global state stuff. Recursion would be really hard to do in a sane way, and honestly, I don't think it is necessary.

Yes, colour should probably be multiplied to the final effect in all cases, but I don't think it is too important given that in all cases the colour will be `vec4(1)`.

I still don't know what is going on. The fact it works with 1 or 0 alpha but not with other values is just weird.

**Comment by UncombedCoconut** [comment]
Most important: you were right about the blend mode being an issue. Cf. https://love2d.org/wiki/Canvas
Med. important: (1,1,1,0) is the wrong clear color. (0,0,0,0) is neutral and correct, though the above needed to be fixed first.
Saved for later: mix() of colors is still shady. It manages to look fine here; the issue is when the rgb colors and alpha are both quite different. (Mixing a color with near-transparent should not change its color so much.)

[This Haskeller](https://lukepalmer.wordpress.com/2010/02/05/associative-alpha-blending/) gave a fast explanation of how two alpha-blends compose. (That math doubles as another explanation for the "premultiplied" mode for canvas-canvas draws.)

From this, and some calculus, one can crank out an accurate color mix function (answering: what blends the same as the `1-t`th iterate of blending the first color and then the `t`th iterate of blending the second?).
It would look something like
```
{
   vec4 color;
   float c1b = pow(1-c1.a, 1-t);
   float c2b = pow(1-c2.a, t);  
   color.a = 1 - c1b*c2b;
   color.rgb = mix( c1.rgb, c2.rgb, c1b * (1-c2b) / color.a );
}
```
How fussy! No wonder no one bothers.

**Comment by bobbens** [comment]
Thanks for the explanation! We could use that blend function for all the transitions, but it does look fairly expensive (and not like most transitions are cheap)
