### ISSUE TITLE
[Love] Drawing to non-full screen canvas has texture coordinate issues

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1713]
Test code is as below:
```
local vn = require 'vn'
local minerva = require "minerva"
local love_shaders = require "love_shaders"
local graphics = require 'love.graphics'

vn.clear()
vn.scene()
blurred = love_shaders.blur( graphics.newImage( 'gfx/vn/characters/cyborg_chicken.png' ) )
--blurred = graphics.newImage( 'gfx/vn/characters/cyborg_chicken.png' )
local cc = vn.newCharacter( minerva.vn_cyborg_chicken({image=blurred}) )
vn.transition()
cc("Test")
vn.done()
vn.run()
```
It is expected that original image is shown blurred in the same place, however, we can see some clear texture displacement, meaning that there is some issue with how we are dealing with coordinate changes with non-fullscreen canvases.

**Comment by UncombedCoconut** [comment]
OK, I'm able to look again.
... Oh shit, just by varying the game window size I can see that this step -- `graphics.draw(image, 0, 0, 0, 1, 1)` -- is trying to draw the image at a size of SCREEN_W*SCREEN_H (note, testing at scale=1 here, so maybe it's gl_screen.rw*gl_screen.rh or something, doesn't matter) instead of the current canvas's w*h.

**Comment by UncombedCoconut** [comment]
DIE!!! (We can revisit the blur stuff separately as needed.)
