### ISSUE TITLE
Regenerate all ship graphics and convert to webp

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1723]
Currently we use png to encode all ship graphics. It should be changed to lossless webp. Our current graphics seem to be rendered at high resolution and then down-scaled before being put in-game. It would make sense to rerender them at native in-game resolution (or some multiple of that) and use that in-game. This would sort of kill two birds in one stone by making ships look nicer and have the data be more compact. I have gotten render scripts (and documented it!) with Ubuntu 12.04, so it should be feasible with relatively little work.

Another thought would be to possible rerender at higher resolution (or supply a higher resolution version) for when scaling/highdpi is enabled. This would look better for most players (we could also try to detect dpi/highdpi and scale by default).

**Comment by UncombedCoconut** [comment]
They're all webp, so I think we should identify the follow-ups and close this.
Is it not true that because of camera zoom there is no one native in-game resolution for ship graphics?
That makes me think we should focus on 3D ships and possibly a project to create a Naev plugin containing high-res assets.
I could imagine making higher-res sprite sheets for everyone, but the ones we've got are already pretty hefty.

**Comment by bobbens** [comment]
What would high-res be for ships? We right now keep ship sprite sheets at 2048x2048. If we, for example, double that to 4096x4096, that will be roughly 60 MiB GPU RAM per large ship (or 4x what each ship uses now). I think we may hit GPU memory issues on some older GPUs. We could probably increase size a bit more, but I do feel like the only way to actually do "high resolution" is going to be by going 3D which opens another set of issues (missing models, models not meant for real-time rendering, etc.)

**Comment by UncombedCoconut** [comment]
I'm calling this done except for the follow-up in #1894 (3d ships).
