### ISSUE TITLE
With friends like these...

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1758]
When I'm friendly with the pirate faction and have taken out a search&destroy mission for a specific pirate, and his pals start to
shoot at me, I can't target them with 'r' - they are still considered friendly, even though they shoot at me.

**Comment by nenau-again** [comment]
Oh, this one is actually a though one.
Because a pilot is friendly if they have the friendly flag OR are in a faction allied to the player
While a pilot requires not to be friendly in order to be considered hostile.
I guess there might be a way to solve this by re-thinking the logic of hostile and friendly, but it requires to think hard on that.

3 things to do:

* Please confirm that their ammo can hit you and reciprocally (otherwise we have a true problem)
* A short-term solution is to make the ambushers an other faction (like the `Shadow_pirates`, or a dynamic one I guess)
* But I guess this friendly and hostile problem needs to be addressed

**Comment by amylaar** [comment]
> Oh, this one is actually a though one.
> Because a pilot is friendly if they have the friendly flag OR are in a faction allied to the player
> While a pilot requires not to be friendly in order to be considered hostile.
> I guess there might be a way to solve this by re-thinking the logic of hostile and friendly, but it requires to think hard on that.
> 
> 3 things to do:
> 
>     * Please confirm that their ammo can hit you and reciprocally (otherwise we have a true problem)

Confirmed (from vivid memory).  Their ammo can kill me before I know it if I'm on autonav. (it doesn't seem to stop autonav till I'm dead)
If I go in more carefully, I can get them before they kill me with some fast keyboard work and a modicum of luck.
> 
>     * A short-term solution is to make the ambushers an other faction (like the `Shadow_pirates`, or a dynamic one I guess)
> 
>     * But I guess this friendly and hostile problem needs to be addressed

It would be nice if autonav also stopped for attacks on an escorted ship.  Ideally, there would be a separate slider for that,]but I think handling an attack on an escortee like an attack on the player would be better than ignoring it as of now.

**Comment by nenau-again** [comment]
I changed the logic a bit. I hope it won't make something else catch fire...
