### ISSUE TITLE
map cost/trade swapped

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1788]
When I select map mode Food:Cost, I get map mode Food:Trade, and vice versa.  Likewise for the other commodities.

**Comment by onpon4** [comment]
I see what happened.

The code is making an assumption that requires one type of mode to be odd-indexed and the other type of mode to be even-indexed, which is a very sloppy design that ended up screwing up when Discovery mode was added. Proper fix would be to get rid of that assumption so that this doesn't happen again.

🕵️
