### ISSUE TITLE
Making bounty missions more doable

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1794]
A common request is to make pirate bounties and such be their own faction so that they aren't blasted to smithereens by patrolling Empire or whatnot forces. Something like that could be done, while compensating for the fact that without being hostile to other ships, they would literally not really do anything and probably fly away. Something like actively seeking out the player or spawning the player could work.

**Comment by Lineth** [comment]
When I tried it on a home build by making the "Bounty" faction hostile to merchants, civilians, and the player it seemed to work. Bounties already seem to spawn near-ish to the player when they warp in. But a command to actively pursue the player would be a good fail-safe if they don't have any valid targets nearby.

**Comment by bobbens** [comment]
The issue is that if the bounty attacks a merchant and this merchant sends a distress signal, it should cause Empire ships nearby to attack it. I don't think this was implemented to only affect the player. However, it would be less likely than now.

**Comment by Lineth** [comment]
I was just thinking that when I made the homment, d'oh. 🤐

**Comment by amylaar** [comment]
In terms of payment, it's not that bad for dead-or-alive missions, since, if the pirate doesn't run away, you can generally take of them quickly, and even if you can't, there's the 'lesser reward' mechanism.
What's annoying is that you don't get even a fraction of the mission reputation gain when that happens.

Also, if the authorities want a pirate alive, what are the grunts doing killing the pirate?

So, a solution might be to give a reputation share with the 'lesser reward', plus make the 'wanted alive pirates another faction,
e.g. "Supergrass" (Assuming they are wanted alive because they might divulge info leading to higher-value targets in return for lenient sentencing and witness protection.  Actually, it seems possible that the only way they can get out alive is to be captured by force (keeping up plausible deniability and all that) .)

**Comment by nenau-again** [comment]
> Also, if the authorities want a pirate alive, what are the grunts doing killing the pirate?

Very few people in naev universe seem to fully understand the concept of "not killing". Some get quite close to it and equip disabling weapons... But then they still shoot at disabled ships until they explode :o/

Sidenote : I thought the alive bounty pirates were part of a special faction that was not attacked by others. Was I wrong ?

**Comment by Lineth** [comment]
Alive bounty pirates are indeed part of the "Wanted Pirate" faction, but that faction is still hostile to pretty much everyone.

**Comment by bobbens** [comment]
> Alive bounty pirates are indeed part of the "Wanted Pirate" faction, but that faction is still hostile to pretty much everyone.

I see, that is a bit weird. I guess the best solution now would be to:

1. Remove `Wanted Pirate` faction and make it dynamic (less faction pollution \o/)
2. Make the faction only hostile to the player
3. Have the pirate just sort of idle around the system pretending to be doing stuff (preferably not near Empires and such) and beeline to he player when they are spotted.

That would probably solve most of the issues without too much loss in realism.

**Comment by bobbens** [comment]
Implemented what I mention above.
