### ISSUE TITLE
Wrong ship price in the shipyard screen

### ISSUE THREAD

**Issue by SlightPersimmon1** [naev/naev#1847]
Hello,

I started playing naev today and noticed that the ship price, in the shipyard screen shows my funds instead of the ship price. This happens on both v0.8.2 and v0.9.0 alpha (1+533.gf2ef0dd29.20210703).

Please see the image.

![ss1](https://user-images.githubusercontent.com/65872044/124366063-d25b0780-dc44-11eb-9c1a-cad6d4e3c1f2.jpg)

**Comment by onpon4** [comment]
More precisely, the "Time Constant" header is breaking into a newline, causing it to take up two lines and thus offsetting all the stat headers below it. The price is the "201.00 k¤" above what you highlighted.

🕵️

**Comment by SlightPersimmon1** [comment]
You are right! I did change the font size (since the default font - Cabin-SemiBold.otf is too small for me). 

So it's not a bug after all. Sorry for this.
As a suggestion, and since we are already using otf and ttf  as fonts, it would be great to see the ui auto-adjusting to the font size.

Please, close this issue if you can. I am not sure i can do that.

**Comment by UncombedCoconut** [comment]
No problem. The situation's definitely not ideal -- if we made a dedicated "table" instead of 2 separate text columns (which is hard), there'd be no problem. And, yes, UI layout is mostly manual. Either of those can become issue trackers referring back to this example, but they're not very high on the priority list.

**Comment by bobbens** [comment]
In general, instead of increasing the font size directly, it is better to use the scale factor which indirectly increases the font size. In fact, given that the font size does cause issues like seen here, it would be best to drop support for that and make scaling support more explicit like mentioned in https://github.com/naev/naev/issues/1776

**Comment by onpon4** [comment]
I think it's worth noting that with some slight interface tweaks it's possible to make the text much bigger as a baseline:

![Screenshot from 2021-07-03 17-17-56](https://user-images.githubusercontent.com/2217995/124392262-851d7b00-dcc2-11eb-8703-0bcf74fb47e0.png)

🕵️

**Comment by PhoenixRiver** [comment]
Reshowing the image of the craft does indeed seem to be a bit
redundant and this layout seems decidedly cleaner... though I suppose
more scrolling is necessary... at least for people buying more
expensive ships...

Phoenix
