### ISSUE TITLE
[Proposal] Missile Rework

### ISSUE THREAD

**Issue by Lineth** [naev/naev#1861]
At the moment, guided missiles are in the awkward position of both being overpowered against larger ships and still feeling bad to use (especially missile turrets). Jammers do not seem to do anything at all to fix this. Possible fixes to this:

- Make jammers slow nearby missiles down.
- Give jammers a chance to make guided missiles unguided, Escape Velocity Nova style.
- Implement point defense turrets for large warships. would require implementing missile health, but would give large warships a chance against ceasar spam.
- remove lock-on or reduce it dramatically for smaller missiles and give them a chance to lose tracking entirely. works with jammers increasing tracking loss chance.
- make jammers force missiles to lose their lock-on entirely is another thing that might help

**Comment by Lineth** [comment]
Another thing I should point out is that at the moment jammers seem to have absolutely no use whatsoever.

**Comment by bobbens** [comment]
My 2 yen:
1. We probably want different mechanics for torpedoes and missiles. Reducing missile speed or making them go haywire does seem like a good potential solution there, but torpedoes shouldn't be subject to the same or they will be basically nullified with jammers that don't significantly affect torpedoes.
2. Point defense does seem like something we would potentially want for torpedoes. They would basically serve as a limit to the amount of torpedoes that can be on you at a given time. If 1 point defense nullifies 1 torpedo launcher, you would still be destroyed by multiple launchers.
3. For missiles, I find lower speed to be most interesting. It could be implemented as lowering "Max Speed / Max Turn" so that it wouldn't affect torpedoes or just add a factor to ignore it for torpedoes. That way you would not be immune, but if you slap on the jammer and hit the afterburner, you would leave missiles in the dust. Or you could just dodge them (especially efficient if turn is weakened). Having them just randomly go away just seems like giving too much to chance.

**Comment by Lineth** [comment]
For a missile rework, how about this:
- Lock-on to fire removed. Missiles launched immediately. Torpedoes can still lock on, but in the interest of consistency, probably not.
- Missiles in flight take a second or two to lock-on, depending on size of missile and target, as well as modifiers like concealment and ship heat.
- Jammers and scramblers, on top of adding concealment, give a chance for the missile lock-on to fail (even if only temporarily), making them behave like rockets.
- Point-defense turrets for heavy ships which automatically attempt to shoot down torpedoes and the like. May target small ships as well. Either missiles have 'health' that gets chipped away by PD turrets or there's an inherent chance for the missile to ignore the shot.

**Comment by bobbens** [comment]
> Lock-on to fire removed. Missiles launched immediately. Torpedoes can still lock on, but in the interest of consistency, probably not.
> Missiles in flight take a second or two to lock-on, depending on size of missile and target, as well as modifiers like concealment and ship heat.

The only downside I can see of moving lock-on from ship to missile itself is that it won't be as easy to understand to the player, especially if electronic warfare stuff affects. I guess you could make an icon to indicate how many seconds it takes or something, but it might be a bit confusing. It might be easier to just keep the lock-on mechanic and make it significantly faster for missiles (1 to 3 secs), while keeping it somewhat delayed for torpedoes (5 to 8 secs).

If we do switch to making missiles lock-on after launch, how much time should it take for missiles vs torpedoes? How would ewarfare affect? Currently it is possible to have launchers that can literally not lock onto small ships, and it might be frustrating to the player if that happens without knowing. On the other hand, you could use Imperators as unguided rockets to one-hit small ships :D

> * Jammers and scramblers, on top of adding concealment, give a chance for the missile lock-on to fail (even if only temporarily), making them behave like rockets.

How would the fail thing work? How would we convey to a player?

There's multiple options:
1. Have jammer chance and resistance chance be separate rolls. Roll first for jamming, if it would be jammed, you then roll for resistance and in the case that fails it gets jammed. This would mean that all weapons could be potentially jammed. Likely would have something like jammers with 30% chance and torpedoes have 80% resistance or something like that, leading to only 6% effective jamming chance.
2. Have jam chance be computed as `jamming - resistance`. So a 30% jamming weapon would never be able to jam a 40% resistance weapon. However a 40% jamming weapon would have a 10% chance of jamming a 30% resistance weapon.

Checks could also be done in at least two ways:
1. The check would be done once per missile at a certain distance. This is probably best.
2. It would be normalized so it is computed once per second or once per XXX seconds. Would be harder to visualize to the player and would make it so slow missiles get many more checks.

> * Point-defense turrets for heavy ships which automatically attempt to shoot down torpedoes and the like. May target small ships as well. Either missiles have 'health' that gets chipped away by PD turrets or there's an inherent chance for the missile to ignore the shot.

I like the idea of giving missiles health and maybe some dodging chance for PD. That way it would naturally work with small fighters and the like. It is just going to be a bit trickier to implement though.

For PD, I think the main question is what slot they would go into. Personally, I think weapon makes the most sense, especially if it also targets small ships. However, I can also imagine it being put into utility.

**Comment by bobbens** [comment]
Follow-up. Back in the day, what we had was that when a missile was "jammed" it had several different behaviours, randomly chosen:
1. It would just blow up.
2. It would stop turning and behave like a rocket.
3. It would randomly turn in one direction so that it would just circle around.

We could reimplement those behaviours plus add some other one like:
1. Missile is randomly slowed by 50% to 100%.

**Comment by Lineth** [comment]
> The only downside I can see of moving lock-on from ship to missile itself is that it won't be as easy to understand to the player, especially if electronic warfare stuff affects. I guess you could make an icon to indicate how many seconds it takes or something, but it might be a bit confusing. It might be easier to just keep the lock-on mechanic and make it significantly faster for missiles (1 to 3 secs), while keeping it somewhat delayed for torpedoes (5 to 8 secs).
> 
> If we do switch to making missiles lock-on after launch, how much time should it take for missiles vs torpedoes? How would ewarfare affect? Currently it is possible to have launchers that can literally not lock onto small ships, and it might be frustrating to the player if that happens without knowing. On the other hand, you could use Imperators as unguided rockets to one-hit small ships :D
> 

I see missiles attempting to lock on as using the hail graphic over themselves, mostly. Small missiles would only need 1~3 seconds to lock. Torpedoes would be 5~8. So your recommended lock-on times with instant unguided launch, basically. Just an idea, not really serious.

And I love the idea of using missiles as ad-hoc unguided rockets. Obliterating a pirate hyena with an imperator may not be practical, but it would be _very_ funny. And it could make missile turrets much more pleasant to use without hopefully being overpowered. Inefficient rocket turrets at short range, efficient missile turrets at long range.

> How would the fail thing work? How would we convey to a player?
> 
> There's multiple options:
> 
> 1. Have jammer chance and resistance chance be separate rolls. Roll first for jamming, if it would be jammed, you then roll for resistance and in the case that fails it gets jammed. This would mean that all weapons could be potentially jammed. Likely would have something like jammers with 30% chance and torpedoes have 80% resistance or something like that, leading to only 6% effective jamming chance.
> 2. Have jam chance be computed as `jamming - resistance`. So a 30% jamming weapon would never be able to jam a 40% resistance weapon. However a 40% jamming weapon would have a 10% chance of jamming a 30% resistance weapon.
> 
> Checks could also be done in at least two ways:
> 
> 1. The check would be done once per missile at a certain distance. This is probably best.
> 2. It would be normalized so it is computed once per second or once per XXX seconds. Would be harder to visualize to the player and would make it so slow missiles get many more checks.

Honestly, not much for me to say here. You have a much better grasp of the math behind implementing than I do. I'd say a jamming check every few seconds (depending on the jammer; I advocate adding more, perhaps unique ones for certain factions like Empire or Za'lek). Maybe a sort of pulsing effect on missiles in range of the jammer (if jammers have an effective range)?

> I like the idea of giving missiles health and maybe some dodging chance for PD. That way it would naturally work with small fighters and the like. It is just going to be a bit trickier to implement though.
> 
> For PD, I think the main question is what slot they would go into. Personally, I think weapon makes the most sense, especially if it also targets small ships. However, I can also imagine it being put into utility.
Both are good, but I have a harder time filling utility slots than weapon slots, so a PD would work there. Weapon slots are kinda crowded and overwhelming as it is (unless we advocate adding a slot to every heavy warship along with PD weapon implementation to lighten the overload.

> Follow-up. Back in the day, what we had was that when a missile was "jammed" it had several different behaviours, randomly chosen:
> 
> 1. It would just blow up.
> 2. It would stop turning and behave like a rocket.
> 3. It would randomly turn in one direction so that it would just circle around.
> 
> We could reimplement those behaviours plus add some other one like:
> 
> 1. Missile is randomly slowed by 50% to 100%.

I like the 'slow and meanders around' for jammed torpedoes. makes them still dangerous-ish when spammed (like pirates do now). but I also see the appeal of them just acting like rockets. I'm not a fan of them just blowing up. Feels too much like an overnerf and kinda headscratchery IMO

**Comment by bobbens** [comment]
OK, so I've implemented it. How it works is the following:

1. Jam chance is `jam_chance - rocket_resist`, if less than 0. it is impossible to jam.
2. If it is possible to jam, the weapon will do a jam check when under `distance / target_evasion`
3. If the missile succeeds the jam check, it will never be jammed and it continues
4. If the missile is jammed then one of 3 things happen (they will also hit any hostile ship, not just the target):
   1. The missile is slowed by 50% to 100% (100% would mean immobile)
   2. The missile stops turning and accelerates straight.
   3. The missile either turns hard right or hard left and loops

I've retweaked the outfits so that:

1. Only 1 scrambler and 1 jammer per ship
2. Milspec stuff is medium size
3. Scramblers / jammers give jam chance plus some evasion
4. Jam resistance is not limited to 0 to 100%, you can go over 100%

So I guess this is working. Only need to do minor things like make it more clear that stuff has been jammed and the likes. Any feedback is welcome.
