### ISSUE TITLE
Chealsea seems wasted

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1877]
On the waste run to Possum ("Waste Collector" / "Garbage Person")", Chelsea fails to enter Hyperspace and instead moves around on random lanes.

**Comment by amylaar** [comment]
It turns out that the mission can't work because the commodity "Waste Containers" has been discontinued.
Nobody really sees what's on the ship, except taht it has to have the right weight.
Plausibly, carbon can be considered waste when you want to cool a planet, so we can use diamonds, which are
needed for the convoy escort missions too, so should be less likely to be eliminated unless there's a dynamic substitute too.
It's debatable if diamonds smell, but maybe these are blood diamonds too so they smell in a methaphorical sense.
[waste-diff.txt](https://github.com/naev/naev/files/6886972/waste-diff.txt)

**Comment by UncombedCoconut** [comment]
Thanks for the patch. There's actually a dynamic cargo setup allowing the waste containers to be waste containers; we'll use that. (Looks like this mission was incompletely switched over to it, from the older method of putting every little thing in commodity.xml.)
I'll leave the issue open because I haven't looked at the AI behavior piece.

**Comment by amylaar** [comment]
I've been looking at rge dynamic cargo setup, but as far as I can tell, it can so far only be used on the player itself, not on any NPCs.

The AI didn't work because the error while spawning Chelsea's ship stopped necessary initializations from being done.

**Comment by bobbens** [comment]
Looks like it's fixed. Closing, thanks!
