### ISSUE TITLE
[Proposal] Player fleets

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1886]
OK, so to start out player fleets are probably one of the most requested features. With that in mind and based on previous discussions in #1224 and #832. I would like to discuss more on the possibility of player fleets (and what to do in the case we don't go down that route).

## Motivation
1. Fleets play a dominant role in Naev. Ships are rarely alone. If the player is alone, they will always be at a disadvantage with respect to existing NPC. Fleets can counteract this.
2. Fleets can help compensate ship weaknesses and currently play a dominant role in supporting larger ships. It is fairly hard to fly around in a Goddard as smaller ships pelt you, but the moment you have two hyena fighter docks, it is much easier to handle random encounters. If player fleets aren't provided, fighter bays basically become an essential outfit on any capital ship, and smaller ships become useless when attacking enemy fleets.
3. Fleets also allow for another venue of game progression or player growth. Having to equip and deal with more ships makes it harder for progression to stagnate.

## Main Issues
1. Fleets open up the potential for balance issues. If the player can accumulate or bring along ships to any mission, they can easily overcome any challenges missions through at them. Forcing mission developers to handle all this can lead to much higher development cost for missions.
2. Assuming the player is not alone does make mission development harder. From simple things to `pilot.attack()` ignoring escorts to more complicated issues like how to write the dialogues to handle the case the player is not alone. Mission development overhead in Naev is fairly high and adding more is a very bad thing.
   - I note that this is already an issue with fighter bays that needs addressing
3. Additional complexity. Having to handle equipping different ships and controlling / ordering pilots around can make everything much more complicated.
   - This too is already an issue with fighter bays to some extent.

## Proposal
This is similar to what I mentioned in #832, but the idea basically to tie fleet to `fleet capacity` values which would be increased as game progresses. The core idea would be to:
1. Each ship gets a strength value (this would also benefit spawning scripts, and be independent of outfits for simplicity)
2. The player gets a `fleet capacity` value which limits how big of a fleet they can have
   - Each ship the player has adds to `used fleet capacity`
   - They player can not deploy ships that push the `used fleet capacity` over maximum
   - The player's own ship counts towards `used fleet capacity`, however, if it is the only ship in the fleet, it can go over it. So a player could fly any ship by themselves, but not use escorts if it goes over `fleet capacity`
3. Fleet ships respawn when the player lands at a planet (maybe limited to planets with shipyards). No need to worry about ship permanent death and other horrible micro-management.
4. Add a Lua library to handle mission ship spawning. It would be able to increase or modify the number of ships to match the player fleet. Something like `function balance.spawnFleet( {table of ship names}, target_relative_strength, parameters )`. It would allow:
   - Trying to meet a target relative `fleet capacity` value. So if you set a value of 1.2 it tries to spawn fleet with `fleet capacity` at 1.2 the player's value.
   - Maximum / minimums could be set so that it doesn't go overboard
   - It could be designed to only either downscale or upscale (scaling could also be disabled maybe if the player dislikes it)
5. Write all the text assuming the player is alone (don't mention their fleet). This wouldn't change anything to what we are doing now.
6. `fleet capacity` would be set to 0 at the start of the game. Once the player reaches chapter 1 (hypergates are enabled), the player would unlock `fleet capacity`
   - `fleet capacity` increases as the player does missions, similar to faction caps
   - Missions that appear from chapter 1 onwards should assume the player has fleets
7. Player fleets should always be somewhat modest. No player having 5 goddards + 10 lancelots out and just destroying everything
8. Missions could temporarily disable fleets, but they would be allowed unless specified
9. Player would be able to equip each fleet ship individually
   - auto-equip would be provided (should be trivial to do now with `equipopt`)

### Notes
1. Maybe it should be enforced that the player has to fly the ship with highest strength

## Alternatives
1. Make the player become much stronger than NPC. If the player can get ships and/or outfits that are stronger than NPC defaults, they will be able to compensate the ship deficiency.
   - This has other balance issues and doesn't solve the fact that battleships without fighters are a bit annoying to fly around normally.
2. Decrease the amount of fleets and ships throughout the game to lower the player number disadvantage. This would allow the player to enjoy stuff without feeling overwhelmed.
   - This does have a downside that, if the player doesn't really get stronger over time, gameplay might stagnate fairly early.
3. Don't really do anything and assume the player is going to always be the underdog.
   - I note that one of the most common bad reviews on steam is that the game is too hard and it's impossible to beat the NPCs due to their number.

## Discussion
I think the heart of the question is what do we expect the player to be doing end-game-ish? When (dependent on campaign of course) they are facing hordes of Proteron invading and lots of open combat in a universe that gets more violent as it unravels into chaos, should the player also be stronger to be able to handle battleships and some enemy fleets, or are they destined to run away and only engage in small skirmishes except when missions allow it?

Personally, I do imagine that an end-game player would have lots of unique outfits (and maybe even ships), giving them a significant advantage over NPCs (however NPCs compensate in number), while also having some escorts allowing them to attack and deal with challenges that would have been unthinkable at early game when the player neither has special gear nor any escorts. This sort of progression would likely give players satisfaction. Missions would also ramp up in difficulty, so while "boss" fighters early on might consist of a Kestrel or a Goddard, late game they would be taking down fleets of multiple battleships and carriers and causing lots of mayhem. However, in the big picture of things, the player's fleets would still be too small to actually engage in things like destroying stations or taking over planets.

That said, not doing fleets has the advantage of not requiring large engine changes, more straight-forward and simple gameplay, and less mission development woes.

## Example of Potential Progression
Below illustrates an example of potential player fleets though-out the game (numbers are just made up for the example, and this is by no means definite, just a random idea):

0. Chapter 0: early game (think tutorial)
   - No fleets, so the player flies whatever ship they want. Just like the game now.
1. Chapter 1: not committed to a faction
   - `fleet capacity = 100ish`
   - cruiser or larger (player, 100ish, alone)
   - destroyer (player, 50ish), corvette (30ish), 2x interceptors (10ish)
   - corvette (player, 30ish), 2x corvette (30ish), interceptor (10ish)
   - fighter (player, 20ish), 2x fighter (20ish), 4x interceptor (10ish)
2. Chapter 2: commits to a faction
   - `fleet capacity = 200ish`
   - cruiser (player, 100ish), 2x corvette (30ish), 2x bomber (20ish)
   - battleship (player, 180ish), 2x interceptor (10ish)
   - destroyer (player, 50ish), destroyer (50ish), 2x corvette (20ish), 2x bomber (20ish)
3. Chapter 3: end-game
   - `fleet capacity = 300ish`
   - battleship (player, 180ish), destroyer (50ish), corvette (30ish), 4x interceptor (10ish)
   - carrier (player, 180ish), 1x cruiser (100ish), 1x bomber (20ish)
 4. Post-game
    - `fleet capacity = 500ish?`
    - battleship (player, 180ish), carrier (180ish), 2x destroyer (50ish), 4x interceptor (10ish)

**Comment by PhoenixRiver** [comment]
A couple of things I'd like to throw into the mix...

If player fleets are done I would suggest that all currently missions
be edited to disable fleets in them until they are vetted as being
able to cope.

"Respawning" player fleet ships should be a player choice since it'll
cost them to replace the ship, no? If players don't have to pay for
replacement ships then player fleets are overpowered since there is no
risk to the player, only advantage.

This "fleet capacity" idea could instead be used to measure single
ship strength alone and scale the presence of other ships based on
that combined with what type of ship a player is flying moderating how
aggressive NPC ships are... a trader player should expect to be
attacked more than a player flying a carrier but a carrier is more
dangerous so should face more ships (even if they are less aggressive
when the player jumps in... that's not to say they won't use any
excuse to attack a powereful player enmass). This could be used to
create a difficulty curve... it may or may not be based on every
ship/item a player owns - players with a choice of ship have a greater
advantage than players without after all and have probably played the
game more and to a higher level.

My own personal opinion is that player fleets are overrated and
Endless Sky is a perfect demonstration of the way it destorys any
interest in the end game as far as I am concerned - particularly with
an in developement game. I have not touched Endless Sky for years
despite major developments I know have happened because I have a save
that has a fleet so large as to crush everything that exists - it was
kinda stupid I couldn't invade planets my fleet was so big, and I
should note that it was almost exclusively low level traders... it was
also standard operating procedure for players of the game at the time
to complete the game as was as quickly as possible.
To summerise: there was no end game to Endless Sky because the player
fleet was potentially insane, there was no middle game because the
player traded to the most powerful ships in the game with low end
traders that then made the middle game easy and the early game
specifically trained the player how to trade with low level ships and
break the game... player fleets have to be handled _very_ carefully
and finding how to min/max it has already been done by fans of this
genre so anything NAEV does must account for that, at a minimum,
unless interest in the game should entirely be lost.
(Yes, I could play the game through from the beginning again rather
than use my save but, as explained, there is no reason not to break it
in the same way again unless they have utterly changed how fleets
work; and the rest of the game, works).

I _like_ that it is one ship against the world, NAEV (like the
originals) is not meant to be a power fantasy until, maybe, the very
end of the game and even then only through player choice... it is
supposed to be hard to take on all comers but maybe the all comers
should have a little more sense and not find weak players worth
killing (if for nothing else than the waste of time and resources to
them). I find it similar to Elite in this vain; a player can always
attack other single ships but to take on a space station worth of
police ships is something only a prepared Elite player with lots of
experience can do and then only with some luck or a good degree of
skill. If players want a power fantasy most of the games on the market
currently already have that in spades. I prefer the more thoughtful
and careful approach (though we can always improve on that of course,
NAEV isn't perfect, it's just what we're striving for :)

Maybe another thought that might give people more sense of power is
the possibility of creating a colony or station, they have the power
that comes with such a thing but not the ability to run rampant
thorugh the galaxy with it... clearly this would require a great deal
of resources, either at once (capital costs) and over time
(maintenance), and maybe in this way players could feel like they have
a better chance, at least in their own neighbourhood since they could
have access to NPCs who are part of their faction?

I feel like one of the main issues is that players are not encouraged
to make enough friends... one of my major issues is that I find few
ships to fight since I try to be friends with as many factions as
possible... maybe I'm just weird! (But I definitely don't have a
problem with it being too hard, the opposite really, I come to NAEV
from Elite to get a break from being attacked and dying so much! ;)

Just my thoughts,

Phoenix

**Comment by bobbens** [comment]
> "Respawning" player fleet ships should be a player choice since it'll cost them to replace the ship, no? If players don't have to pay for replacement ships then player fleets are overpowered since there is no risk to the player, only advantage.

That is sort of the point. Maybe it could be possible to add some maintenance costs or something, but the idea is that `fleet capacity` balances fleet usage, not economy. Having them respawn, just like missiles / fighter bays, reduces micro-management and keeps things simple.

> My own personal opinion is that player fleets are overrated and Endless Sky is a perfect demonstration of the way it destorys any interest in the end game as far as I am concerned - particularly with an in developement game.

My understanding is that ES tries to balance fleets with economy, which is very different to this proposal. In my example, fleets would be fairly small throughout the game. You wouldn't be able to farm up a big fleet and just stomp everything.

> I _like_ that it is one ship against the world, NAEV (like the originals) is not meant to be a power fantasy until, ...

Original EV very much had a power curve where the player would really soon start out-classing NPCs by a lot. There were some permanent ship upgrades that would increase thrust / speed / turn by a ton, and all other outfits to increase health and the likes way past generic NPC. These could also be acquired fairly soon. Furthermore, the equipment on almost all NPC was really sub-par. Current Naev doesn't really have this. Except for the `accessory` slot, and some minor limitations on NPC outfits, the NPC  usually are equipped as good as the player can be. There is a much much smaller gap between the player and generic NPC than similar games at the moment, which I believe is an issue when combined with the fact that the NPC do get fleets.

To make myself clear, I don't think an end-game player should be able to take out Kestrels in a Hyena, but I do think that they should be able to take a Kestrel-based fleet in a light destroyer.

The main reason I see fleets as something important is that, as mentioned in the proposal above,
1. Large ships (cruisers, battleships), are very niche-usage due to not having support unless you use fighter bays (which act sort of as a fleet).
2. Smallest ships become fairly useless as player's main ship, unless doing stealth or very specific missions.
3. Most NPCs are in fleets, making it so the player is always at a extreme disadvantage.

The way the game has evolved has basically pushed the player to be in a position where you have to run more often than not, and still have a high chance of getting killed. Fleets is one way of compensating. Others being letting the player get much stronger than NPC, reducing the fleet usage by NPCs, and/or point defense systems.

**Comment by PhoenixRiver** [comment]
> That is sort of the point. Maybe it could be possible to add some
> maintenance costs or something, but the idea is that `fleet capacity`
> balances fleet usage, not economy. Having them respawn, just like missiles /
> fighter bays, reduces micro-management and keeps things simple.

I don't feel having a "Do you want to pay to respawn this ship at a
local shipyard?" question to answer is much in the way of
micro-management and also makes it easier in some ways since maybe
that ship wasn't up to scratch and the player wants to replace it
anyway... auto-respawning ships assumes the player always wants every
ship in their fleet forever... not a good assumption in my minor
opinion.

> My understanding is that ES tries to balance fleets with economy, which is
> very different to this proposal. In my example, fleets would be fairly small
> throughout the game. You wouldn't be able to farm up a big fleet and just
> stomp everything.

You don't need to stomp every ship/fleet with your fleet... in fact in
ES the best way was to stomp the economy by having a huge cargo fleet
which allowed you to own the game... if your fleet capacity system
involves only curbing combat fleets then the lesson ES taught is
missed, you don't need to stomp other ships if you can stomp the
economy and for that you need cargo space which a fleet will always
provide more of...

And, side note, which also means any dynamic economy system will be
more unstable due to the player having greater ability to unbalance
it.

> Original EV very much had a power curve where the player would really soon
> start out-classing NPCs by a lot.

Clearly I didn't talk to other players enough since I was always (and
always am) trade heavy in these games and so my power level took
rather longer to outstrip NPCs.

> 1. Large ships (cruisers, battleships), are very niche-usage due to not
> having support unless you use fighter bays (which act sort of as a fleet).

Can I propose boosting turrets then? I always feel turrets are
underpowered compared to main guns because of the theory that you can
make main guns more simply and so they should be more powerful in the
same space BUT lasers reflect off mirrors, right? So a rotating mirror
can turn a straight laser into a turret laser with almost no extra
gear at all! Rail guns use magnets and magnets can curve paths (and
they're slow firing anyway so the extra time is less an issue) Plasma
launchers use (I'd imagine given that's how we make plasama these
days) torii of spinning plasma so turning that from firing in only one
direction to firing in any is pretty simple... also magnets again,
that suggests you could double up a rail gun turret and plasma turret
in the same place;

Sudden thought... how about splitting weapons in large ships into
generator and emission system; the generator creates the type of
weapon, e.g. plasma, high speed magnetic projectile, laser, missile,
and the emission system is what directs it; e.g. no emission system
fires the projectile straight ahead (though I guess homing missiles do
their own thing), a turret can redirect the "projectile" - maybe have
different sorts to deal with different projectiles; magnetic, mirror -
a spreader creates a shotgun effect (reduces range/power but increase
chances of a hit), a spreader turret.
[EDIT: an emission system to turn the projectile into a point defence
system that hits multiple targets, maybe similar to the spreader but
for even smaller targets (though maybe still the smallest ships) would
help appaarently. On top of that the generators could have a max
capacity for creating projectiles and emitters a max for emitting them
but you could reduce the number they fire by having multiple emitters
(maybe different types) tied to one generator or even multiple
generators tied to multiple emitters (e.g. a magnet turret that
alternates between railgun and plasma projectiles, this might well
cause the turret to fire at it's maximum rate even if the generators
were each not capable of supplying the turret on their own.]

From a player perspective they would set up their firing system and
tie it to one or two fire keys (e.g. primary fire, secondary fire) so
that in battle they would fire a predefined but mutable firing pattern
depending on how they set it up. This of course could be limited as
desired by the ships setup.

There is also the issue of freindly fire... do fleets have it turned
on or off, I assume off, but friendly blast radius could be an
intereting compromise that might take the edge off the effectiveness
of missile fleets and require a little more dogfighting rather than
fire and forget fleets.

> 2. Smallest ships become fairly useless as player's main ship, unless doing
> stealth or very specific missions.

Now I'm confused, are we trying to make small ships more survivable in
big fights? When has that ever been a thing unless they stealthed? If
we do this then why have different sizes of ship? If everything is
equally survivable in every role why bother having different sizes of
ship or even different ships... just go with more options of equipping
one standard ship... (I don't think we should I'm just questioning why
small ships should do things that physics and reality havealways said
is just not a thing.

> 3. Most NPCs are in fleets, making it so the player is always at a extreme
> disadvantage.

Okay, I presume that this is considered the real problem here. In that
case make aggressive fleets less dangerous, but bare in mind that this
is a player difficulty issue. Maybe we need a difficulty setting that
scales how hard the game is generally and that that changes how big,
dangerous, aggressive fleets are and how much of a disadvantage the
player is at... in could even include stopping the AI from using
certain types of weapons in their ships or capping their speed or turn
rates... but making the player more powerful is only one of many
things that can address " the player is at a disadvantage" and making
them stronger will impact every other system in the game, changing
many of the other systems will only impact that or a few other
systems... and so is much less likely to cause unintended
consequences.

> The way the game has evolved has basically pushed the player to be in a
> position where you have to run more often than not, and still have a high
> chance of getting killed. Fleets is one way of compensating. Others being
> letting the player get much stronger than NPC, reducing the fleet usage by
> NPCs, and/or point defense systems.

I thought we still had point defense systems... apparently I need to
replay that style of play again... I'd have thought it was a given
that battleships have these systems... if not then that needs to be
added ASAP in my opinion! Apologies for my bluntness here but I can't
imagine a battleship without point defenses!

Still not a fan of fleets without a lot of limitations on the economic
side and I can see numerous improvements without fleets that could
improve the players standing without the need for something that could
be as game-breaking as a dynamic ecnomic model that is not extremely
well thought-through... and, as I remember, we still don't have a full
economic model...

Anyway, I'm adding a lot here and hogging bandwidth... whatever
happens I hope some of the points I've made are useful in creating a
more refined system that improves the player experience (as long as it
doesn't push NAEV towards that lowest common denominator... it's so
hard to find games that don't cater primarily to that :(

All the best and if there are any specific points about my ideas or
points you'd like to discuss with me I'm happy to address them, I just
don't want to be the squeeky wheel when everyone else thinks I'm the
one bad apple.

Phoenix

**Comment by bobbens** [comment]
> I don't feel having a "Do you want to pay to respawn this ship at a local shipyard?" question to answer is much in the way of micro-management and also makes it easier in some ways since maybe that ship wasn't up to scratch and the player wants to replace it anyway... auto-respawning ships assumes the player always wants every ship in their fleet forever... not a good assumption in my minor opinion.

It's a bit tricky because what to do if the ship is a rare ship not sold at the planet? What about outfits? You could just ignore that and let the player pay for a new one, but if they have to pay the full price every time, that could mean costing 10+ million credits easily. This would make it so the player would have to grind to be able to use fleets, or just assume they aren't using them. If fleets get implemented there would be a fleet manager so the player could choose what ships to bring and the likes.

>  Sudden thought... how about splitting weapons in large ships into generator and emission system...

Does seem like a lot of added complexity that I'm not sure brings an equal amount of benefit.

> Now I'm confused, are we trying to make small ships more survivable in big fights? When has that ever been a thing unless they stealthed? If we do this then why have different sizes of ship? If everything is equally survivable in every role why bother having different sizes of ship or even different ships... just go with more options of equipping one standard ship... (I don't think we should I'm just questioning why small ships should do things that physics and reality have always said is just not a thing.

I'm not saying small ships should be survivable in big fights by themselves. If you only have a single ship, basically that will determine what you can handle in a fight. So if you want to attack a destroyer or larger, you'll probably need at least a corvette. That means that fighters/interceptors would only make sense when engaging corvettes or smaller (less when factoring fleets). If for a given `fleet capacity` you can say "do I want to fly a cruiser? or do I want to fly a fighter with 4 fighter escorts?" you are then able to use fighters to engage in larger battles. Of course, you won't be able to take down a battleship with 10 fighters, but you may with 4 fighters and 6 bombers. Basically, fleets enable smaller craft to be used in other scenarios rather than pure stealth / speed by the player.

I feel that with the current game state, it really encourages use of medium ships: corvettes and destroyers. They are fast enough to avoid most dangers, while being strong enough to take down most mission encounters fine. If you go with fighters or smaller, you lose critical firepower, making them useless in most situations other than running away, while larger ships tend to be ground down by smaller ships since they can't really flee/hide and don't have enough support to survive things like enemy bombers. Fleets would be able to make gangs of fighter a viable alternative, and also larger ships by providing proper support. At the end, the player could try more play styles and ships, without feeling as limited by the circumstances.

> > 3. Most NPCs are in fleets, making it so the player is always at a extreme  disadvantage.
>
> Okay, I presume that this is considered the real problem here. In that case make aggressive fleets less dangerous, but bare in mind that this is a player difficulty issue. Maybe we need a difficulty setting that scales how hard the game is generally and...

While difficulty modes are planned (should be an issue on that), I do think the game, as it currently is, is too disfavourable to the player. We should strive to have the game enjoyable as possible on a normal setting without having to rely on difficulty modes. I do feel like basically the situation winds up with two directions we can focus on, and I still think that fleets, if done right, would add a lot more to the game than take away from it. However, some things should also be possible with other directions.

Just to reiterate a bit:
1. I don't think fleets should be limited economically - that sort of defeats the purpose of having them as a core game element. Control should be done with `fleet capacity` or whatever you want to call it. Economical limits will likely encourage grinding, or, without some other limit, make it so you can trivialize specific encounters by bringing in a long of ships just for it.
2. Fleets should be fairly small. We're not talking about hordes of ships covering the horizon, but literally the player just dragging along a couple of extra ships. That should be enough to enable more play-styles and ship usage without creating major balance or GUI issues, and also be fairly in-line with most of the fleets the player will encounter in-game. If you look at my examples, the player is mainly limited to smallish fleets, with a single battleship/carrier plus support at end-game.
3. I do think it should be possible to do without fleets, but I do think game dynamics are currently basically pushing us towards fleets. If we want to do without them, I do think many things such as NPC fleets, NPC-gear, and player-specific gear have to be rethought of. I also feel that we would still have the issue that some ships will just not make much sense to be flown by the player late-game.

**Comment by V-ktor** [comment]
> You don't need to stomp every ship/fleet with your fleet... in fact in ES the best way was to stomp the economy by having a huge cargo fleet which allowed you to own the game... if your fleet capacity system involves only curbing combat fleets then the lesson ES taught is missed, you don't need to stomp other ships if you can stomp the economy and for that you need cargo space which a fleet will always provide more of... And, side note, which also means any dynamic economy system will be more unstable due to the player having greater ability to unbalance it.

That's actually an issue that an approach based on economy can't balance. More freighters will always make it more profitable, regardless of purely economic drawbacks of larger fleets. The fleet capacity can limit the maximum cargo space of the player.

**Comment by PhoenixRiver** [comment]
I feel like if the general theme of Naev is towards chaos then I expect that fleets would become less important, at least for everyone except the Proteon because in more chaotic situations it is harder to supply the logistics to create fleets. I would expect that ships would slowly adapt by bundling more weaponry and/or shielding and armour... maybe something that the varients proposal might be able to handle.
As for the PC, I feel like the option to have control over larger and larger ships is something already hinted at... it feels like the player has already played a decisive role in the FLF which suggests that they could become powerful enough in that role to pilot a miniture station carrier level of ship, ditto in the case of the Empire who have an enourmous ship under construction (and have had for many versions)... the Za'lek are just chaffing at the bit to be let loose on designing something insane with drones, ditto the Collective (or at least making use of their remains). The Dvaered with a megaship is just entirely natural and the structure of the Sirians could accomodate a station class ship with the ability to launch corvettes and the like.
My personal head-cannon that I don't have time to implement is that the Soromid are secretly working on miniture terraforming of small asteroids, mix that with their bioships and you have blue whale levels of carrier ship even potentially able to grow it's own fighters, never mind host destroyers or the like.

So, back to the fleet suggestion. We already have it with carriers and if the player is to survive they either have to run / sneak (my gameplay preference) or have something even bigger - shown to be a logical conclusion if the player follows the faction missions all the way to the top. So maybe what this needs is;
- a way for the player to switch to a ship that has been released from his carrier,
- a way for the player to be jumped either back to his carrier or to another nearby ship that was launched from his carrier,
- the use of fighter bays / docks being looked at in the same way fleet capacity is being, since they are essentially the same thing (as was previously mentioned).

Either way, in the end, I don't see the much increased complexity in writing content for the game as a good enough trade off for adding greater complexity to handling fleets (that are already, in effect, in the game from a combat perspective) and I certainly won't ever use them because I play for the single person in a ship making their way in life.

I feel like one of the (other) reasons that this keeps getting brought up (other than ES having it *sigh*) is because the combat aspect of this game slowly seems to be becoming the most polished and strongest facet, not because it is easy but because a good economy system is hard, so is a good stealth system (though that has improved, not that there is much point to it since you still can't use it to backstab a larger opponent before the fight has started, nor to transport contraband) and as for trade and exploration... trade has little to it with few goods and little rarity, nevermind contraband and exploration is hard without combat experience and ability (in the ship and player) or an extremely fast ship (where it is limited in its breadth to less busy neighbourhoods) but also because the galaxy is quite small.

But I feel a lot of these types of issues are related to the lack of balance as addressed in #2083 .

**Comment by bobbens** [comment]
> So, back to the fleet suggestion. We already have it with carriers and if the player is to survive they either have to run / sneak (my gameplay preference) or have something even bigger - shown to be a logical conclusion if the player follows the faction missions all the way to the top. So maybe what this needs is;
>     * a way for the player to switch to a ship that has been released from his carrier,
>     * a way for the player to be jumped either back to his carrier or to another nearby ship that was launched from his carrier,
>     * the use of fighter bays / docks being looked at in the same way fleet capacity is being, since they are essentially the same thing (as was previously mentioned).

I feel like this sort of misses the point of the PR. The idea is to allow the player to have fleets without having to rely on carriers. One of the main potential usage is for the player to get more out of their ships and especially smaller ships, like interceptors, fighters, and bombers that sort of lose their role in combat past a certain point. In particular, it would open up to other styles of game play like a stealth-ganking horde of fighters maybe lead by the player's corvette, or guerilla-style medium ships, or even just giving battleships a way to more reliable deal with enemy fighters and the likes, without having to rely on using carriers.

> Either way, in the end, I don't see the much increased complexity in writing content for the game as a good enough trade off for adding greater complexity to handling fleets (that are already, in effect, in the game from a combat perspective) and I certainly won't ever use them because I play for the single person in a ship making their way in life.

You would just write assuming the player is in a single ship. This doesn't add any complexity that doesn't exist with, for example, fighter bays and fighters, both from a writing perspective, and from a mission design perspective (if the AI only attacks the player's ship, they can exploit escorts).

The only potential downside I can imagine is that the game will potentially be harder for a player who doesn't want to use fleets ever. However, I do think that the current proposal doesn't really make the game impossible to play as a single ship given how small the fleets will be, with maybe 20 ships tops if the player only uses interceptors in the post-game, and much less most of the time.

**Comment by amylaar** [comment]
>     1. Large ships (cruisers, battleships), are very niche-usage due to not having support unless you use fighter bays (which act sort of as a fleet).

Large ships are unnaturally weak because you nerfed them with slowness and excessive mass growth.
A catamaran is not slower than two kayaks - to the contrary, it's larger size allows a more efficient propulsion system.  It can't turn as trivially if the wind isn't right, but you get a lot more speed over long distances.
That turrets turn slower than some ships can fly around you is also straining suspension of disbelief.  And when you look how
different size outfits like shield boosters and reactors scale in shield/power and performance/weight, the larger ships are again
at a disadvantage.  I understand this is there to avoid the big ships dominating everything (particularily with free fuel planetside), but if you are concerned that they are not attactive enough, you could just reduce the degree of big-ship-nerfing.
 
>     2. Smallest ships become fairly useless as player's main ship, unless doing stealth or very specific missions.

Huh, I travel most distance in a small ship (because the big ones are too slow).  If a bigger ship is needed, I figure out the most suitable shipyards to change.
  
>     3. Most NPCs are in fleets, making it so the player is always at a extreme disadvantage.

It's not them in fleets that makes it so that the player is at an extreme disadvantage.  It is them being in kamikaze fleets that single-mindedly want to destroy the player, ready to sacrifice scores of their ships (including crew) just to blow the player up.
If the opponents were more mindful of their own sacrifices, the fleets would often withdraw rather than press for a Pyrrhic victory.
 
> The way the game has evolved has basically pushed the player to be in a position where you have to run more often than not, and still have a high chance of getting killed. Fleets is one way of compensating. Others being letting the player get much stronger than NPC, reducing the fleet usage by NPCs, and/or point defense systems.

fleets of small ships are only so strong against big ships because the game mechanics made it so.  Now, if you were talking about huge fleets of small ships or big fleets of big ships, then the player would either have to run away or have their own fleet.

Talking about fleets the player has to face: every task and conflict is made harder by having to fight random pirates on top of doing the actual mission.  So you can be friendly with the pirates - but not if you are doing any ordinary missions.  You can pay of few of them off in a pinch, but it's not sustainable long-term even if you could afford the credits because of all the interaction.  So the pirates get either blown up, ignored, or they blow you up.  Or you abstain from most kinds of missions for long periods of time.  One way for the player to progress in power would be to find a way to pay protection money.  E.g. 10% of any gains in the pirate clan's claimed territory.  If they can know when you complete a mission, such an arrangement should be possible, and it would be a win-win.

Maybe some strong results at Totoran could bring a pirate at the negotiating table, or invite you to talk to a contact in Minerva or wherever.  The tax (protection money) rate might be negotiated and re-negotiated based on how strong you appear.

**Comment by amylaar** [comment]
> That's actually an issue that an approach based on economy can't balance. More freighters will always make it more profitable, regardless of purely economic drawbacks of larger fleets. The fleet capacity can limit the maximum cargo space of the player.

Politics can limit that.  What stops your pilots from taking off in your ships and never come back?  Or declaring themselves an independent republic?  You might pay them well, hire some watchmen... but who watches the watchers?  If your trade empire grows too much and you still try to hold control with an iron fist, you'll end up with another Empire with a lumbering bureaucracy, oppressive surveillance, a stifling atmosphere, and lots of strongmen that are just there to hold the power structure together.  At some point, you'll get less work done for your benefit if you add more freighters and people.

**Comment by bobbens** [comment]
A simple version has been implemented in main!
