### ISSUE TITLE
Tweaking SDF thresholds has opened Pandora's box.

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1893]
We have a commit, " Tweaked font rendering to work better with srgb."

https://github.com/naev/naev/commit/10ca4f1cf2f65979345cb2b5554a27a32170474c

I assume there's some situation it clearly improved, but things aren't universally better.

Here's a comparison of the Gamma Polaris overlay on both sides of the change, on my laptop (3200x1800 screen, 1.5x scaling).
The thinner outline makes it challenging to read.

![gp bad](https://user-images.githubusercontent.com/1224111/129490657-3dd52fc1-a87d-4a20-ad1f-0db929420148.png)
![gp good](https://user-images.githubusercontent.com/1224111/129490659-8383a946-3bb4-4408-a362-f3ed40266fb1.png)

I first noticed the problem on a machine that runs X11 at 1x. Everything looks worse without HiDPI, and this is no exception. Eyes would bleed if I uploaded that screenshot. :)

Since I'd probably appreciate the upside of the change given a better example, I'm not committing any changes for now.

**Comment by bobbens** [comment]
The main motivation with lowering thresholds was that with the linear colourspace change, basically everything has gotten thicker. So all the fonts + outlines looked very bold. I shrunk it a bit, and since there was some slight overlap with the outline, I probably decreased it more than before. It should be possible to increase it more, but I wanted to avoid doing the outline + glyph itself in two passes.

**Comment by bobbens** [comment]
I restored it partially, please see if it's ok.

**Comment by UncombedCoconut** [comment]
Yes, loads better -- legibility is fine on the 1x and 1.5x test displays. If it didn't worsen things from your viewpoint, we can close this!

**Comment by bobbens** [comment]
Yeah, the important part was tweaking `glyph_center`. Thanks!
