### ISSUE TITLE
The C and Lua formats may not be translatable into a language that has the different word order from English.

### ISSUE THREAD

**Issue by oo13** [naev/naev#1905]
The format should have the position directives, or "Fly to %s in the %s system" cannot be translated into Japanese.

**Comment by PhoenixRiver** [comment]
> The format should have the position directives, or "Fly to %s in the %s
> system" cannot be translated into Japanese.

I agree with the principle that this might be an issue in some cases
but in this particular case could you say "%sシステムの%sに飛ぶ"?

Phoenix

**Comment by oo13** [comment]
Japanese sentence for "Fly to %s in the %s system" is "{1:s}星系の{0:s}へ飛べ" in python format.

**Comment by bobbens** [comment]
OK, this might be a bit of a mess to do. Looking around, positional arguments are only specified by POSIX, we would have to  check to see if it works on windows too, and if not, use a library. Furthermore, Lua doesn't seem to support this out of the box, so we'll have to overload string.format, but I do think it should be possible.

**Comment by UncombedCoconut** [comment]
Lua explicitly removed support. (The 5.0 manual says "the format option %n$ is obsolete." Never mind that this use case requires it!)
I forget if I taught Weblate about this. Hopefully not, or it will recognize %n$ as invalid in lua-format translations.
The C side should be less of an issue, but I'm not sure if there's a consensus about best practices for MinGW-based projects.

**Comment by bobbens** [comment]
OK, I feel like the general consensus is to get Naev to understand `"%1$s"` and friends. That way, if you want to change the order you could do: `"%2$sの%1s%へ行け！"` in the translated string to get the order changed around Things to support this:
1. Get windows to understand `"%n$s"`
1. Get Lua to understand it (should be trivial by just overriding `string.format`)

**Comment by Zireael07** [comment]
Lua explicitly removing support for positional formatting is downright weird - as a translator I can tell you there are a literal ton of cases where it is required!

**Comment by PhoenixRiver** [comment]
Hello oo13,

Apologies I misunderstood the problem :(

Generally; I am kinda shocked that this was explicitly removed since I
can't imagine trying to do translations without it... I hope some of
the other projects I enjoy either don't use Lua or have thought about
this or else this could get messy fast (many of the are very popular
in Europe and Japan and word order in those two parts of the world are
about as diametrically opposed as they could be with the exception of
maybe (sometimes) adjectives... in some European languages, depending
on the adjective... yeah... languages are worse to deal with than time
when it comes to programming... and that is saying something! :P

I don't know if anyone is translating Naev into a Right-to-Left
language yet but that will also require this.

Incidentally does any know if a solution for Top-to-Bottom languages
exists? (Thankfully Japanese people can handle Left-to-Right as
well...)

Apologies and thank you for finding a solution :)

Phoenix

**Comment by UncombedCoconut** [comment]
We talked through it on Discord.
The gist of the plan is as follows:
- On the C side, translators may use %n$ directives. (For example, if the original text is "Fly to %s in the %s system", you can write "%1$s" wherever the planet name belongs and "%2$s" wherever the system name belongs.) If this breaks on Windows, we'll fix it.
- On the Lua side, we'll take the community's annoying advice and stop using string.format to format strings. We'll adopt a recipe along these lines: [lua-users wiki: String Interpolation](http://lua-users.org/wiki/StringInterpolation). We'll use a script to make sure existing code and translations are safely updated.

**Comment by bobbens** [comment]
Follow-up. The string interpolation has been implemented on the `presence` branch at the moment in the `scripts/format.lua` module (replaces `numstring.lua`). Needs regex-magic to convert`string.format` calls to use `fmt.f` for all the strings.

**Comment by UncombedCoconut** [comment]
Although classical Lua format strings aren't completely gone, I think there should be no further blockers of this kind.
Please let us know if you see any issues.
Sometime soon we'll probably standardize the `{variable_names}` a bit better, but it's mostly a small set of abbreviations already.
