### ISSUE TITLE
Lua loading optimizations

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1915]
[quoting from [Discord](https://discord.com/channels/661743268505190400/671163057161895947/891161375894802464)]
It would be cool to improve the Lua loading stuff. Things I can think of:
a) Have all the Lua include files compiled and stored as chunks in C. When a known require gets pulled in, just execute the chunk in the new env
b) Lazy load heavy Lua libraries

During some work I ended up loading heavy Lua libraries in all missions and this led to like 5 second landing time
by lazy loading it I was able to avoid it
(looking at you VN)

**Comment by bobbens** [comment]
Lua-side lazy loading is working on slow libraries and can be added as needed (there's no single one-fits all solution here).

For C-side, what would have to be done is modifying the Lua loader so that it first checks to see if the filename is in some array, if it is just run the chunks there, if not, load the chunks, save them, and run them. Should be fairly straight-forward and even be compatible with the lazy-loading. However, it does not replace lazy loading as the chunks might load data when run, which could add to long load times. Lazy loading defers that.

**Comment by UncombedCoconut** [comment]
(closed as duplicate of #1938 -- which explains the goal better)
