### ISSUE TITLE
Up button event toolkit mayhem

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1917]
If you open a new window on mouse down from a custom widget (like say the map custom widget triggers a hook when you select a hyperspace target that opens a custom dialogue), the custom widget gets stuck in the "mouse down" state, since the "mouse up" state gets eaten by the new window. I guess this can also affect other cases and potentially key presses, pretty much anything that has some sort of internal state tied to the down press.

Potential solution: store current down state for a window, and when creating a new window generate up states for the old window.

Another potential solution: always propagate up events to everything, although this will add more overhead.

**Comment by bobbens** [comment]
To point out how this is triggered, this happens in the nelly01 mission. In particular,
1. Open the info menu and go to the missions place
2. Click on the mission map to select the target destination as nelly tells you to
3. This triggers a small "congratulations" message with the VN
4. The "up mouse" event doesn't get propagated to the custom map widget, it gets "eaten" by the VN, so the custom map thinks it's dragged
5. Clicking again will solve the issue, but it's really weird that it is dragging.

**Comment by UncombedCoconut** [comment]
I'm thinking the best way might be to set `WGT_FLAG_CANFOCUS` on customs and propagate focusGain/focusLose events.
Drawbacks: code duplication gets even worse between mapedit/sysedit/uniedit/map/news, focusGain doesn't always happen when expected (by me anyway). Also, this isn't a building block for a state-tracking solution: by the time you handle focusLose, the current mouse state might differ from the state prior events reported to you.
Benefits: avoids the complications of faking SDL_Events, allows the widget to straightforwardly handle the exact thing that happened.

Always propagating up events is tempting, though, because it could be a lot simpler and it seems unlikely to go wrong.

**Comment by bobbens** [comment]
The focusGain/focusLose does seem like a potential solution, but I'm just worried that it'll be a mess to make sure the states are coherent. Always propagating up events does seem like a more one size fits all solution, and I can't really think of a drawback atm. However, I'm fine with any approach if it works :)
