### ISSUE TITLE
Include contributors artwork licenses

### ISSUE THREAD

**Issue by bobbens** [naev/naev#1932]
Contributors from `artwork/gfx/ARTWORK_LICENSE` and `artwork/snd/SOUND_LICENSE` should be parsed from the YAML and included in the in-game credits (appended to `dat/AUTHORS` somehow).

**Comment by UncombedCoconut** [comment]
I allege this is done. The script `utils/build/gen_authors.py` appends the detected authors to the `dat/AUTHORS` source file. [*]
Then we tell Meson to install the generated version (onto the machine or into the package/bundle/installer), which works, and shove it into a physfs layer for naev.sh, which also works.

[*] is the part that could (endlessly) be considered not-done due to untidy results. Where do we split lines which credit co-authors? What's a duplicate? Which version do we keep in case of duplicates? If we tweak that stuff, are we still catching sneaky cases like Ingo=Grumbel and Edgar=bobbens? Etc.

**Comment by bobbens** [comment]
Honestly, I think just a simple concatenation should be fine. As long as everyone is properly credited, I consider it sufficient. Merging authors is going to be fairly impossible due to many cases where files are modified from other versions leading to inconsistent author information, and it just doesn't seem worth the time trying to perfect it, given that it will still need to be endlessly maintained.

**Comment by UncombedCoconut** [comment]
OK, I'm going to close this and if necessary we can go back and delete all nontrivial logic from `utils/build/gen_authors.py`. (Just `yield credited_name` and simplify/eliminate `deduplicate()`, or even yield all the yaml file lines unmodified from `authors()`.)
I personally favor the dedpulication step, as it eliminates most of the clearly silly stuff.
