### ISSUE TITLE
save_updater changes for the next SemVer

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#2005]
Most important:
`dat/save_updater.lua` has a bunch of "Bioship" entries which are no longer helpful.
In case a player in possession of a bioship wants to continue their Naev <0.10 game, I'm very unsure what should happen. Maybe they can get refunded and there can be a way to reset to first-stage outfits?

Less important:
There may be some one-time-only outfit renames to handle, like the original "Thurion Perspicacity Fighter Bay". This is a case where outfit lookup by name would succeed, just not in the desired way.

**Comment by bobbens** [comment]
For bioships it would make sense to refund the outfits (or be mean and set them all to 0 price). From a look at the code, the bioships should then be automagically updated to use the system, so I don't think we have to do anything there. They will get their experience reset, but I don't think it's possible to move it over (since it's defined in outfits and not ships in 0.9.x)

**Comment by bobbens** [comment]
I've automated 0.8.x and 0.9.x bioship stuff and added it with the following script:
```sh
for FILE in bio*/*.xml; do
   name=`grep name=\" ${FILE}`
   name=${name%\">}
   name=${name#<outfit name=\"}

   price=`grep \<price\> ${FILE} | xargs`
   price=${price%<\/price>}
   price=${price#<price>}

   echo "   [\"${name}\"] = ${price},"
done
```
Are we missing anything still?

**Comment by bobbens** [comment]
I believe this issue is outdated. Closing.
