### ISSUE TITLE
Steam 0.9.2 Rhino engine...

### ISSUE THREAD

**Issue by PhoenixRiver** [naev/naev#2069]
Just a little thing... but maybe I can fix it or maybe it is part of a larger problem?

The Rhino's engine is nigh on unreplacable... I have a slightly smaller one in there now that can haul as much weight and weighs a touch less but it seems that these two engines are the only ones that a Rhino can use because it is at the top edge of the Medium Structure Engine size... the engine it comes with is even a special one since the standard Unicorp ones are not good enough!

Maybe we do need more cores after all?

**Comment by bobbens** [comment]
How many viable cores should each ship have? In general, most ships are designed with mainly one core in mind, while the player has a bit more flexibility pushing it in other directions, but in general the choices are fairly limited. Sure, you can equip an interceptor as one class up (fighter/bomber), or corvette as a destroyer, but it'll be worse than a higher class ship. Would it be beneficial to have more nuanced cores all over? I'm a bit broken on that because it will increase the number of outfits and complexity by a lot which may not compensate the gain gotten from them.

I would like to have like two different viable sets: high tech vs low tech for all ships, so that you can have more flexibility and choice (see the somewhat abandoned #2027 ), but it's not that simple to design a system that is a) somewhat balanced, and b) not too hard to understand for the player. I do think #2027 failed in that sense. I might give another try later, but it does seem a bit non-trivial.

Another point is I think it would be beneficial for NPC to have more "bad" outfits, so that they aren't all perfect killing machines. Increasing the price of the "good" outfits and adding an entire tier of basically objectively cheaper but worse outfits could be used for that. Using the rarity system we could have the bad ones be rarity 0, and have decent ones start at rarity 1 so we could add a filter to the outfitter (and equipment?) so that the player could ignore them easily.

I guess at the end of the day the main thing that we may have to think about before adding more outfits is how to improve the interface so that it's easier to handle when there are many outfits. The current filters are one step in that direction, but I think it may need a complete overhaul. I guess something like allowing hiding the player's ships and maximizing the outfits when doing equipment would be good. It would also be cool to allow the player to save, load, and compare outfit sets on ships, but that would be quite a lot more work.

**Comment by PhoenixRiver** [comment]
I guess I'm just feeling it on the Rhino because I can't seem to "upgrade" it since it already technically has the highest numbered outfit fitted when you buy it... the one I replaced it with only has the advantage of being lighter making a full freighter Rhino not slow down at all despite having three medium cargo pods and cargo armour and fully topped up iwth cargo (just). The default engine doesn't allow that along with turrets to defend yourself with wihtout stripping everything else to the bone (the 40t engine weight difference is how tight it is!)
I suppose it is also because I don't really know what else you might use a Rhino for other than cargo so buyiong it requires little work in upgrading it to get to it's "high_tech" state bu thten I suppose that migh tbe considered intentional given it is an early ship a lot of people will graduate to from the Llama or maybe Koala (as I did). Then again the Koala has much more leeway for builds.

I think I'm just being picky due to the Rhino constituting a quarter of my experience with the newest version of the game and the Gawain and Koala having more space to manouveur outfit-wise! Feel free to close as you feel appropriate not withstanding #2027.

**Comment by bobbens** [comment]
Well I think it is a valid concern. I do think we need a bit more diversity in core outfits and the likes. However, I believe it might be better to try to first stabilize the outfits before adding many variations and new ones (especially for cores/weapons/structurals, utilities are more tangential). That said, it would be important to jointly think of a high level way of doing high/low tech that works. It's a bit tricky since CPU is basically a hard limit (you only want to have just enough CPU and anything left over is "lost"), while energy/mass are soft limits (the lower the better, no hard limits). The advantage we have is that being a single-player game, we don't really need perfect balance, just something enjoyable. I'll keep this open until a more complete proposal or the likes appears.

**Comment by amylaar** [comment]
>   It's a bit tricky since CPU is basically a hard limit (you only want to have just enough CPU and anything left over is "lost"), while energy/mass are soft limits (the lower the better, no hard limits).

Actually, that's one bit that's unrealistic which I think would not be too much affecting the balance to fix, but would give more
options to push the limits with more active player engagement.
Why is there such a hard delineation between permanently active a activated outfits, and most systems are permanently active?
Realistically, you could have stealth systems that can be put to sleep when you are in a safe environment, or contrarily, if you are already blazing like a small star and don't care about stealth.  If you are in a medium-to-long range exchange of missiles, why do all the short-range weapons systems continue to suck CPU?  Or if you want to capture somebody and don't use and destruction-oriented systems?  You don't want to deploy the escorts you carry because they have no sense of holding back
if you are presence of a faction that is hostile but that you want to appease / make friends with?  It would make sense if you could set cpu priority lists which outfits get to use the CPU and switch them around as situations change.  Also, a lot of systems could plausibly work at degraded performance if they get less then their full allotment of CPU.
I suppose the main problem is that it's take a lot of attention to detail to implement.

**Comment by bobbens** [comment]
> > It's a bit tricky since CPU is basically a hard limit (you only want to have just enough CPU and anything left over is "lost"), while energy/mass are soft limits (the lower the better, no hard limits).
> 
> Actually, that's one bit that's unrealistic which I think would not be too much affecting the balance to fix, but would give more options to push the limits with more active player engagement. Why is there such a hard delineation between permanently active a activated outfits, and most systems are permanently active? Realistically, you could have stealth systems that can be put to sleep when you are in a safe environment, or contrarily, if you are already blazing like a small star and don't care about stealth. If you are in a medium-to-long range exchange of missiles, why do all the short-range weapons systems continue to suck CPU? Or if you want to capture somebody and don't use and destruction-oriented systems? You don't want to deploy the escorts you carry because they have no sense of holding back if you are presence of a faction that is hostile but that you want to appease / make friends with? It would make sense if you could set cpu priority lists which outfits get to use the CPU and switch them around as situations change. Also, a lot of systems could plausibly work at degraded performance if they get less then their full allotment of CPU. I suppose the main problem is that it's take a lot of attention to detail to implement.

Honestly, I think it would be a lot of complexity for little to no gain, plus the potential to make balance even wonkier than it is. I don't really see any clear benefit for the player from a gameplay experience point of view. Having CPU as some sort of hard limit game mechanic as we have now feels like the best approach.

**Comment by PhoenixRiver** [comment]
> Honestly, I think it would be a lot of complexity for little to no gain, plus the potential to make balance even wonkier than it is. I don't really see any clear benefit for the player from a gameplay experience point of view. Having CPU as some sort of hard limit game mechanic as we have now feels like the best approach.

If there is any interest in this idea then how about something a little more managable... say a mode setting that can switch between: normal, stealth, combat and it takes a few seconds to switch between (can't have it all be good).
Normal runs with all systems hot, combat turns off any stealth systems, stealth turns off combat AIs and weapons - running in stealth and combat means that energy load is potentially lower leaving more power for weapons and active outfits if necessary and CPU load is lower, producing less heat and therefore reducing radar / heat signature leading to lower detection and heat tracking for missiles...

Form the player perspective there is a trade off between being ready and having advantages and it would mean there is less of an absolute "must use all CPU" because lower CPU means less heat and so more stealth... this would also help give newer players who haven't the money to actually use all the CPU more stealth, as well as traders running with lower combat rated weapons because they need the space for cargo...

Just a thought. :)

**Comment by PhoenixRiver** [comment]
You've a good point there @bobbens, that is exactly what stealth mode does I guess but I feel like combat mode is a thing that is different too. There is no need for outfits like adaptive stealth plating and, maybe, the mining lasers... though if a ship has no other weapons... and that's as much as I can find... to be honest I think this speaks to the lack of more power hungry outfits that benefit things other than combat than the uselessness of a combat mode but having discovered the above, I concur with you @bobbens, there is no (current) need for a copmbat mode.

Now I'm trying to think of outfits that could be useful in non-combat situations, apologies!

**Comment by amylaar** [comment]
On Sun, 20 Mar 2022 at 08:04, PhoenixRiver ***@***.***> wrote:

> You've a good point there @bobbens <https://github.com/bobbens>, that is
> exactly what stealth mode does I guess but I feel like combat mode is a
> thing that is different too. There is no need for outfits like adaptive
> stealth plating and, maybe, the mining lasers... though if a ship has no
> other weapons... and that's as much as I can find... to be honest I think
> this speaks to the lack of more power hungry outfits that benefit things
> other than combat
>

That is not true.  The afterburner is extremely power hungry.  If you can
switch off the power consumption of your weapons system, you have a true
fight-or-flight decision.

**Comment by PhoenixRiver** [comment]
> That is not true. The afterburner is extremely power hungry. If you can switch off the power consumption of your weapons system, you have a true fight-or-flight decision.

I was under the impression that your weapons only consumed power when they were fired... if that is not the case when they are disabled then I would definitely agree with you that this is something that should be fixed for stealth mode - though using an afterburner should, of course, remove you from stealth mode; you might as well be a supernova for all the subtlety you have firing off an afterburner! :D *laugh* - I'd be tempted to see if I could also make a ship using afterburner immediately detected by all ships in the system and for a short while after stopping given the heat that would need to be disappated from using it... again another presumption here that there is also already a cooldown on afterburners... I don't use them (as yet) so I'm a bit out of my depth here! Apologies.

**Comment by amylaar** [comment]
> I'd be tempted to see if I could also make a ship using afterburner
immediately detected by all ships in the system and for a short while after
stopping given the heat that would need to be disappated from using it...
again another presumption here that there is also already a cooldown on
afterburners... I don't use them (as yet) so I'm a bit out of my depth
here! Apologies.

Actually, that would be a reason for a Mule or Rhino or Large Bulk
Freighter to equip an afterburner.  It might not help you much with escape
speed, but it'd be splendid as a distress signal.

**Comment by bobbens** [comment]
I think this should be solved with the new structural changes and the likes. If necessary, please open it again. Thanks!
