### ISSUE TITLE
Failure to compile due to libunibreak

### ISSUE THREAD

**Issue by l8gravely** [naev/naev#2148]
Hi,
I'm trying to compile Naev master on Linux Mint 20.3, but running into all kinds of problems.  Am I supposed to use the 'meson setup build' commands, or the 'autogen.sh' command to get stuff working?  

I've also checked out the v0.9.3 branch and tried compiling there, but I keep getting errors when running 'meson setup build' about libunibreak not found.  

`sail:~/src/Games/naev$ meson setup build
The Meson build system
Version: 0.53.2
Source dir: /home/john/src/Games/naev
Build dir: /home/john/src/Games/naev/build
Build type: native build
Project name: naev
Project version: 0.9.3
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
meson.build:14: WARNING: This version of Meson is nearly too old to work, but partially supported for subproject-free builds (e.g., for distro packages). In most cases you will need to upgrade Meson or use the included meson.sh wrapper script.
Compiler for C supports arguments -Wextra: YES 
meson.build:27: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C supports arguments -Wshadow: YES 
Program python3 found: YES (/usr/bin/python3)
Program python3 (yaml) found: YES (/usr/bin/python3) modules: yaml
Program python3 (mutagen) found: NO
Program build/gen_version.sh found: YES (/home/john/src/Games/naev/utils/build/gen_version.sh)
Program utils/build/add_to_package.sh found: YES (/home/john/src/Games/naev/utils/build/add_to_package.sh)
Program doxygen found: NO
Program dot found: YES (/usr/bin/dot)
Program ldoc found: NO
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency sdl2 found: YES 2.0.10
Run-time dependency sdl2_image found: YES 2.0.5
Dependency libunibreak found: NO found 1.1 but need: '>=4.0'
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency libunibreak found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libunibreak

meson.build:97:3: ERROR: Subproject exists but has no meson.build file

A full log can be found at /home/john/src/Games/naev/build/meson-logs/meson-log.txt

looking in .gitmodules, I don't see anything for libunibreak, even though I see discussions about version 4.3 in the commit messages.  I have libunibreak 1.1 installed, but it want's >=4.0, but the supposed submodule isn't setup properly.

**Comment by UncombedCoconut** [comment]
(replying from out of town, sorry for not being more detailed)
Hi, Meson is the right tool to use and overall steps are laid out in the Readme.md file. But the version you have installed, 0.53.2, is too old for most purposes. Can you try using the included meson.sh script in place of the regular "meson" command?

**Comment by l8gravely** [comment]
Thanks for the quick reply, but no script attached from what I see...  Looking over how the builds are done within docker, I'd be tempted to try and go that route, but I'm a debian guy and it looks like most development is on Steam or Fedora.  

Would it help to pull down a newer version of Meson?  So I just tried this with version 0.62.2 of meson, but no go.  I'm on the master branch.  So I switched over to the v0.9.3 branch, which has the meson.build file, but I run into the same issue with libunibreak not having a meson.build file.  

I was able to go into the subprojects/libunibreak/src and do the 'cp Makefile.gcc Makefile && make' to generate a library, but I suspect that's not quite enough.

I've also done the 'git submodule update' and 'git submodule status' to make sure that wasn't a problem, and those look all ok to my eye.

Dropping back to v0.8.2 seems to work better, I can at least do the setup and start a compile, we will see if it actually finishes properly or not.  




And once I get this working, I'll be happy to submit a pull request to update the Readme.md file to reflect reality better.  :-)

**Comment by UncombedCoconut** [comment]
Lots to unpack here!

- The "included meson.sh script" I mentioned is a file at the root of the naev repository. So an example command would be `./meson.sh setup build .` The job of meson.sh is to download a new version of Meson (when first run) and execute it.
- A newer Meson on your system would help too. 0.62.2 is what I use today. Basically 0.55 or newer is required to build without crazy hoop-jumping. We have _very limited_ support for 0.53 because it helped an openSUSE packager; it basically requires all the libs used by Naev to be installed on your system because nothing under subprojects/ will work.
- The git branches of interest are "main" (latest and greatest) and "0.9.x" (same as 0.9.3 tag plus minor fixes, so more finished/debugged). For best results, choose which of these you prefer and stick with it (and clean your source tree as much as possible). Both branches have all necessary `meson.build` files.
- Invoking makefiles under subprojects/ is counterproductive. Once you have a recent Meson working, you may want to get the subprojects/ subdirs back to a clean state, e.g. using `meson subprojects purge` from the source root.
- If all else fails, you should still be able to download and play: we offer AppImage builds at https://github.com/naev/naev/releases/, flatpack packages are available via flathub, and we have Linux builds on the Steam and itch.io app stores.

**Comment by bobbens** [comment]
Closing. Please reopen if it is still an issue, thanks!

**Comment by FedericoCeratto** [comment]
I'm seeing the same problem when building on Debian Unstable using meson 0.63.3 and unibreak 1.1

**Comment by UncombedCoconut** [comment]
> I'm seeing the same problem when building on Debian Unstable using meson 0.63.3 and unibreak 1.1

Sorry to hear that. That's a new enough Meson.
Does it help to pass `--force-fallback-for=libunibreak` as an argument to Meson?
If you're even getting the same "Subproject exists but has no meson.build file" error as in the OP, does it help to run (from your source dir) `meson subprojects purge` (and following that command's instructions)?

**Comment by bobbens** [comment]
> I'm seeing the same problem when building on Debian Unstable using meson 0.63.3 and unibreak 1.1

For Debian, there may be some developments as there is a high possibility 5.0 or 5.1 will be packaged in the near future.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003351

**Comment by bobbens** [comment]
libunibreak5 is in debian sid
https://packages.debian.org/sid/libunibreak5
This should fix the issue, although it will take a while until it reaches stable. Closing issue, thanks!
