### ISSUE TITLE
Installing Naev in MSYS2 on Windows does not work.

### ISSUE THREAD

**Issue by ProjectSynchro** [naev/naev#2163]
It appears that when installing Naev via `meson install` in MSYS2 `packageWindows.sh` does not run correctly citing that it does not exist when in fact it does.

Snippet from console:
```
--- stderr ---
/bin/bash: C:/msys64/home/jack/naev/extras/windows/packageWindows.sh: No such file or directory

FAILED: install script 'bash C:/msys64/home/jack/naev/extras/windows/packageWindows.sh -n false' exit code 127, stopped
```

While I think the overall goal should probably be to split up creating the installer from the default install process; this does still mean that the cause of this not working should be investigated.

**Comment by UncombedCoconut** [comment]
It looks like msys2 tools make paths (such as the first argument to `bash`, i.e., the script path) relative to the msys2 root, so that passing an absolute Windows path actually fails.
They talk a little bit about it here: https://www.msys2.org/docs/filesystem-paths/
I think the solution is... to give up programming and go pet a cat? Something like that.

**Comment by ProjectSynchro** [comment]
This seems resolved after the move to python for the `packageWindows.sh` script. 

Closing this.
