### ISSUE TITLE
We can land a planet without a spaceport.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2171]
Delta Polaris I has no spaceport, but I can land the planet. It ends up SIGSEGV (Japanese language) or creating a bad save file (English).

By the way, the default faction of a planet is Achack_sirius. I noticed the faction of Eiroik and Antlejos V at the beginning is Achack_sirius.  It's odd but no real problem.

**Comment by bobbens** [comment]
Thanks for the report! This is a set of 3 bugs that I've fixed in main:
1. Crash when landing on spob with no description when not using English.
2. Spobs defaulting to first faction (Achack_sirius)
3. The spob Lua "can_land" result being ignored by the autoland stuff.

My testing indicates that they are all fixed, thanks!
