### ISSUE TITLE
Too many logs "Texture '%s' has no transparency map".

### ISSUE THREAD

**Issue by oo13** [naev/naev#2175]
Too many logs "Texture '%s' has no transparency map" output to the console in the mission "Destroy the FLF base!", "Assault on Raelid", and "Assault on Haleb".

I use the debug build (meson compile && ./naev.sh) of the current main version (bd2998fae39767e6125d160c187b55f4a2ca60cb) of Naev and run it on Linux.

%s is one of ship name and said ship seems to be invincible.
Example in "Destroy the FLF base!":
Warning: [CollideSprite] Texture 'gfx/ship/vendetta/vendetta_dvaered.webp' has no transparency map
Warning: [CollideSprite] Texture 'gfx/ship/goddard/goddard_dvaered.webp' has no transparency map
Warning: [CollideSprite] Texture 'gfx/ship/vigilance/vigilance_dvaered.webp' has no transparency map

**Comment by bobbens** [comment]
It was two bugs (fixed in main):
1. Weapon collision code would do extra comparisons in pixel-perfect mode when collision polygons exist.
2. Textures loaded without transparency maps, then loaded with transparency maps would not actually load the transparency maps.

Now, there's still a potential issue, in that if a weapon without collision polygons exists, it will spam the warning on trying to collide stuff. We need to implement a polygon <-> pixel perfect collision routine to solve that. (this issue shouldn't exist in Naev currently, but could potentially happen with a plugin or something)

**Comment by bobbens** [comment]
Decided to revert the optimization seeing as we're caching the transparency maps anyways. Should fix all potential issues (and better than before!). Thanks again!
