### ISSUE TITLE
Pirates seem to stalk players through stealth

### ISSUE THREAD

**Issue by bobbens** [naev/naev#2218]
Not sure the cause, but LJ_Dude on discord reported that pirates stalk the player through stealth.

**Comment by LJDude** [comment]
Here are the two videos I recorded on this. The second one shows it a bit better. 

https://user-images.githubusercontent.com/38018891/197091459-2e208917-6145-4ccb-9857-c5fc49c05620.mp4
https://user-images.githubusercontent.com/38018891/197091418-69b14946-3dd7-43ce-a0a1-5d657fe3b7c1.mp4

Based on a recent conversation on discord, I think this issue can be applied to all enemy ships instead of just pirates or proteron like sigus#4715 was having issues with.

The enemy ships repeatedly turn exactly towards the player with no noticeable limit to the amount of turns. Before this issue showed up, I recall enemy ships doing the same thing, but it was limited to just one turn. 

That being said, I don't think an enemy ship should be turning towards the player in the first place. Stealth mode makes a ship invisible to all sensors, and I doubt that enemy ships have some sort of equipment (or superpowers) that can calculate/see the future of where the player will be.

I think that enemy ships should follow the player for a short bit after entering stealth, then afterwards just turn towards the nearest jump point or friendly base until it either finds the player or finds a new task, such as a patrol route to follow or another target to engage.

**Comment by bobbens** [comment]
OK, I've pushed what I believe is a definite fix for this. I'll keep it open a bit more just in case.

**Comment by bobbens** [comment]
I believe it is fixed.
