### ISSUE TITLE
very low prices for Thurion missions

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2311]
same thing as with FLF missions? Please see screenshot. It's a priority shipment, so shouldn't be that low, should it?
![Screenshot_20230328_200145](https://user-images.githubusercontent.com/122737685/228327872-541a4b23-cbf8-4578-b911-32575ad78cbc.png)

**Comment by bobbens** [comment]
The FLF mission was a bug in the computations. For the Thurion one, the issue is that the generic missions don't really work with them because they have no piracy and quite compact systems, so you can get small intra-system missions with really low payments. Down the line, the true "solution" is to give them their own set of missions. A potential fix would be to just filter the missions so that ones below a certain amount of payment don't get generated.
