### ISSUE TITLE
several (nearly) identical missions on offer (intended?)

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2316]
Please see the attached screenshot.
Missions: By accident there are 2 patrols of the Dune system and 3 convoys to Selphod. I doubt that these multiple (similar) instances are intended. 

A small general feedback besides that issue: great game, great stories/missions, great dialogues! You're doing a brilliant job! 
![Screenshot_20230403_152525](https://user-images.githubusercontent.com/122737685/229523250-63657bb3-d80c-4e9f-9933-c1ce637164b0.png)

**Comment by bobbens** [comment]
What's likely happening is that there are few potential targets for patrols or convoy escorting. So if it generates a patrol mission, it may only have 1 potential "valid" patrol route. Since the patrol missions are independent of each other, you'll get multiple patrol missions being generated exactly the same. I agree this is an issue, but the solution is a bit tricky, as we need to somehow have the missions understand the other generated missions and try to minimize overlap.

Possible solutions I can think of:
1) Extend the claim API to allow more fine-grained overlap detection so that you can have patrol missions not generate overlapping with each other.
2) Use the cache system to manage overlapping mission stuff to an extent. Would be a bit tricky, but should be possible with a high priority helper event to set up the cache (or just use some sort of spob-based indexing).
3) Relax the requirements for missions more so it is less likely that they overlap.

**Comment by bobbens** [comment]
OK, I've implemented solution 2. for cache-based checking. However, I only implemented it for patrol + trader escort missions at the moment. Do you think this should be implemented for other missions too?

**Comment by BM-W1** [comment]
I believe the restriction to patrol and trader escort missions should do it. That is fine. Actually, I cannot remember other cases where this popped up in a way that distorts the intentions of missions.

**Comment by bobbens** [comment]
OK, great! I'll close the issue then, thanks! If you see any other extreme case, it can be also added.
