### ISSUE TITLE
[Bug]: Autonav may cause an error in a system with no patrol lane.

### ISSUE THREAD

**Issue by oo13** [naev/naev#2354]
### What happened?

1. Check "Use patrol lanes when jumping" in Player Settings.
2. Enable autonav and fly to a system with no patrol lane.
3. Autonav is disabled and there are some error messages in the console.

I guess the root cause is this: (in function autonav_enter (), autonav.lua:582)
```
         table.remove( path, 1 ) -- Remove first node
```
#path is 1 if the system has no patrol lane.

lanes.getRouteP() seems to return the corrected location as the first node when the system has some patrol lanes, so the you might not need to remove the first node?

### Version

4fbc1505c (main, Local build)

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Invalid parameter for aiL_iface.
Warning: [player_thinkAutonav] [string "autonav.lua"]:284: Invalid parameter for aiL_iface.
stack traceback:
	[C]: in function 'iface'
	[string "autonav.lua"]:284: in function 'autonav_approach'
	[string "autonav.lua"]:336: in function 'autonav'
	[string "autonav.lua"]:513: in function <[string "autonav.lua"]:507>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
I see, that's quite an oversight. It still needs improvement, but the reason for this is I found that when jumping in to a system with a lane on the jump you are jumping in from, it had a tendency to overshoot and miss it, forcing the autonav to go back to the jump point before doing autonav. By "skipping" the first lane point, it was able to ignore this, however, this leads to the issue you describe, and furthermore, can make autonav skip the path that sometimes may be desireable. I guess the trick would be to give a few second moratorium before starting the autonav in a new system so that it computes lanes and such when it is at a normal velocity instead of when it newly enters the system.

**Comment by bobbens** [comment]
OK, so I've made it so autonav delays when jumping in for a bit. This seems to solve the issue while avoiding this bug. Thanks!
