### ISSUE TITLE
[Bug]: path calculateion lawed

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2410]
### What happened?

After double clicking on the jump point to the unknown system towards Majestica in the local map, the craft takes the direction to  Van Mannen.
This seems to happen, when there is no direct known route to the target system or the system is unknown.

[navigation.zip](https://github.com/naev/naev/files/13041200/navigation.zip)

### Version

0.11.0 beta

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report with a save to reproduce! The issue was that autonav was preferring lanes over going directly to the approach, even if the lanes had "holes in them".

I've fixed the functionality by default and exposed a "Lanes preference" value which controls how much out of the way the ship goes to find lanes.
