### ISSUE TITLE
[Bug]: Advanced nebula research flawed

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2414]
### What happened?

The Research Shuttle does weird things etc. The mission seems to be broken in the current state.
Please try with attached file.
[adv_research.zip](https://github.com/naev/naev/files/13062994/adv_research.zip)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
What are you seeing? I've tried it and the research shuttle seems to jump, but never spawns on the other side. It seems like your save is missing the jumpin hook, which I don't really understand why. Is that what you get too?

**Comment by bobbens** [comment]
I'm not sure why the jumpin hook is missing from the save, but I performed save surgery to add it back in, and it seems to work fine.

**Comment by BM-W1** [comment]
I see the same as you. The shuttle does not spawn.
What happens when I start at Praxis and the shuttle seems to be attacked or changes the way due to another ship, some drones seem to spawn at the shuttle. The drones don't jump. Please see the screenshot. They are, however, not from my ship, because my drone bay is full.
![Screenshot_20231022_191128](https://github.com/naev/naev/assets/122737685/da69f4fc-abe4-408e-aa03-9a14314ac347)

If I remember right, the mission started in Pudas and the shuttle jumped to Daravon and landed on the restricted Eclipse Citadel. Because it never turned up, I landed at Praxis. That's where the savefile was taken.

I hope this information rather helps than confuses you.

**Comment by bobbens** [comment]
Thanks for the details. OK, so it seems like the route is quite weird, because it used to go the other way around, and with the system changes, it's quite unnatural, I'll have to look into that, although it's separate than the issue you are seeing. I'm not sure how you lost the jumpin hook, I'll try to reproduce later and see what is going on. If you abort the mission and try it again, does it work?

**Comment by BM-W1** [comment]
I cancelled the mission, restarted in Praxis and it does not work at all. The shuttle wanted to go to Daan in two restarts.

**Comment by BM-W1** [comment]
I may have found a hint why the mission seems to be flawed:
Vilati Viata is in Ogat, but the mission requires it to be in Daravon.  
![Screenshot_20231023_113717](https://github.com/naev/naev/assets/122737685/4c693117-4761-4055-9d2b-ec38fddb35e4)
Hope that helps.

**Comment by bobbens** [comment]
OK, I've edited the route and confirmed it's fixed. Thanks for the report! The issue was most likely Vilati Vilata being moved as you said. That was helpful to track it down.

I've also made it so that by default, you will jump after pilots you are following (you can disable in info -> settings). It makes the mission a lot less tedious :) (should appear in tomorrow's nightly)
