### ISSUE TITLE
[Bug]: Cargo Pod calculation 

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2442]
### What happened?

I have the impression that the nominal extra cargo space of Cargo Pods does not equal the calculated result. Please check with the drone carrier in the savefile or the Quicksilver.
 
[Cargo Pods.zip](https://github.com/naev/naev/files/13370594/Cargo.Pods.zip)

### Version

0.11.0 alpha (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Thanks for the report. The drone carrier has a -25% cargo space modifier. I just tried to equip a large cargo pod in your save and it added 150 space (which is 75% of the true 200 space). Is this what you're seeing?

**Comment by BM-W1** [comment]
Yes, I do. And the Quicksilver has a +32% cargo space modifier, now I got it. Sorry for the bug.
 
I am asking myself what's the purpose of the cargo space modifier? The relative and absolute numbers may tend to be a bit confusing to people like me. ;-)

**Comment by bobbens** [comment]
They just encourage or discourage certain behaviours. Trader-focused ships get cargo inertia + cargo space modifiers, so they can carry more and be less affected by their cargo. Otherwise you could just equip them the same way and the ship itself wouldn't really matter. That said, maybe it would be beneficial to show the real change rate for a ship with its current bonuses somewhere (although they can depend on your core outfits and such). However, I tend to think too much information would be more confusing than helpful.
