### ISSUE TITLE
[Bug]: The system map seems to show any system "0-star system".

### ISSUE THREAD

**Issue by oo13** [naev/naev#2454]
### What happened?

And not to show the images of the stars.

0.10.x showed the images of the stars, although Delta Polaris was "0-star system".

### Version

c58f041ac (main, local build)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UncombedCoconut** [comment]
Mildly horrifying cause: we count stars by running the Lua background script and counting the images it puts in the background. What broke it? "Changed it so space dust renders behind stars due to popular acclaim."
Within the current design, I like a horrifying fix: just change the layer we look at. It's a fix for star images and Taiomi debris.
There used to be some nebula-background effects in this window. I'm not sure they need to be preserved as-is, but I'll look into it. I predict that one day bobbens will have the engine render a full background to a framebuffer for use here, just as a flex. :)
