### ISSUE TITLE
[Proposal]: Highlight spaceport bar tab if there's a mission giver

### ISSUE THREAD

**Issue by clintonmead** [naev/naev#2533]
### Suggestion

Just some visual indicator on the spaceport bar if there's a mission giver available, that is, the bar patrons with the exclamation point. Saves one having to switch to the spaceport bar tab every landing if they don't want to miss story missions. Could just be a little exclamation point inside the "spaceport bar" tab or perhaps a different colour for the tab, whatever works.

Perhaps also (or instead) some warning before taking off when there's a mission giver in the bar. 

Both of these could be GUI options, as I understand they may not be to everyone's taste.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
This would be great. NPCs with a priority <= 5 are given exclamation marks so that would have to be the criterion. I guess it would be as simple as giving support to changing the text in the window tab widget, and just adding something like `#r!!#0` at the end of the bar to indicate this. Every time the NPCs are regenerated, it would have to check to see if it has to modify the bar tab text or just regenerate it to update it. Or simplify hide the exclamation points once the player visits the bar.

**Comment by bobbens** [comment]
I've just implemented adding a simple red "!!" at the end. It should be trivial to change as necessary. Thanks for the great idea!
