### ISSUE TITLE
Engine support for non-ammo homing weapons (For Thurion use)

### ISSUE THREAD

**Issue by naev** [naev/naev#298]
Original [issue 114](https://code.google.com/p/naev/issues/detail?id=114) created by azar.wol... on 2011-04-27T15:51:28.000Z:

Essentially from an engine perspective, this would be implementation of ammoless missiles; ie, the outfit would act like a normal weapon, while the projectile would act like a tracking missile.

This would be put into use for the Thurion weapon tree, proposed for using high CPU, short-range, high accuracy homing weapons.

**Comment by ids1024** [comment]
I've started implementing this at https://github.com/ids1024/naev/tree/homing

It's not really hard to implement (since as mentioned it's basically just missile launchers without ammo) but it requires an annoying amount of code duplication. I'm not sure if there's a way to avoid that...

Pinging @AvanWolf since this is his issue but it was migrated from Google Code.

**Comment by Lineth** [comment]
Just a small addition/question: how difficult would it be to add swivel and track support to launchers (I'd imagine not much, but I know nothing about C)? Would be useful for certain advanced rocket-type weapons or ammo-limited cannons.

**Comment by bobbens** [comment]
Should be possible with current regenerating ammo. Just make the ammo regenerate infinitely fast. Visually you will see ammo, but in practice there won't be any.
