### ISSUE TITLE
Shadow Vigil introduction gives no indication of where Pas is

### ISSUE THREAD

**Issue by naev** [naev/naev#317]
Original [issue 133](https://code.google.com/p/naev/issues/detail?id=133) created by stephan on 2011-06-01T22:36:00.000Z:

At the start of the second Shadow mission, an event is triggered which spawns a ship and hails you. When you respond, you are directed to fly to Pas.

However, this is not the actual mission yet, just the event happening beforehand. And Pas is not exactly an obvious system to visit otherwise; I didn't explore it yet at all in my case. This makes it rather difficult to locate, because there is no universe map indicator like on missions.

Another effect of event-vs-mission is that if the player decides to save and quit, it's easy to forget this ever happened when coming back. There's nothing on the info screen.

**Comment by onpon4** [comment]
Just wanted to comment here that some time ago I modified that event's dialog so that the player would know to make a mental note of what system to go to for this exact reason. I think it could still be better, though. Ideal in my opinion would be to have an actual marker, which would require starting the mission with the event, but another idea that comes to mind is a text description of where Pas is.

**Comment by bobbens** [comment]
Maybe have the event be recurring until the player goes to Pas?

**Comment by onpon4** [comment]
That's an interesting thought! I'll have to look into doing that.

**Comment by onpon4** [comment]
I've added that fix to #1057. It recurs every 500 periods.
