### ISSUE TITLE
Game won't load

### ISSUE THREAD

**Issue by MandaKK** [naev/naev#575]
When I try to open the game it won't load, I can see that the process actually opens as it appears on the task manager but after a second it disappears, tried running as administrator and every other option in the compatibility tab.

I'm running Windows 10 64bits and the 0.6.1 version.

**Comment by BTAxis** [comment]
Anything in the logs?

**Comment by MandaKK** [comment]
If the logs are saved in the installation folder, then there are no logs.

**Comment by BTAxis** [comment]
By default, they are in %APPDATA%\naev\logs\

**Comment by MandaKK** [comment]
stdout is empty but this is stderr

[2015-11-13_15-11-35_stderr.txt](https://github.com/naev/naev/files/34213/2015-11-13_15-11-35_stderr.txt)

**Comment by BTAxis** [comment]
From what I can determine, the errors in the log probably are unrelated to the issue you're having. I can't be sure why it isn't loading for you, but you could consider running Naev as a portable application, it might help.
See: http://wiki.naev.org/wiki/Portable_Mode

**Comment by BTAxis** [comment]
It turns out VERSION was missing from ndata.zip, and that's why the game won't load. I've uploaded a new version of ndata.zip that includes it, but you don't really have to re-download the whole thing. Just stick a VERSION file into your existing archive and it should fix the problem. VERSION is a text file that just contains the text "0.6.1".
