### ISSUE TITLE
Problems installing SDL as described on Wiki

### ISSUE THREAD

**Issue by ohnoplus** [naev/naev#592]
Hello. I am trying to compile naev from source on my computer and am having some troubles with the SDL dependency. 

Basicly I am having the interaction I have included below. Can anyone advise me how to proceed so that I have the correct version of SDL and other dependencies to run NAEV? Note I got the install command here http://wiki.naev.org/wiki/Compiling_Nix

$> sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libgl1-mesa-dri libxml2 libfreetype6 libpng12-0 libopenal1 libvorbis0a libzip2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvorbis0a is already the newest version.
libvorbis0a set to manually installed.
libopenal1 is already the newest version.
libopenal1 set to manually installed.
libfreetype6 is already the newest version.
libfreetype6 set to manually installed.
libpng12-0 is already the newest version.
libxml2 is already the newest version.
libxml2 set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by bobbens** [comment]
Hello, this issue is unrelated to Naev. It seems like your have a depedency issue on your Ubuntu system. Try using the synaptic package manager to see if you can fix it before continuing with the instructions to install Naev.

**Comment by PhoenixRiver** [comment]
trying the command:

sudo apt-get -uV install libsdl2-2.0-0 libsdl2-image-2.0-0
libgl1-mesa-dri libxml2 libfreetype6 libpng12-0 libopenal1 libvorbis0a
libzip2

and:

sudo apt-get -uV check

to get more information as what you currently have is not enough to
find the dependancy problem (though I would guess it is related to one
of the following packages (in order of likelyhood) in some way:
libcheese7 libgl1-mesa-dri libsdl2-image-2.0-0 libsdl2-2.0-0 )

Unfortunately, in trying to build Naev you've discovered a
pre-existing problem with your system (very occassionally happens
simply through time and updates if you don't do a fresh install of
Ubuntu) - as it happens I discovered a couple of problems in the same
way (that was due to a half-installed package). It's possible to fix
though sometimes you need to reinstall one or two packages to get it
to work ("apt-get purge" can be your friend here if you have broken
config. files) - "apt-get -h" or "man apt-get" can help you find the
necessary commands you need once you've narrowed down the problem a
little more :)

Hope this helps :)

**Comment by ohnoplus** [comment]
What ended up working for me, was that instead of installing libgl1-mesa-dri I installed
sudo apt-get install libc6:i386
sudo apt-get install libgl1-mesa-glx-lts-trusty:i386

As reccommended here http://askubuntu.com/questions/588024/steam-install-error-on-14-04-ubuntu-64bit in the post by JorgeArtware.
Compiling and running the program both seemed to work fine after that, and installing the other dependencies on the wiki.

**Comment by PhoenixRiver** [comment]
Glad to hear you got it working and thank you for supplying the fix -
it may help someone else in the future :)

> What ended up working for me, was that instead of installing libgl1-mesa-dri
> I installed
> sudo apt-get install libc6:i386
> sudo apt-get install libgl1-mesa-glx-lts-trusty:i386
