### ISSUE TITLE
Jump to Herakin in the Eiderdown system is incorrectly placed

### ISSUE THREAD

**Issue by zorun** [naev/naev#616]
In the Eiderdown system, the jump to Herakin is placed in the south-east of the system.  But the Herakin system is actually north of Eiderdown.

**Comment by BTAxis** [comment]
This is on purpose, though not for any particular reason.

**Comment by zorun** [comment]
Ok, sorry for the bug report then.  This is a bit strange, because I never saw another system with this "feature": all jump points are roughly in the direction of the target system.

**Comment by BTAxis** [comment]
Normally speaking a jump point is automatically placed in the direction corresponding to the galaxy map position of the target system, but in this instance I decided to manually place the jump point elsewhere. Just because, really. There are other jump points that are slightly offset from their default positions, but none as far as the one in Eiderdown.
