### ISSUE TITLE
Mission won't end properly.

### ISSUE THREAD

**Issue by DjRay2016** [naev/naev#680]
In the first FLF mission, after eliminating the Dvaered Patrol, the mission won't end after landing back on Sindbad.  Here is the error in the LUA

Warning: [misn_runFunc] Mission 'Disrupt a Dvaered Patrol' -> 'pilot_death_dv': [string "dat/missions/flf/flf_pre02.lua"]:335: Invalid parameter for systemL_get.
stack traceback:
	[C]: in function 'get'
	[string "dat/missions/flf/flf_pre02.lua"]:335: in function <[string "dat/missions/flf/flf_pre02.lua"]:321>
Warning: [hook_runMisn] Hook [p_death] '294' -> 'pilot_death_dv' failed

**Comment by BTAxis** [comment]
The mission is failing because the mission var flfbase_sysname does not contain a valid argument for system.get(). I think I know why this is: the variable gets popped in the previous mission on abort, which shouldn't happen. I'll fix that.

Meanwhile, you can fix the problem in your current game by opening the console and typing:
var.push("flfbase_sysname", "Sigur")

**Comment by DjRay2016** [comment]
Thanks, BTAxis.  That fix did indeed work.
