### ISSUE TITLE
Proposal: Player Escort Hiring System

### ISSUE THREAD

**Issue by onpon4** [naev/naev#832]
This is something I won't have time to work on for the moment, but think might be a good idea and something I might be interested in working on at some point in the future.

So, back when I first played Naev, it had this problem where there was this very clear hierarchy: small ships < medium ships < big ships. This was because smaller ships were weaker and more vulnerable, but didn't have any particular advantages over larger ships in terms of things like speed. This was fixed several years ago with the introduction of many mechanics, but most importantly the "mass limit" system, which has done a very good job to make light ships more useful by allowing them to be much more agile than their larger counterparts.

That improvement applied to medium (Corvette and Destroyer class) ships too. However, what I have consistently found is that medium ships find themselves sandwiched between the faster and more numerous light ships, and the slower but heavier armored and deadlier heavy ships. Medium ships are too weak to take the punishment of a capital ship, yet too slow to run away from light ships or evade fire of any ship. This has left medium ships in a peculiar situation where it never makes any sense for the player to use one; the second you enter hostile territory, a medium ship is essentially an open target that is easily taken out.

That is, and this is where my proposal comes in, unless you happened to jump into a system that *also* has very high friendly presence. If you're lucky enough to find yourself in that situation, controlling a medium vessel can be a massive boon; Corvettes and Destroyers are fast enough to mostly keep up with a friendly fleet, but powerful enough to inflict crippling damage to opposing fleets. Additionally, medium cargo ships are some of the best ships for carrying very large amounts of cargo in the game, and the help of friendly ships helps to draw the attention of hostile ships away from you.

Escorts have become an important part of how the A.I. ships fight. But as it is right now, the player is, for the most part, unable to create fleets. The only way for a player to have any kind of escort is through fighter bays, which can only be used on heavy ships or at least ships with heavy weapon slots. So here I would like to propose an expansion of the idea of escorts to match what is seen in A.I. ship fleets: the ability to hire your own escorts to form your own fleet.

There are a few possible ways to do this, but the following options are the ones I'm considering in particular:

1. Allow the player to hire random non-hostile ships by hailing them in space; or
2. Add a hub of sorts, probably presented as a menu (similar to the mission computer), where you can hire new pilots.

Whichever method of hiring escorts is used, hiring an escort would entitle that escort to a certain agreed-upon compensation. This could either be a flat rate over time, or (my preferred option) a percentage of any payment you receive. A mix of the two could also perhaps be used; you could have some escorts who ask for a percentage of your pay, and some other escorts who ask for a fixed rate. Either way, this would encourage you to keep your fleet small so as not to be a net sink. It would also teach players a bit about economics. ;)

Now, here's the interesting bit: I propose, furthermore, that each ship should have a new stat added indicating a multiplier for the rate charged by all escorts. The biggest ships in the game, such as the Empire Peacemaker, would have a rate of 100%, i.e. if an escort would charge 5% as a baseline, 5% is what you pay. Medium ships would have a smaller rate, e.g. 75%, and small ships would have a rate that's smaller still, e.g. 50%. The exact numbers can be figured out later, but the point is that smaller ships would entail lower hiring costs, which would also enable you to hire more pilots in a cost-effedctive manner.

Should you decide you no longer need an escort, you can fire them at any time. However, to discourage doing this in the middle of a mission, I propose turning any former escort hostile when you fire them while in space.

That's about it. As I said, this is just an idea I wanted to share. Any feedback on the idea would be appreciated, and we'll see if this goes anywhere.

**Comment by ids1024** [comment]
Naev definitely should have some escort hiring system.

> However, to discourage doing this in the middle of a mission, I propose turning any former escort hostile when you fire them while in space.

Another alternative would be for them to demand a fee (to cover the cost of returning). They could still become hostile if the player refuses to pay.

I think it would be interesting to consider if the player could have escorts (either in fighter bays or otherwise) using ships owned by the player (who could equip them however they want). They could then hire pilots to fly them (which would probably have to apply to fighter bays as well).

I suggested a mechanism like this for fighter bays previously (in [this forum post](https://forum.naev.org/viewtopic.php?f=15&t=1220), though the forum is down). This would take some effort to implement but would eliminate the "fighter" outfits.

 It would be possible to also allow hiring pilots with their own ships at a greater cost and lower flexibility in equipment, but without the initial investment of buying a ship.

**Comment by onpon4** [comment]
> It would be possible to also allow hiring pilots with their own ships at a greater cost and lower flexibility in equipment, but without the initial investment of buying a ship.

Ah, yeah, I forgot to mention: I was actually thinking of leaving you with no influence whatsoever over how the ship is equipped. It would just be, you pick escort X which has configuration Y, and you're stuck with that configuration for as long as escort X is in your employ. This would also mean no initial investment; the pilot would just be assumed to have already bought the ship and equipped it the way they want. The reason I would want to do it this way is both because it would make the system simpler (so you still just configure one ship rather than half a dozen), and because it would avoid penalizing you (too much) for the death of an escort. Under this system, losing an escort would simply mean you have to find a replacement for them. Though offering the option to have a "deposit" of sorts up-front for a new escort could be a nice idea.

I like the idea of the pilot demanding a fee before turning hostile, though that might be a bit redundant since you could simply bribe them after they turn hostile for the same effect (assuming they're left bribeable; I don't remember off the top of my head how bribes play into individual pilots set as hostile in Lua).

**Comment by ids1024** [comment]
Yeah, what I'm suggesting definitely adds complexity. Anyway, I personally don't really like having the escort ships as "ammunition" outfits; though that's separate from this proposal. The general way fighter bays work, and how that interacts with other kinds of escorts (hired, or perhaps part of a mission) could use some thought.

> that might be a bit redundant since you could simply bribe them after they turn hostile for the same effect

Yep. Really it's just a way to achieve the same effect (with little added complexity to the code or the player's experience) that might seem a little better because it seems like a natural thing to happen. And it's easy enough to add an extra dialog box for payment when firing the pilot. An alternative would be to have the pilot send a message asking for such a bribe.

>  I don't remember off the top of my head how bribes play into individual pilots set as hostile in Lua

It's based on faction specific scripts. Empire ships, for instance, are never bribable. Pirates usually are, but I think there's a random chance that they're not. Since it's all handled in Lua, it's easy enough to adjust.

**Comment by onpon4** [comment]
> Anyway, I personally don't really like having the escort ships as "ammunition" outfits; though that's separate from this proposal. The general way fighter bays work, and how that interacts with other kinds of escorts (hired, or perhaps part of a mission) could use some thought.

Yeah, probably just using a fighter bay as a dock for, say, repairs would be a better choice. Though honestly I can't think of a very good way to make fighter bays useful without also hurting gameplay.

Alternatively, maybe fighter bays could stay as they are, but combined with reworking the ammo system (suggested in passing by @bobbens in #719 ) it would get rid of the thing where you spend loads of money on ships. Fighter bays could count launched fighters toward their "ammunition" as well to avoid players abusing the system to build up large numbers of fighters. In that sense the ships would just be drones that are manufactured within the ship, and it would be separate from escorts (which would entail renaming some hotkeys to prevent confusion).

**Comment by bobbens** [comment]
One of the ideas that was on the roadmap or at least written somewhere was allowing the player to control fleets, with the more ambitious version being the game turning into a pseudo-RTS with enough ships. However, how it is implemented will have a large impact on the gameplay and balance of the game, which is where my main worries lay.

First of all, how to balance missions when the player is allowed to have fleets? There are two ways I can think of.
1. Try to dynamically scale encounters based on the player's fleet (something like many modern games do, but it feels a bit hacky to just scale everything up)
2. Basically assume the player will have a fleet and balance based on that.

I'm not sure what the best option is, but it might be a mix of both. Assume the player has a fleet and scale encounters "slightly" based on the player's fleet. Of course we would want caps so that what should be simple missions wouldn't scale into crazy encounters just because the player has good ships.

Regarding how to implement them. One way would be, as mentioned, have them be sort of mercenaries which you pay a flat rate. However, this would just make it so the player would change escorts every mission and make it much harder to balance. How the original Escape Velocity handled it was to limit escorts to 8, allow player to pay them, however, the player could "capture ships" to get free escorts. At the end of the game the player would usually have 8 fairly strong permanent free escorts. This is also broken and "handled" by the fact the escorts would basically fight everything and thus die fairly easily when travelling through hostile systems.

Possible implementations I can think of are:
1. Make money based escorts. These can be flat-rate (encourages per-mission assembling), or have some sort of penalty on the money the player makes (they take some % of all rewards, encouraging more stable fleet compositions).
2. Make "escort power" a separate value that can be unlocked during the game and determines how many escorts the player can have. This can be implemented in several ways. One would be a value that gets monotonically incremented through missions (pilots joining the player, could spiral out of control). Another would be some cap that gets raised through missions (would allow more gating without spiraling out of control). This "escort power" would be sort of a budget, so you could choose to spend it on a big ship or many small ships. The player would either have to pay for the ships (very hardcore), or just have them regenerate when you land at a shipyard selling the ship of that type (much more forgiving).

I am leaning towards using escort power (needs better name) and making it a core mechanic of the game instead of more sort of a gimmick. Thoughts?

**Comment by onpon4** [comment]
I rather like the % of rewards approach. It would be pretty simple to implement (just modify player.pay to give the player less money), and it would encourage you to keep your fleet at a minimum level to maximize your own profits. Perhaps, to prevent players from firing pilots too much, an up-front nominal fee could be required to hire a new pilot, maybe called a "deposit", "equipment cost", "training cost", or something like that.

I don't like the idea of "escort power" because it would subvert the main motivation behind this proposal: to make medium ships useful. If the number of escorts you can hire increases with smaller ships, then the advantage of more ships with a smaller ship yourself would mitigate any possible benifit of having a heavy-hitter to back up your fleet. After all it really doesn't take many small ships to outclass a single medium ship, maybe 3 or 4 at the most. Besides, I don't like the idea of adding that much complexity to the game.

I don't like the idea of free escorts, or anything you described as coming from Escape Velocity (I've never played EV, so I'm just going by what you're saying). I think it would be better to use economics to encourage a limit on escorts rather than some predefined cap. After all if missions become more rewarding and challenging over time, for example, that could make it so that it makes sense to grow your fleet over time.

Dynamic scaling I have mixed feelings about. We don't do that right now; if you have a really powerful ship then it's just like, good for you, you get to beat the mission easier. But at the same time, maybe that wouldn't be necessary? E.g. if you pay your escorts a percentage, then having them would make the mission easier, but also cut your pay down, especially if you have a lot of them. Consider if everyone takes 7%. Now if you have 7 escorts, the mission is going to be much easier, butt your pay is almost cut in half.

One other possible concern I can think of with paying escorts a percentage is that you could simply allow them to die during the mission and take full payment, so one more possible proposal would be to make that impossible by determining that slice when accept the mission (for that pilot), or if you hire a new pilot in the middle of a mission, when hired. So for example, that would mean that if you have 4 pilots when you take a mission, then hire an additional 6, you would be guaranteed to pay those 10 slicese, e.g. if the slice of each pilot was 5%, you will be getting only 50% even if all of the pilots are destroyed during the mission. This could be explained away as the payment going to their families or something.

I don't like the idea of the player controlling these escorts. I think it would be better for them to be autonomous and follow some common-sense rules similar to the other A.I. ships. Current "escorts" (fighter bays) I think should be reimagined as drones and the fact that you control them somewhat, can regenerate them after they get destroyed, and don't have to pay a fee for them would be their primary distinction from escorts. Basically, more difficult to use and less effective, but more reliably available and without recurring costs.

**Comment by ids1024** [comment]
> First of all, how to balance missions when the player is allowed to have fleets? There are two ways I can think of.

I can think of a couple others.

* Some missions may require a fast ship. If a player can only command a fleet from a large slow ship (which is true with fighter bays; I don't know how it would be justified otherwise) this won't work.
* Missions could require stealth, and thus the player may be caught if seen with a large fleet (this makes sense for certain missions).
* For something like the collective campaign, the Empire probably doesn't want the player to come along with a fleet of mercenaries of dubious loyalty who may not be trusted to keep quiet.
* For some missions, perhaps the player may fear such betrayal themself; since another side could bribe their escorts.
* For a particularly dangerous task, escorts may expect an excessive pay (far beyond routine defense of a cargo ship); making them less attractive.
* Hired escorts won't have the necessary shielding to survive the Sol nebula, and may otherwise not be able to go on missions requiring the player have special equipment.

(Some of these reasons seem a bit similar; but this is just my attempt to come up with as many as I can.)

The direction Naev has gone seems to encourage owning different ships for different purposes (which seems more interesting than games where you just want the most powerful ship). So probably taking a mixed approach is good. Some missions may be best with a single small ship, with a single large ship, with a fleet, etc. Not to say it's the easiest solution.

**Comment by onpon4** [comment]
That idea of increasing costs sounds interesting. There could be some sort of flag missions could use to mark missions as dangerous, for instance.

Also, building off of the bribing idea, perhaps that could just be a normal risk of hiring someone. Right now only the player is able to offer bribes, but it  would be nice to implement that for A.I. too (and this would also enable a new form of piracy by allowing players to shoot at defenseless ships to get them to offer a bribe, but that's on an unrelated note). And if we did that, you would always have to be concerned about escorts being bribed and turned against you. A special rule could be made for escorts to make them hostile as soon as they're bribed just to make it more interesting.

I was also thinking the possibility of just not allowing escorts for certain missions, and the Collective campaign would definitely be an example. We already have missions denying access to missions or offering lower rewards based on what ship you have, so doing so on the basis of fleet size would certainly be doable too.

By the way, regarding the owning different ships thing, I want to make a point of mentioning again that one of the main reasons I think having such an escort system would be a good idea is to benefit the medium ships, to give them their own plausible niche. So I think it would be important to not design the system in such a way as to make a reverse linear model where fleets accompanying a smaller ship are always better than fleets accompanying a larger ship. Perhaps one possibility to consider to this end is to severely penalize the player cost-wise for recruiting a ship larger than they themselves pilot. For example, if you pilot a fighter and recruit a destroyer, perhaps that destroyer would end up requiring 85%, whereas recruiting that same destroyer when you yourself have a destroyer would only require e.g. 15% (just throwing some numbers at the wall there). Of course this would have to be balanced with the concern that large vessels should generally not have particularly large fleets; the idea would be to make medium-ship-headed fleets moderate numbers of durable heavy-hitters, small-ship-headed-fleets large swarms of less durable light hitters, and heavy-ship-headed fleets small task forces of tactical lightweight ships. At least, that's how I envision it.

**Comment by bobbens** [comment]
I'm not entirely sure. I would argue for making escorts an integrated part of the game using some sort of fleet power. To encourage the player to use weaker ships, it could be done so that you can use a fleet power equal to `max( 0, fleet_power - current_ship )` so that unless you have a high fleet power, you wouldn't be able to use escorts in a capital ship, thus encouraging smaller ship usage. Fleet power would be an attribute that would be increased depending on key events, and not be additive. For example if you have 70 fleet power and a mission sets your max to 50, it would be ignored, while if it set it to 90, your max would become 90.

My main reasoning for this would be that it would make it easier to design things assuming some fleet power and not be as variable as the player being able to hire and fire pilots fairly arbitrarily. From the designing of combat-oriented missions perspective this would be fairly nice. You could just design missions around XX fleet power, and even set different sets of enemies depending on the fleet power. Of course this would be independent of other limiting factors like stealth/speed.

A possible implementation would be to basically let player design ships he owns (and has outfitted) as escorts until the fleet power cap is set. That would let the player set the specific outfits (and also require the player to own more ships). Although it does break immersion, I would argue for letting the ships "regenerate" when the player lands at a planet with a shipyard just to avoid making them grind infinitely. If necessary, having some sort of insurance cover 95% of the cost or something like that, while the player would only pay 5% or less could be implemented (or be optional parameter if the player wants a hardcore mode).

While certainly a money-based escort things, I am just worried it would allow for too much balancing mayhem in combination with increased micromanagement and grinding. However, if those could be solved elegantly, I wouldn't be against it.

**Comment by onpon4** [comment]
I don't know, the whole "fleet power" idea seems like something that would just seem arbitrary and forced. I'd rather see use of economic forces to get the desired result; that would make the game more immersive.

Also, the idea reminds me of the current "combat rating" stat, and if you look at the various missions, very few of them outside of the Empire missions developed years ago attempt to use that. It's a confusing stat that doesn't really do anything useful except add a nice string to your info screen. "Fleet power", I think, would be a similar situation, except you'd have to also arbitrarily tell the player that they can't hire any more pilots because they've used all their "fleet power".

When it comes to the progression aspect you're proposing, I think a much better way to achieve that would be to make fees for escorts smaller and smaller down to a certain cap. Like maybe a small escort could cost 80% for big ships and 40% for small ships at first, but eventually it could lower down to 10% for big ships and 5% for small ships. If we did that it could be controlled by a "fleet power" stat in the background (but invisible to the player), or it could just utilize the existing "combat rating" stat. That way the increase in feasible fleet size would be controlled by economics and justified in-universe.

Another thing that can be investigated is making fewer and weaker pilots available when you have a low rating (i.e. at the start of the game) so that you gradually have better options as the game progresses.

> A possible implementation would be to basically let player design ships he owns (and has outfitted) as escorts until the fleet power cap is set.

Another problem I have with that is micromanagement. It would encourage buying very large numbers of outfits to try to maximize each of your individual fleet ships. If the ships are preset (because they're independent contractors, say), then it would force the player to not worry about specifics too much and just look at general numbers, e.g. "this pilot has a higher rating than that pilot, so I'll choose this pilot". It would be a better experience I think.

**Comment by bobbens** [comment]
> Also, the idea reminds me of the current "combat rating" stat, and if you look at the various missions, very few of them outside of the Empire missions developed years ago attempt to use that. It's a confusing stat that doesn't really do anything useful except add a nice string to your info screen. "Fleet power", I think, would be a similar situation, except you'd have to also arbitrarily tell the player that they can't hire any more pilots because they've used all their "fleet power".

Combat rating is some legacy component copied from original Escape Velocity. It is basically sort of a counter that tracks how many enemies you killed. Honestly, I don't think anybody would miss it if removed.

> I don't know, the whole "fleet power" idea seems like something that would just seem arbitrary and forced. I'd rather see use of economic forces to get the desired result; that would make the game more immersive.

I'm not against doing it with money, but I am worried that using soft constraints (money) instead of hard constraints (fleet power) will be much trickier to balance. The player will be able to basically to, for a short period of time, basically trivialize any combat encounters that are not designed with large player fleets in mind. Furthermore, the current state of balance of the Naev "economy" is fairly bad as far as I know and that would also be fixed to make some sort of sense before allowing it. Besides only economy, I'm guessing stuff like faction level / missions could be used to unlock "unique" and stronger escorts which could allow some sort of gating. On the other hand, using some sort of fleet power concept which would represent the maximum capacity the player can muster would be easier to balance against.

> Another thing that can be investigated is making fewer and weaker pilots available when you have a low rating (i.e. at the start of the game) so that you gradually have better options as the game progresses.

As mentioned above, unlocking pilots with missions / reputation would make sense. However, being decentralized in nature, I still think it would be harder to balance than having it all centralized in some sort of fleet power concept.

> Another problem I have with that is micromanagement. It would encourage buying very large numbers of outfits to try to maximize each of your individual fleet ships. If the ships are preset (because they're independent contractors, say), then it would force the player to not worry about specifics too much and just look at general numbers, e.g. "this pilot has a higher rating than that pilot, so I'll choose this pilot". It would be a better experience I think.

As pilots are currently randomized on creation (including fighter bay pilots...), this would require having some sort of predetermined pilots or just having a pool available that is partially / randomly refreshed. What I'm worried is that players may spend a long time trying to find perfect escorts if they appear randomly since they are unable to modify their outfits. Allowing the player to manually set it would be better for these players. We could also add an "autoset" option to automatically assign outfits which could also trivialize this (should be probably added either way). Furthermore, as the player gets more unique outfits (something that I've always wanted to expand), they would also allow the escorts to use them (of course, something similar could be done with unique escorts).

Although a way of side-stepping the issue entirely with economy-based escorts would be to just have each ship type have one determined outfit configuration and have them always appear to hire (of course with restrictions based on the faction, etc...).

The part of micro-management I am more worried about is having economy-based encourage only hiring escorts for certain missions, making the player have to go to an system with available escorts, choose and hire them, do the missions, then fire them all, ad infinitum. Adding some sort of fixed cost when hiring (or firing) would discourage this, but still some players would try to avoid increasing their expenses with escorts. A fleet power cap would have no recurring cost (depending on implementation, until ships die), and would allow the player to experiment more freely with configurations.

The way I see it:

Economy-based fleets
* Makes more sense than an arbitrary cap
* Requires a sensible economy
* Potentially can trivialize many combat encounters (needs per-mission limits and checks)
* Will need a secondary mechanism limiting what pilots can be hired
* Allows for unique pilots as rewards

Capacity-based fleets
* Based on an arbitrary number (needs better in-game explanation)
* Needs guidelines determining how to increase and use this number
* Needs some way to compute the capacity of all ships (or define in xml)
* Makes the player have to own more ships/outfits and micromanage them (mitigated with auto-outfitting)

Common issues
* How to handle pilot death?
* Many existing missions will need rebalancing

**Comment by onpon4** [comment]
Regarding that whole grinding aspect, I figure one simple way to do that is to not ever show the player specifics (just general class/rating), and to make them pay a sort of deposit to hire someone. You could even go further and require paying a deposit just to see the ships; nominal, of course, no more than say 5k. The idea would be to make the benefit of grinding for the best possible fighter so marginal, and the process so tedious and costly, that it won't be an appealing option.

Another thing worth doing, and I've implemented something like this a couple years back for the Commodity Run mission, is to just have some kind of limit on when you get different pilots, like to make it so that a certain number of periods needs to pass before the lineup changes or something. That would make attempting to grind for the best pilots even more tedious. (I imagine you would just store the available pilots on a per-planet basis and refresh those if a certain amount of time has passed.)

On the other hand, I don't think there's a problem with players adjusting their fleets to match what they need, at least to a certain extent. It would be like when a real employer lays off employees due to having too much of a workforce, then hires more employees due to having too little workforce. To discourage changing things up *all* the time, I think a nominal deposit up-front, plus a limit to availability of pilots and combining a flat rate with a percentage "commission", would sufficiently do it.

As for soft limits, I think it's worth noting that at some point these soft limits would make you start to lose money, e.g. if you have 20 pilots that each take 5%, you're literally doing missions for nothing, and with that flat fare as well, it would guarantee loss of money. So in that case, something less than 20 pilots would be the practical (sustainable) limit. I could imagine, however, some players choosing to hire more pilots than they can afford for missions that are very difficult, or if they're rich and having trouble getting through a particular region of space. That's not necessarily a problem, in fact it could be a nice sort of difficulty stabilizer.

Also worth noting, I imagine a percentage thing to allow your money to be taken away as well, e.g. if you're paid 100k credits while you have 21 pilots that each take a 5% commission, you would lose 5k credits at that point. And I figure if your funds drop to 0, your entire fleet quits and turns on you, which would further discourage reckless hiring of dozens of pilots.

**Comment by ids1024** [comment]
> The part of micro-management I am more worried about is having economy-based encourage only hiring escorts for certain missions, making the player have to go to an system with available escorts, choose and hire them, do the missions, then fire them all, ad infinitum.

@bobbens So are you envisaging that the player would basically always be accompanied by escorts after a certain point in the game? I don't know about that. As I was saying, it's great that Naev aims to have the player use different ships for different purposes (a fighter with an upgraded engine and afterburner for one, a slow cargo ship for one, a quicksilver for another, and a massive capital ship for certain purposes). This is somewhat broken if the player is always the center of a fleet.

Though I agree we need to avoid too much complexity flying to another system to hire escorts for each mission. The current fighter bays, despite many flaws, are actually good for this. It's easy enough to equip a ship with fighter bays for a mission, so this integrates well with the general system of choosing a good ship for the mission.

I'm not really sure how to achieve that with a hiring system.

This "fleet power" system seems like it would end up seeming artificial as @onpon4 said, but I can't imagine exactly how it would work out. It might seem alright if done well.

**Comment by bobbens** [comment]
> @bobbens So are you envisaging that the player would basically always be accompanied by escorts after a certain point in the game? I don't know about that. As I was saying, it's great that Naev aims to have the player use different ships for different purposes (a fighter with an upgraded engine and afterburner for one, a slow cargo ship for one, a quicksilver for another, and a massive capital ship for certain purposes). This is somewhat broken if the player is always the center of a fleet.

I always envisioned something like that. In the case of a fleet, slowest ship could be factored into jump time to not allow a fast fighter to bring along capships. I don't think having a "permanent" fleet would be incompatible with encouraging the player to change ships if done right.

> Regarding that whole grinding aspect, I figure one simple way to address that is to not ever show the player specifics (just general class/rating), and to make them pay a sort of deposit to hire someone. You could even go further and require paying a deposit just to see the ships; nominal, of course, no more than say 5k. The idea would be to make the benefit of grinding for the best possible fighter so marginal, and the process so tedious and costly, that it won't be an appealing option.

This might be discouraging to min-max type players. It might be better to just make it fixed by using multiple templates or single loadout per ship type that are always available.

> Another thing worth doing, and I've implemented something like this a couple years back for the Commodity Run mission, is to just have some kind of limit on when you get different pilots, like to make it so that a certain number of periods needs to pass before the lineup changes or something. That would make attempting to grind for the best pilots even more tedious. (I imagine you would just store the available pilots on a per-planet basis and refresh those if a certain amount of time has passed.)

IIRC, the game also does this for the spaceport bar.

> On the other hand, I don't think there's a problem with players adjusting their fleets to match what they need, at least to a certain extent. It would be like when a real employer lays off employees due to having too much of a workforce, then hires more employees due to having too little workforce. To discourage changing things up all the time, I think a nominal deposit up-front, plus a limit to availability of pilots and combining a flat rate with a percentage "commission", would sufficiently do it.

Having three different parameters (deposit up-front, flat-rate, and commission) is a bit tricky to balance and also convey to the player. If possible having it more simple would be better, but in this case it would also probably be exploitable.

That said, I am not against economy-based escorts. I just feel that the amount of fine-tuning and balancing necessary to get it working seems scarily high. That said, I also wouldn't having both systems co-exist, which could be used to mitigate issues between both systems.

**Comment by onpon4** [comment]
> It might be better to just make it fixed by using multiple templates or single loadout per ship type that are always available.

Yeah, that would work too.

**Comment by PhoenixRiver** [comment]
Apologies I'm a little late to the discussion but a couple of things
to consider that I thought might simplify some of the systems you're
looking at wihtout causing too much unbalance in the current game
system...

1. Missions have a danger rating; Escort pilots have a courage rating
- if the pilots courage does not exceed the missions danger rating
then the escort pilot refuses to fly the mission - the player is given
the choice to fire them, bribe them with extra money (only increases
courage by a ceertain small anount) or leave them (and still pay for
them) while they do the mission (at which point they rejoin the player
once they have finished the mission. Pilots flying less combat capable
ships could be less willing (on average) to have high courage ratings
- ditto pilots with expensive ships having less courage (don't want to
lose their investment).

2. Players should have to pay for the fuel and ammunition that escorts
use and, possibly, travel distance and speed be limited to the slowest
(shortest warp capable) ship - I don't remember either of these being
factors in the original EV and the fuel and ammunition costs certainly
weren't.

3. To help address the usefulness of medium ships maybe friendly and
neutral AI pilots in medium ships could "fleet" as they traverse
systems, small ships wouldn't naturally do this because they have too
different speeds and big ships are too slow to collect and traverse
together to be worth it but medium ships exist in this sweet spot - it
would require a little calculation in putting together "fleets" for
each system but this might be made easier by adjusting the ship
spawning system to make medium ships spawn together (and possibly near
the player's entry awrp if that makes sense for the system (i.e. warps
from war zones or the nebula maybe not and where those ships would be
hostile to the player also not).

Hope these ideas help contribute and I might find time to do a little
to help - but apologies for not having recently or not doing - major
life changes :/

River *<:@)

**Comment by bobbens** [comment]
> 1. Missions have a danger rating; Escort pilots have a courage rating
- if the pilots courage does not exceed the missions danger rating
then the escort pilot refuses to fly the mission - the player is given
the choice to fire them, bribe them with extra money (only increases
courage by a ceertain small anount) or leave them (and still pay for
them) while they do the mission (at which point they rejoin the player
once they have finished the mission. Pilots flying less combat capable
ships could be less willing (on average) to have high courage ratings
- ditto pilots with expensive ships having less courage (don't want to
lose their investment).

I would try to keep it as simple as possible and avoid adding more factors such as courage, etc.

> 2. Players should have to pay for the fuel and ammunition that escorts
use and, possibly, travel distance and speed be limited to the slowest
(shortest warp capable) ship - I don't remember either of these being
factors in the original EV and the fuel and ammunition costs certainly
weren't.

Currently I am pretty sure we made fuel free as the cost was basically negligible anyway. With regards to ammunition, I am in favor of making it free (and slowly regenerating) to make missiles and such more usable for the player. Having to buy and set up ammunition adds more micromanagement without really making the game better in any significant way.

**Comment by PhoenixRiver** [comment]
On 06/08/2019, Edgar Simo-Serra <notifications@github.com> wrote:
>> 1. Missions have a danger rating; Escort pilots have a courage rating
> - if the pilots courage does not exceed the missions danger rating
> then the escort pilot refuses to fly the mission - the player is given
> the choice to fire them, bribe them with extra money (only increases
> courage by a ceertain small anount) or leave them (and still pay for
> them) while they do the mission (at which point they rejoin the player
> once they have finished the mission. Pilots flying less combat capable
> ships could be less willing (on average) to have high courage ratings
> - ditto pilots with expensive ships having less courage (don't want to
> lose their investment).
>
> I would try to keep it as simple as possible and avoid adding more factors
> such as courage, etc.

This does indeed make things more complicated but could in future be
used to add more interesting things such as fight or flight to AI
generally (and would be much simpler than performing calculations,
such as relative strength of ships, etc. on the fly). I agree that
giving the player a choice is mor complicated but this could simply be
removed and the pilot either stays or goes (and says so) depending on
this courage factor without player interaction... since most players
would want cargo ships to stay out of fights and small fighter escorts
and strong big ships to stay with him anyway.

Also I'm assuming that you don't generally mean complication is a bad
thing or else we should be writing a perfectly uncomplicated snake
game ("space snake" if you prefer a sci-fi feel) rather than a highly
complicated economic and combat space sim.

>> 2. Players should have to pay for the fuel and ammunition that escorts
> use and, possibly, travel distance and speed be limited to the slowest
> (shortest warp capable) ship - I don't remember either of these being
> factors in the original EV and the fuel and ammunition costs certainly
> weren't.
>
> Currently I am pretty sure we made fuel free as the cost was basically
> negligible anyway. With regards to ammunition, I am in favor of making it
> free (and slowly regenerating) to make missiles and such more usable for the
> player. Having to buy and set up ammunition adds more micromanagement
> without really making the game better in any significant way.

It was rather less negligible at the start of the game and ditto
ammunition but maybe we just include it with docking fees... though
that does remove the possiblity of ammunition weapons that can only be
restocked at certain types of port (e.g. very heavy torpedos or other
types of weapon that you'd not expect backwater ports to have
ammunition stock for  or ports that belong to factions that are
enemies or at war with the faction that creates the ammunition for
those weapons.

Just a thought,

River *<:@)
