### ISSUE TITLE
Colorblind accessibility

### ISSUE THREAD

**Issue by onpon4** [naev/naev#868]
This is an issue I've thought of for years since I always look out for this sort of thing in games I develop, but I haven't come up with a solution myself. So I think I'll raise it here.

Basically, Naev relies a lot on color to convey information, so it's not colorblind accessible. Here are the examples of requiring color vision I can think of (in order of importance):

* The overlay map and display indicators use only colors to distinguish hostile/neutral/friendly ships, as well as other kinds of space objects and whether or not a given thing is selected (very important)
* Current mission objective in the OSD (as opposed to other objectives) is indicated only by color (very important)
* Mission marker types are distinguished only by color (very important)
* Slot sizes are distinguished only by color (important)
* Some text is differentiated from other text only by color (not very important; differentiation usually unnecessary)

There of course may be others that I missed (being someone with full color vision).

I'd like to note as well that many cases involve having to differentiate red and green; red/green color deficiency is quite common so that's going to prevent even more people from being able to play and enjoy the game.

There's nothing wrong whatsoever with using colors in these situations, and I think we can all agree that those should stay (as they're really nice and useful for those of us with color vision). So what I'm suggesting in all cases is keeping colors, but also adding a secondary method of distinguishing these things for those who cannot see the color differentials. What to do to this end depends on the particular situation. Sometimes brightness levels can do the trick, sometimes adding a symbol does the trick, and sometimes modifying the shape of something does the trick. The point is to make the game as accessible as it possibly can be.

Some of these are tricky, of course. The map in particular poses quite a challenge as so much information is being packed into color right now. Let's discuss some ideas on how to deal with this. :slightly_smiling_face:

**Comment by ids1024** [comment]
Android has a neat feature under developer options for simulating different types of colorblindness. I haven't tried it, but apparently [Color Oracle](http://colororacle.org/) can be used for that purpose on Windows/Mac/Linux.

**Comment by onpon4** [comment]
That could definitely be real helpful for testing purposes.

It also occurred to me that perhaps there could be a "colorless mode" that filters all colors to shades of gray, as a fallback in case a type of colorblindness is missed.

**Comment by bobbens** [comment]
The colors defined in the code could easily be moved to the config file for full configuration. Or just define two sets (one for colorblind one for regular) and have an option to change between them.
Although Naev is not using shaders atm, it should probably be trivial to write a color blind simulation shader. However, I wouldn't be surprised if that would require completely ditching the fixed pipeline and moving to shaders, i.e., a fairly big rehaul of the backend (shouldn't be **too** hard though)

**Comment by onpon4** [comment]
So on this issue of colorblind accessibility, I'd like to share some screenshots filtered through [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/), a simulator of colorblindness. My motivation for doing this is mainly to generate sympathy for those who are colorblind and give a visual idea of the scope of the problem as it stands now. For simplicity's sake I just saved the monochrome images, but you can see through Coblis that a lot of the issues here are just as bad with a dichromatic view. In some ways certain parts could even said to be worse with certain dichromatic views, though that may be subjective. In any case:

![1](https://user-images.githubusercontent.com/2217995/84694695-952bb680-af17-11ea-8723-50248f4fa652.png)

This one I actually took because I wanted to see if the heat indicator was visible, and luckily, it is! As it turns out the shade of red used for that is much brighter than the shades of gray behind it.

But you can incidentally see some contrast problems, especially with the status message text on the bottom-right; we know that it's purple, but from the colorblind player's perspective it contrasts so poorly with the nebula background behind it that it's practically invisible.

You can also see here, for the first time, that while the green text in the OSD is easily distinguishable from the white text (this holds true for green-blind as well), the contrast with the background is very poor, so the current objective is (ironically enough) harder to read than the inactive objectives, essentially highlighting the later objectives.

![3](https://user-images.githubusercontent.com/2217995/84694704-99f06a80-af17-11ea-9fe6-dc9fa946df1a.png)

Can you tell what I have selected in this picture?

![4](https://user-images.githubusercontent.com/2217995/84694705-9a890100-af17-11ea-95f7-770783290e28.png)

There's a lot more going on in this image than you think. No, really. See if you can find what it is. There are three points of interest.

![5](https://user-images.githubusercontent.com/2217995/84694709-9bba2e00-af17-11ea-8c54-0af0ed7ccb13.png)

Is there anything here an aspiring captain should be aware of? See how long it takes you to notice.

![6](https://user-images.githubusercontent.com/2217995/84694713-9ceb5b00-af17-11ea-8783-a3cb06730e88.png)

I could have swore there were hotkeys for those buttons. It would be nice if the buttons showed what they were! (In truth I don't care for those hotkeys, but the lack of any indication for them from a colorblind player's perspective is worth mentioning.)

I actually took this screenshot for the radar, though. See if you can point out the pirates. Yes, all of them. They're very easy to spot in full color.

![7](https://user-images.githubusercontent.com/2217995/84697187-b68ea180-af1b-11ea-8a41-f140fad2817a.png)

Lots to do on this map! See if you can find out what kinds of planets and factions these are (friend, foe, uninhabited) without prior knowledge. See how long it takes for you to find where the destination and source are. And can you figure out what route is being taken? Where was it that I was supposed to go for that mission, again? And where is this new mission that I'm being offered on the mission computer?

**Comment by onpon4** [comment]
A couple more screenshots:

![9](https://user-images.githubusercontent.com/2217995/84709021-8bae4880-af2f-11ea-8ba3-29c6a8d7d531.png)

Good news: the outfit shop is nowhere near as bad as it used to be! Obviously the size colors aren't visible and the coloring of text to show "good" or "bad" doesn't work (though honestly I think it would look better and sacrifice nothing to get rid of those anyway, make all outfits consistent in that regard), but the variety of images for outfits we now has makes that indication less essential. Still, it would be nice if there were a size indicator so a colorblind person could see right at a glance what size an outfit is.

![8](https://user-images.githubusercontent.com/2217995/84708781-1d698600-af2f-11ea-8f39-be11d9636091.png)

The equipment screen is not so great, though. Contrast between the text and the bar indicating CPU Free is very bad, slots have no indication of their size, and the important information that's supposed to be highlighted is instead grayed out.

(Personally, I think all of this text in both of these screenshots should just be black, with icons to indicate the things they indicate, if any such indication is given.)

**Comment by PhoenixRiver** [comment]
Although I agree taht some fo the colouring is unnecessary and causes
problems in terms of colourblindness dispensing with it where it does
not cause detriment to colourblind players and serves to highlight
things for other players would seem to reduce the game decidedly for
the majority of players and for little benefit for colourblind
players... possibly even to their detriment; to explain, not being
colourblind I might assume that the dark colours stand out more,
however after a good time living in the real world where colourblind
people have to put up with few adaptations to their problems might not
the dark colours be know by them not to be so important as the harder
to see but lighter colours... after all any use of colour in any
setting at all would do this for them - traffic lights all the way
through to the colour of dangerous insects or snakes...

I'm just suggesting it might be worth bearing in mind that the
assumptions made by a non-colourblind user of what a colourblind user
interprets might not be correct (please forgive me if you are indeed
colourblind; I assumed not given the mode fo your writing). To make
such mistakes would probably annoy colourblind users more than just
being blind to their lack of seeing the full trichromatic color
spectrum! ;)

Just a thought,

River *<:@)

**Comment by onpon4** [comment]
The world at large has a lot more accessibility for colorblind people than you probably realize. You mentioned traffic lights, which are legally required to follow a specific order in the U.S.: red on top, then yellow, then green. That's an accessibility feature, as is the legal requirement for permanent blinking red lights to be accompanied by stop signs, which color-sighted people have probably never noticed, but is essential for colorblind people to be able to discern permanent blinking red lights from permanent blinking  yellow lights.

As for dangerous insects and snakes... not sure what point you're trying to make with that. I'm not aware of any insect or snake whose dangerous nature is indicated by their color. If anything it would be poisonous frogs. But either way I don't see what that has to do with anything especially since those aren't exactly a feature of modern life.

> I'm just suggesting it might be worth bearing in mind that the assumptions made by a non-colourblind user of what a colourblind user interprets might not be correct

That's true, but I don't see why you're pointing this out at this time. Coblis is designed for that exact problem: so you can see what colorblind folks see.

My introduction to colorblindness was in high school when my math teacher at the time gave us an assignment to do some sort of graph that needed to be multicolored, and he had a very specific instruction: don't use red and green or pink and green, because he had a form of red-green colorblindness. I don't know which type, but the point is, we had to avoid those colors because he couldn't discern them reliably. He even mentioned sometimes having to ask people what color something is when shopping for clothing and such.

> To make such mistakes would probably annoy colourblind users more than just being blind to their lack of seeing the full trichromatic color spectrum! ;)

Just to point out, this is an assumption from a non-colorblind person... which, as you pointed out, "might not be correct".

We don't need to understand the *feelings* of colorblind people to provide accessibility for them. I've been doing it in my games for years and I've never once been contacted by a colorblind person. It's a pretty easy thing to do and when you do it right there's no detriment to anyone else.

> dispensing with it where it does not cause detriment to colourblind players and serves to highlight things for other players would seem to reduce the game decidedly

That depends. If the usage is ugly (which I would argue a lot of it is), then it would enhance it, especially if the benefit is minimal (such as highlighting certain attributes as green or red in the outfitter, which I would note is inconsistent between kinds of outfits). So in those cases I would get rid of the text coloring regardless because the aesthetics of having nice-looking text override the very very minor benefit of having a reminder that losing CPU capacity is bad.

**Comment by onpon4** [comment]
I decided to give Color Oracle a try. It's useless; it just does a single screen grab and then goes away the second you use your mouse or keyboard. Basically just a worse version of Coblis.

**Comment by PhoenixRiver** [comment]
As you metioned my "assumption" may not be correct - though since I
ued it as an example of the sort of problem it doesn't fit the
definition of assumption - and I have also been adapting things for a
very long time to various ways of seeing the world; either through
family experience, friends , requirements of work etc. I, also, have
never been contacted by people about my work except by those with
problems other than accessiblity issues... this didn't mean (in the
case of those I sought out for their opinion) that they didn't have
issues, just that they had learnt there was little point in doing so
and so didn't bother (though Apple is a good example of a company that
does get a lot of feedback and promotes the "don't bother" attitude by
steadfastly failing to respond or address those accessiblity issues
pointed out to it).

My experience with my "blind" mother-in-law is probably the most
recent, pertinent case and she has a lot to say about accessibility if
you ask her but she'll not trouble you with it otherwise. One of the
things that most troubled her with seeing things - you see she is only
"legally blind", not actually, she has "tunnel-vision" (something
like) as well as some blurring not fixable with lenses, that enabled
her to see but only in a slowly (over her life) narowing field of
view. One of the things that really annoyed her when it became
fashionable to make things easier for colourblind people was to stop
hightlighting text with colours (at least this was the solution a lot
of cheapskates used because it was easy)... for her this meant that it
became hugely time consuming to find important text because she could
not quickly scan text (having such a limited field of view) and now
had to read everything to find the important bits... she learned many
tricks to finding important text which involved just asking someone
with good sight to find them for her and not go to the trouble of
doing it herself. You might think this is not so much a problem but
disabled people have a LOT of forms to fill in.

The assumptions that we make of people who see the world differently
are more than just wong, they are often not even in the ballpark, like
assuming they'll tell you when they have a problem.

River

**Comment by onpon4** [comment]
> I, also, have never been contacted by people about my work except by those with problems other than accessiblity issues... this didn't mean (in the case of those I sought out for their opinion) that they didn't have issues, just that they had learnt there was little point in doing so and so didn't bother (though Apple is a good example of a company that does get a lot of feedback and promotes the "don't bother" attitude by steadfastly failing to respond or address those accessiblity issues pointed out to it).

An oddly casual description of certain aspects of systemic oppression in our society.

It happens with a lot of people. Someone learning that there's little point in raising an issue is something I can *personally* testify to having experienced. Like how I've learned that defending myself when someone misgenders me never does any good, or how I've learned that speaking up about blatant discrimination in the workplace only leads to more discrimination, or how I've learned that no matter how many times I tell Walgreens to stop calling me by my dead name they'll still do it. (And that's not even going into the discrimination I deal with for being neurodivergent.)

When you face a society that disparages you and hates your very existence, you learn to choose your battles.

That said, I'm not sure why you bring this up. We shouldn't need someone to complain before we start caring about their accessibility needs.

> One of the things that really annoyed her when it became fashionable to make things easier for colourblind people was to stop hightlighting text with colours (at least this was the solution a lot of cheapskates used because it was easy)... for her this meant that it became hugely time consuming to find important text because she could not quickly scan text (having such a limited field of view) and now had to read everything to find the important bits...

Just a note: if you're talking about Web pages, there's a very good reason to not use colors to indicate text meaning: it's inaccessible. The standard way to indicate text meaning in HTML is with HTML tags, which can be styled in any arbitrary way. So all your mother has to do is create a custom style that enables coloring of certain HTML tags in certain ways.

Incidentally, the first thing that came to my mind is that your mother-in-law's annoyance is, oddly enough, ableist. I've never been able to just scan important text no matter how much school pressured me to do it. If I try, all of it gets scrambled in my head and I end up with no idea what I've looked at. I have to read out every bit of a block of text (like a paragraph) and sound it out in my head. So I can only read as fast as one can speak. The idea of being able to just find "important text" immediately without carefully reading the entire thing is a fantasy to me.

Of course, that ableism also extents to completely blind people, who can't see color at all; screen readers aren't able to handle text coloring well because color, by its very nature, does not have a specific meaning. (And I can only assume that like me, most blind people probably can't just instantly scan through text like your mother is apparently accustomed to.)

> she learned many tricks to finding important text which involved just asking someone with good sight to find them for her and not go to the trouble of doing it herself. You might think this is not so much a problem but disabled people have a LOT of forms to fill in.

Incidentally, this wasn't much of an accessibility problem. No more than I have every day no matter what you do to accommodate my needs. So I find the attitude insulting.

The appropriate response would be that disabled people shouldn't need to fill out all these forms (which I do think is a problem), not that it's such a drag that she can't fill them out super quickly because they were made more accessible for colorblind and blind people.

**Comment by PhoenixRiver** [comment]
> An oddly casual description of certain aspects of systemic oppression in our
> society.

Suffering from systematic oppression may have lead me to a rather
casual attitude to systematic oppression as a coping mechanism to deal
the stress.

I wish you the best in your struggles, and I hope that you are, at
some point soon, able to convince people to correctly refer to your
gender though I understand that it may not be possible in this
language in which case you have my sympathy. Ido have to say though
that the failure to address you by your actual name seems rather
remiss and something that is not legally reasonable (though I
understand in some places this is different).

> That said, I'm not sure why you bring this up. We shouldn't need someone to
> complain before we start caring about their accessibility needs.

I brought this specific instance up due to the importance of being
careful to check ones assumptions of something before one acts on
those assumptions in an area where I have had specific programming
experience of the need to be careful.

> Just a note: if you're talking about Web pages, there's a very good reason
> to not use colors to indicate text meaning: it's inaccessible.

Her screen reader of the time was able to search on colour tags but
maybe that has changed, certainly she has to the point it wouldn't
help much now anyway (she is now 100% blind).

> The idea of being able to just find "important text" immediately
> without carefully reading the entire thing is a fantasy to me.

Indeed, I can sympathise entirely, thankfully searching digital text
is much easier than written text so life is becoming easier, no?
Especially as digital text is becoming more and more often tagged.
Though I'll admit that it doesn't work well when time is of the
essence or the knowledge needed to search is unknown... though screen
readers sometimes have advantages over human eyes in these respects if
the text is compliant.

> because they were made more accessible for colorblind and blind people.

I'm confused by this statement since I am specifically talking about a
blind person having more problems with the forms (and I'll note that
braille has no "colour", though due to systematic oppression my
mother-in-law was not taught braille at school, her deaf-blind school
believed their students should learn to speak and lip read like able
people; no, I don't know how this is supposed to work long-term but
then again I don't understand how systematic oppression is supposed to
work long-term either, possibly on the assumption that their students
disabilities would not worsen with age - a terrible assumption in the
case of the majority of deaf and/or blind people).

Back to the point at hand, assumptions can be dangerous and to remove
things that help part of the userbase is probably unhelpful. Might I
suggest that some of the changes that you seem to suggest (e.g.
changing the shade of colours used) be adopted where it does not
remove information for any part of the player base and an option in
the settings be created to allow changing the interface more
drastically - though I thought we already had a system for chanigng
the UI layout? (does it not allow changing text colours?)

I hope I have not made unwarrented assumptions in this discussion and
I apologise that I seem to have provoked some considerable ire, it was
not my intention, neither did I mean to question your competance on
this topic, I simply wanted to improve this game that I enjoy and have
enjoyed for many years and would like to continue to help in the
development of despite my current inability to sort out a system to
allow me to submit meaningful code.

Yours sincerely,

River

**Comment by onpon4** [comment]
> Back to the point at hand, assumptions can be dangerous and to remove things that help part of the userbase is probably unhelpful.

The only benefit of the current colored text is to convey information that isn't conveyed anywhere else. Icons could do that just as well if not better, for everyone.

> though I thought we already had a system for chanigng the UI layout?

No, it's all hardcoded in C code.

> I hope I have not made unwarrented assumptions in this discussion and I apologise that I seem to have provoked some considerable ire

Sorry, I'm very sensitive is all. Look up Histrionic Personality Disorder and Borderline Personality Disorder, that might help with understanding a bit. (I've not been diagnosed with anything but I experience most BPD symptoms and all HPD symptoms.)

**Comment by onpon4** [comment]
I believe this issue is now sufficiently solved. All necessary information can be gleamed without any color-sight. There are some minor issues for someone with blue cone monochromacy under high light conditions, but this can be mitigated via "colorblind mode" which is now accessible from the options menu and causes the game to display as it would for someone with rod monochromacy (i.e. purely black, white, and shades of gray).

Closing this now; version 0.9.0 will be the first version of Naev which is fully colorblind-accessible. :tada:

🕵️
