### ISSUE TITLE
Stats in info screen vs equipment tab

### ISSUE THREAD

**Issue by ids1024** [naev/naev#886]
Should these just be the same (ideally with the same code)? They are fairly similar, but with some difference, most notably the green/red in the equipper, and the list of `stats` in the info screen (which includes things like `Cloaking` and `Nebula Resistance` that are not visible on the equipping screen).

**Comment by bobbens** [comment]
Ideally yes. The interface is less than ideal. It might be worth making a better widget sort of like a table with the possibility to scroll to handle it all more elegantly. It's fairly nasty code.

**Comment by onpon4** [comment]
OK, so I just took a quick look at this and it seems most of it is simply because the two screens serve different purposes. Some observations:

* The green/red text (and now symbols) are there to show how your outfitting of the ship improves the ship and how it makes it worse. It's not in the Info screen because that screen is more about showing your ship's basic info.
* The stats you mention actually are in the outfitter, just in a different place: the tooltip for the ship. I don't think it would fit below the stats as it's shown on the Info screen since the equipment tab uses more vertical space for other stuff.
* Info about price would be essentially useless out in space. Actually, on that note, the info about the CPU capacity of the ship should probably be removed from the Info screen as well.

My takeaway is that the lack of colored text should remain on the Info screen (since that's irrelevant info and may be distracting), CPU capacity should be removed, and ship stats are probably fine as they are. Actually I think the bigger issue with ship stats is that many of them are irrelevant while you're out in space; you don't need to know that you have +140% crew, just that you have 156 total crew. So it may be a good idea to have something separate generate the ship stats for out in space (in a way that isn't colorized and excludes unimportant stat changes).

🕵️

**Comment by bobbens** [comment]
I looked at it quickly and they seem to be the same. Am I missing something or is this issue solved?

**Comment by bobbens** [comment]
Seems to be solved, closing.
