### ISSUE TITLE
When a faction is not <known>,  its ships, systems, and assets are still clearly marked

### ISSUE THREAD

**Issue by ids1024** [naev/naev#891]
When a faction lacks the `<known>` tag, the faction's presence is listed as "unknown". But the name and/or logo of the faction appears when targeting a ship or planet of that faction, or selecting a system controlled by the faction on the map.

**Comment by onpon4** [comment]
Luckily none of the "unknown" factions can be found with normal gameplay yet. But this definitely needs to be fixed. (Probably should just display "Unknown" anywhere the faction name displays and not show a faction logo.)

**Comment by onpon4** [comment]
I've pushed some commits which should resolve this. The GUIs have been updated to not show faction info for unknown factions, the map no longer displays unknown factions (only the "Unknown" presences value, though I wouldn't be opposed to removing that as well if we want that), and the comm channel no longer shows the logo of unknown factions. The only way to find out about the faction of an unknown faction ship now is through the ship's name, which can be fudged by Lua to avoid this; I've implemented an example for the Thurion where Thurion ships are renamed to "Unknown" in the Thurion spawn script if the Thurion faction is unknown. (This was not made universal because this is not desired behavior everywhere, e.g. the Proteron Dissident faction is designed to masquerade as regular civilians.)

🕵️
