### ISSUE TITLE
Harmonize the use of relative and absolute velocity on rockets

### ISSUE THREAD

**Issue by nenau-again** [naev/naev#922]
As I mentioned in https://github.com/naev/naev/pull/921, I believe the computation of velocity for rockets is odd and confusing. After having got a look at the code and some experimentations, here is how it works :
* When the rocket is fired, its velocity is the same as the pilot's, excepted for rockets with 0 thrust, that start at their max vel+the pilot's vel.
* Rocket is updated with Runge Kutta, and absolute velocity is bounded by max velocity, excepted again for rockets with 0 thrust, for whom velocity is not bounded
* In the thinking step of seekers, absolute velocity is again bounded (but only for seekers)
* Right now, only the mace rocket has nonzero thrust

So here are examples of behaviour :
* When you fire a seeker while moving towards the target, the seeker starts at its max vel+your vel, and just after, during the update step, this velocity is reduced, so the seeker starts at its max vel
* When you fire a seeker while moving backwards (you try to escape your target), it starts at its max vel - your vel (which is slow and handicaps the seeker)
* When you fire a banshee, it works exactly as a (slow) bolt weapon
* When you fire a Mace rocket, it starts at your velocity and then accelerates until it reaches its max vel in the absolute referential (but it's so fast that it's hard to make the difference).

And the question is now : what is the desired behaviour ?
* I believe that dumb ammo should use relative velocity because they are used the same way as bolt weapons (am I right ?). This is more or less the case right now as the speed of the mace rocket is far too high for that to make any difference.
* Seekers should use absolute velocity in all cases, otherwise, it's odd imho.

If we want to get both those behaviour in a consistent physics, the best way could be to get all the missiles to start at relative velocity and then make a slow transition towards absolute velocity. As the dumb weapons are short range, they would mainly remain at relative velocity while seekers would end up at absolute velocity.
...Or we could have different physics for dumb and seekers, but simply make sure all seekers end up at absolute velocity.

What do you think ?

What's more, thrust of missiles seems like a good way to add a few fanciness in the ballistic, but I guess there is a reason why it is nearly unused. What is it ?

**Comment by onpon4** [comment]
One thought that comes to mind is that the max speed could serve not as an absolute cap, but instead as a restriction on increase to speed. So if the missile/rocket is already moving in the direction it "wants" to thrust at max speed or higher, it wouldn't change velocity. For slight direction changes the speed in the "wrong" direction could be slightly reduced (like ship speed in The Ur-Quan Masters) rather than instantly capped; it's not how physics actually works but I know from experience that feels generally natural and gives generally expected results.

As far as real-world implications, this would mean that the Mace rocket would start off at the ship's velocity and stay there if that velocity (in the fired direction) is above the max velocity of the Mace, but otherwise it would accelerate to its max speed as it currently does. This would increase its range slightly for a persuer and decrease its range for a pilot who is fleeing.

And homing missiles that for some reason never need to change direction would rocket through (no pun intended) faster than top speed. But in practice they would start at faster than top speed and gradually slow down to top speed.
